// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(chio_kernel_mobileFFI)
import chio_kernel_mobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_chio_kernel_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_chio_kernel_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct PortablePassportMetadata {
    public var subject: String
    public var issuerHex: String
    public var issuedAt: UInt64
    public var expiresAt: UInt64
    public var evaluatedAt: UInt64
    public var payloadCanonicalHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(subject: String, issuerHex: String, issuedAt: UInt64, expiresAt: UInt64, evaluatedAt: UInt64, payloadCanonicalHex: String) {
        self.subject = subject
        self.issuerHex = issuerHex
        self.issuedAt = issuedAt
        self.expiresAt = expiresAt
        self.evaluatedAt = evaluatedAt
        self.payloadCanonicalHex = payloadCanonicalHex
    }
}



extension PortablePassportMetadata: Equatable, Hashable {
    public static func ==(lhs: PortablePassportMetadata, rhs: PortablePassportMetadata) -> Bool {
        if lhs.subject != rhs.subject {
            return false
        }
        if lhs.issuerHex != rhs.issuerHex {
            return false
        }
        if lhs.issuedAt != rhs.issuedAt {
            return false
        }
        if lhs.expiresAt != rhs.expiresAt {
            return false
        }
        if lhs.evaluatedAt != rhs.evaluatedAt {
            return false
        }
        if lhs.payloadCanonicalHex != rhs.payloadCanonicalHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(subject)
        hasher.combine(issuerHex)
        hasher.combine(issuedAt)
        hasher.combine(expiresAt)
        hasher.combine(evaluatedAt)
        hasher.combine(payloadCanonicalHex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePortablePassportMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PortablePassportMetadata {
        return
            try PortablePassportMetadata(
                subject: FfiConverterString.read(from: &buf), 
                issuerHex: FfiConverterString.read(from: &buf), 
                issuedAt: FfiConverterUInt64.read(from: &buf), 
                expiresAt: FfiConverterUInt64.read(from: &buf), 
                evaluatedAt: FfiConverterUInt64.read(from: &buf), 
                payloadCanonicalHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PortablePassportMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.subject, into: &buf)
        FfiConverterString.write(value.issuerHex, into: &buf)
        FfiConverterUInt64.write(value.issuedAt, into: &buf)
        FfiConverterUInt64.write(value.expiresAt, into: &buf)
        FfiConverterUInt64.write(value.evaluatedAt, into: &buf)
        FfiConverterString.write(value.payloadCanonicalHex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePortablePassportMetadata_lift(_ buf: RustBuffer) throws -> PortablePassportMetadata {
    return try FfiConverterTypePortablePassportMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePortablePassportMetadata_lower(_ value: PortablePassportMetadata) -> RustBuffer {
    return FfiConverterTypePortablePassportMetadata.lower(value)
}


public struct VerifiedCapability {
    public var id: String
    public var subjectHex: String
    public var issuerHex: String
    public var scopeJson: String
    public var issuedAt: UInt64
    public var expiresAt: UInt64
    public var evaluatedAt: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, subjectHex: String, issuerHex: String, scopeJson: String, issuedAt: UInt64, expiresAt: UInt64, evaluatedAt: UInt64) {
        self.id = id
        self.subjectHex = subjectHex
        self.issuerHex = issuerHex
        self.scopeJson = scopeJson
        self.issuedAt = issuedAt
        self.expiresAt = expiresAt
        self.evaluatedAt = evaluatedAt
    }
}



extension VerifiedCapability: Equatable, Hashable {
    public static func ==(lhs: VerifiedCapability, rhs: VerifiedCapability) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.subjectHex != rhs.subjectHex {
            return false
        }
        if lhs.issuerHex != rhs.issuerHex {
            return false
        }
        if lhs.scopeJson != rhs.scopeJson {
            return false
        }
        if lhs.issuedAt != rhs.issuedAt {
            return false
        }
        if lhs.expiresAt != rhs.expiresAt {
            return false
        }
        if lhs.evaluatedAt != rhs.evaluatedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(subjectHex)
        hasher.combine(issuerHex)
        hasher.combine(scopeJson)
        hasher.combine(issuedAt)
        hasher.combine(expiresAt)
        hasher.combine(evaluatedAt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerifiedCapability: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VerifiedCapability {
        return
            try VerifiedCapability(
                id: FfiConverterString.read(from: &buf), 
                subjectHex: FfiConverterString.read(from: &buf), 
                issuerHex: FfiConverterString.read(from: &buf), 
                scopeJson: FfiConverterString.read(from: &buf), 
                issuedAt: FfiConverterUInt64.read(from: &buf), 
                expiresAt: FfiConverterUInt64.read(from: &buf), 
                evaluatedAt: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: VerifiedCapability, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.subjectHex, into: &buf)
        FfiConverterString.write(value.issuerHex, into: &buf)
        FfiConverterString.write(value.scopeJson, into: &buf)
        FfiConverterUInt64.write(value.issuedAt, into: &buf)
        FfiConverterUInt64.write(value.expiresAt, into: &buf)
        FfiConverterUInt64.write(value.evaluatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedCapability_lift(_ buf: RustBuffer) throws -> VerifiedCapability {
    return try FfiConverterTypeVerifiedCapability.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifiedCapability_lower(_ value: VerifiedCapability) -> RustBuffer {
    return FfiConverterTypeVerifiedCapability.lower(value)
}


public enum ChioMobileError {

    
    
    case InvalidJson(message: String
    )
    case InvalidHex(message: String
    )
    case InvalidCapability(message: String
    )
    case InvalidPassport(message: String
    )
    case AttestationUnavailable(message: String
    )
    case AttestationRejected(message: String
    )
    case KernelKeyMismatch(message: String
    )
    case SigningFailed(message: String
    )
    case EvaluationDenied(message: String
    )
    case Internal(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChioMobileError: FfiConverterRustBuffer {
    typealias SwiftType = ChioMobileError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChioMobileError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidJson(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidHex(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidCapability(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidPassport(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .AttestationUnavailable(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .AttestationRejected(
            message: try FfiConverterString.read(from: &buf)
            )
        case 7: return .KernelKeyMismatch(
            message: try FfiConverterString.read(from: &buf)
            )
        case 8: return .SigningFailed(
            message: try FfiConverterString.read(from: &buf)
            )
        case 9: return .EvaluationDenied(
            message: try FfiConverterString.read(from: &buf)
            )
        case 10: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChioMobileError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidJson(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidHex(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidCapability(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidPassport(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .AttestationUnavailable(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .AttestationRejected(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .KernelKeyMismatch(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .SigningFailed(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .EvaluationDenied(message):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension ChioMobileError: Equatable, Hashable {}

extension ChioMobileError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}
public func attestAppAttest(keyId: String, challengeHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_attest_app_attest(
        FfiConverterString.lower(keyId),
        FfiConverterString.lower(challengeHex),$0
    )
})
}
public func attestPlayIntegrity(nonceHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_attest_play_integrity(
        FfiConverterString.lower(nonceHex),$0
    )
})
}
public func evaluate(requestJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_evaluate(
        FfiConverterString.lower(requestJson),$0
    )
})
}
public func signReceipt(bodyJson: String, signingSeedHex: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_sign_receipt(
        FfiConverterString.lower(bodyJson),
        FfiConverterString.lower(signingSeedHex),$0
    )
})
}
public func verifyAppAttestEvidence(keyId: String, challengeHex: String, appId: String, attestationCborHex: String, previousCounter: Int64)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_verify_app_attest_evidence(
        FfiConverterString.lower(keyId),
        FfiConverterString.lower(challengeHex),
        FfiConverterString.lower(appId),
        FfiConverterString.lower(attestationCborHex),
        FfiConverterInt64.lower(previousCounter),$0
    )
})
}
public func verifyCapability(tokenJson: String, authorityPubHex: String)throws  -> VerifiedCapability {
    return try  FfiConverterTypeVerifiedCapability.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_verify_capability(
        FfiConverterString.lower(tokenJson),
        FfiConverterString.lower(authorityPubHex),$0
    )
})
}
public func verifyMobileReceipt(receiptJson: String, evidenceJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_verify_mobile_receipt(
        FfiConverterString.lower(receiptJson),
        FfiConverterString.lower(evidenceJson),$0
    )
})
}
public func verifyPassport(envelopeJson: String, issuerPubHex: String, nowSecs: Int64)throws  -> PortablePassportMetadata {
    return try  FfiConverterTypePortablePassportMetadata.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_verify_passport(
        FfiConverterString.lower(envelopeJson),
        FfiConverterString.lower(issuerPubHex),
        FfiConverterInt64.lower(nowSecs),$0
    )
})
}
public func verifyPlayIntegrityEvidence(token: String, expectedNonce: String, expectedPackageName: String, expectedAudience: String, jwksJson: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeChioMobileError.lift) {
    uniffi_chio_kernel_mobile_fn_func_verify_play_integrity_evidence(
        FfiConverterString.lower(token),
        FfiConverterString.lower(expectedNonce),
        FfiConverterString.lower(expectedPackageName),
        FfiConverterString.lower(expectedAudience),
        FfiConverterString.lower(jwksJson),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_chio_kernel_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_attest_app_attest() != 57287) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_attest_play_integrity() != 54025) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_evaluate() != 49976) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_sign_receipt() != 62477) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_verify_app_attest_evidence() != 45468) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_verify_capability() != 4858) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_verify_mobile_receipt() != 27575) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_verify_passport() != 33721) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chio_kernel_mobile_checksum_func_verify_play_integrity_evidence() != 23668) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all