"""Closed current P6 gate commands, frozen before final package review."""

GATES = {'alloc': {'command': ['cargo',
                       'check',
                       '--offline',
                       '--locked',
                       '--manifest-path',
                       'fixtures/recovery-portable-consumer/Cargo.toml'],
           'cwd': '.'},
 'cage-inventory': {'command': ['python3', 'scripts/check-cage-all-target-inventory.py', '--source-only'],
                    'cwd': '.'},
 'cage-inventory-mutations': {'command': ['python3', 'scripts/tests/check-cage-all-target-inventory.test.py'],
                              'cwd': '.'},
 'cage-script-mutations': {'command': ['bash', 'scripts/tests/check-cage-enforcement.test.sh'], 'cwd': '.'},
 'clippy': {'command': ['cargo',
                        'clippy',
                        '--offline',
                        '--locked',
                        '-p',
                        'chio-core-types',
                        '-p',
                        'chio-security-types',
                        '-p',
                        'chio-cage',
                        '-p',
                        'chio-flow',
                        '-p',
                        'chio-recovery',
                        '-p',
                        'chio-semantic-contracts',
                        '-p',
                        'chio-kernel',
                        '-p',
                        'chio-process',
                        '-p',
                        'chio-store-sqlite',
                        '-p',
                        'chio-control-plane',
                        '-p',
                        'chio-conformance',
                        '-p',
                        'chio-spec-codegen',
                        '-p',
                        'xtask',
                        '-p',
                        'chio-cli',
                        '--all-targets',
                        '--',
                        '-D',
                        'warnings'],
            'cwd': '.'},
 'conformance-lib': {'command': ['cargo', 'test', '--offline', '--locked', '-p', 'chio-conformance', '--lib'],
                     'cwd': '.'},
 'contracts': {'command': ['cargo',
                           'test',
                           '--offline',
                           '--locked',
                           '-p',
                           'chio-core-types',
                           '-p',
                           'chio-security-types'],
               'cwd': '.'},
 'diff': {'command': ['git', 'diff', '--check'], 'cwd': '.'},
 'domains': {'command': ['python3', 'scripts/check-domain-separation.py'], 'cwd': '.'},
 'format': {'command': ['cargo', 'fmt', '--all', '--', '--check'], 'cwd': '.'},
 'guard-mutations': {'command': ['python3', 'scripts/tests/check-recovery-p0.test.py'], 'cwd': '.'},
 'hygiene': {'command': ['python3', 'scripts/check-rust-file-hygiene.py'], 'cwd': '.'},
 'kernel-doc-tests': {'command': ['cargo', 'test', '--offline', '--locked', '-p', 'chio-kernel', '--doc'],
                      'cwd': '.'},
 'kernel-lib': {'command': ['cargo', 'test', '--offline', '--locked', '-p', 'chio-kernel', '--lib'],
                'cwd': '.'},
 'layering': {'command': ['bash', 'scripts/check-workspace-layering.sh'], 'cwd': '.'},
 'lint-parity': {'command': ['python3', 'scripts/check-lint-parity.py'], 'cwd': '.'},
 'msrv-alloc': {'command': ['cargo',
                            '+1.93.0',
                            'check',
                            '--offline',
                            '--locked',
                            '--manifest-path',
                            'fixtures/recovery-portable-consumer/Cargo.toml'],
                'cwd': '.'},
 'msrv-std': {'command': ['cargo',
                          '+1.93.0',
                          'check',
                          '--offline',
                          '--locked',
                          '--manifest-path',
                          'fixtures/recovery-portable-consumer/Cargo.toml',
                          '--features',
                          'std'],
              'cwd': '.'},
 'owner-doc-tests': {'command': ['cargo',
                                 'test',
                                 '--offline',
                                 '--locked',
                                 '-p',
                                 'chio-control-plane',
                                 '--doc'],
                     'cwd': '.'},
 'owning-tests': {'command': ['cargo',
                              'test',
                              '--offline',
                              '--locked',
                              '-p',
                              'chio-core-types',
                              '-p',
                              'chio-security-types',
                              '-p',
                              'chio-cage',
                              '-p',
                              'chio-flow',
                              '-p',
                              'chio-recovery',
                              '-p',
                              'chio-semantic-contracts',
                              '-p',
                              'chio-process',
                              '-p',
                              'chio-spec-codegen',
                              '-p',
                              'xtask',
                              '--',
                              '--test-threads=2'],
                  'cwd': '.'},
 'pure-guard': {'command': ['python3', 'scripts/check-recovery-p0.py', '--offline'], 'cwd': '.'},
 'python': {'command': ['/Users/connor/Medica/backbay/standalone/arc/sdks/python/chio-crewai/.venv/bin/python',
                        '-m',
                        'pytest',
                        '-q',
                        'sdks/python/chio-sdk-python/tests'],
            'cwd': '.'},
 'python-codegen': {'command': ['target/debug/xtask', 'codegen', 'python', '--check'], 'cwd': '.'},
 'rust-codegen': {'command': ['target/debug/xtask', 'codegen', 'rust', '--check'], 'cwd': '.'},
 'schemas': {'command': ['bash', 'scripts/check-chio-schema-registry.sh'], 'cwd': '.'},
 'std': {'command': ['cargo',
                     'check',
                     '--offline',
                     '--locked',
                     '--manifest-path',
                     'fixtures/recovery-portable-consumer/Cargo.toml',
                     '--features',
                     'std'],
         'cwd': '.'},
 'toolchain-parity': {'command': ['python3', 'scripts/check-rust-toolchain-parity.py'], 'cwd': '.'},
 'ts': {'command': ['node',
                    'node_modules/vitest/vitest.mjs',
                    'run',
                    'test/recovery_schema.test.ts',
                    'test/recovery_p1_schema.test.ts',
                    'test/recovery_p2_schema.test.ts',
                    'test/recovery_p3_schema.test.ts',
                    'test/recovery_p4_schema.test.ts',
                    'test/recovery_p5_schema.test.ts',
                    'test/recovery_client.test.ts',
                    'test/recovery_p6_schema.test.ts',
                    'test/recovery_product_client.test.ts',
                    'test/recovery_setup_client.test.ts'],
        'cwd': 'sdks/typescript/packages/conformance'},
 'ts-codegen': {'command': ['target/debug/xtask', 'codegen', 'ts', '--check'], 'cwd': '.'},
 'ts-conformance-build': {'command': ['node',
                                      'node_modules/typescript/bin/tsc',
                                      '-p',
                                      'packages/conformance/tsconfig.json',
                                      '--noEmit'],
                          'cwd': 'sdks/typescript'},
 'ts-node-build': {'command': ['node',
                               'node_modules/typescript/bin/tsc',
                               '-p',
                               'packages/node-http/tsconfig.json'],
                   'cwd': 'sdks/typescript'},
 'wasm': {'command': ['cargo',
                      'check',
                      '--offline',
                      '--locked',
                      '--manifest-path',
                      'fixtures/recovery-portable-consumer/Cargo.toml',
                      '--target',
                      'wasm32-unknown-unknown'],
          'cwd': '.'},
 'wire-lock': {'command': ['python3', 'scripts/check-wire-schemas.py'], 'cwd': '.'}}
