# DO NOT EDIT - regenerate via 'cargo xtask codegen --lang python'.
#
# Source: spec/schemas/chio-wire/v1/**/*.schema.json
# Tool:   datamodel-code-generator==0.34.0 (see xtask/codegen-tools.lock.toml)
# Schema sha256: bab930356fcbf944c42cdbdaef62cc82db4c242eee4942218590770e15ff1c0e
#
# Manual edits will be overwritten by the next regeneration; the
# spec-drift CI lane enforces this header on every file
# under sdks/python/chio-sdk-python/src/chio_sdk/_generated/.

"""Generated Pydantic v2 models for the Chio wire protocol (chio-wire/v1).

Re-exports every subpackage so callers can write
``from chio_sdk._generated import CapabilityToken`` for the canonical
capability token shapes without knowing the per-subpackage layout. Class
names that collide across subpackages (for example ``Kind`` defined in
both ``anchor`` and ``capability``) are re-exported under a
``<Subpkg><Class>`` alias (``AnchorKind``, ``CapabilityKind``) so
neither definition silently shadows the other. The SCHEMA_SHA256
constant pins the schema set this build was generated from; the
spec-drift CI lane reads it to detect tampering.
"""

from __future__ import annotations

from pydantic import TypeAdapter
from pydantic_core import core_schema

#: SHA-256 of the lexicographically sorted concatenation of every
#: ``spec/schemas/chio-wire/v1/**/*.schema.json`` byte stream that was
#: fed into datamodel-code-generator at build time.
SCHEMA_SHA256 = "bab930356fcbf944c42cdbdaef62cc82db4c242eee4942218590770e15ff1c0e"

from .agent import Body as AgentBody, Body3, ChioAgentmessageHeartbeat, ChioAgentmessageListCapabilities, ChioAgentmessageToolCallRequest, ChioGovernedActiveResponseIntentBody, ChioGovernedTransactionIntent, MaxAmount, OrderedEffect
from .anchor import Body as AnchorBody, CheckpointId, ChioAnchorBatchV1, Inclusion, Kind as AnchorKind, Witness, WitnessReceipt, WitnessState, WitnessState1, WitnessState2, WitnessState3
from .capability import AggregateRootPublicKey, AggregateRootSignature, AggregateRootSigningAlgorithm, Algorithm as CapabilityAlgorithm, Attenuation, AttenuationProof, AttenuationWitness, Body as CapabilityBody, Caveat, ChioAggregateBudgetRootBinding, ChioAggregateInvocationBudget, ChioAggregateInvocationBudget1, ChioAggregateInvocationBudget2, ChioCapabilityGrant, ChioCapabilityNegotiationV1, ChioCapabilityRevocationEntry, ChioCapabilitytoken, ChioCumulativeApprovalRootBinding, ChioGovernedApprovalToken, ChioOpaqueSupplementalAuthorization, ChioScope, ChioThresholdApprovalProposal, ChioVerifiedApprovalSetBody, Constraint, CumulativeApprovalDelegableConstraint, CumulativeApprovalDirectConstraint, CumulativeRootMonetaryAmount, CumulativeRootPublicKey, CumulativeRootSignature, CumulativeRootSigningAlgorithm, Decision as CapabilityDecision, DelegationLink, GenericConstraint, GovernedApprovalPublicKey, GovernedApprovalSignature, GrantKind, GrantSubsetRelation, Kind as CapabilityKind, LegacyApprovalConstraint, MonetaryAmount, Operation as CapabilityOperation, PromptGrant, ResourceGrant, ScopeAttenuation, Subset, ThresholdProposalPublicKey, ThresholdProposalSignature, TokenDigest, ToolGrant, Value, Value1, Value2
from .error import ChioToolcallerrorCapabilityDenied, ChioToolcallerrorCapabilityExpired, ChioToolcallerrorCapabilityRevoked, ChioToolcallerrorInternalError, ChioToolcallerrorPolicyDenied, ChioToolcallerrorToolServerError, Detail as ErrorDetail
from .federation import CapabilityLeaseRef, ChioBilateralDsseSignatureSliceEnvelope, ChioBilateralDsseSignatureSliceStatement, CoSign, CrossOrgVisibility, Digest as FederationDigest, GovernanceReceiptRef, HashRecord, JointDisposition, KernelIdentity, PolicyEvaluationSummary, PolicyVerdict, Predicate, Signature as FederationSignature, SubjectItem, Verdict as FederationVerdict
from .jsonrpc import ChioJsonRpc20Notification, ChioJsonRpc20Request, ChioJsonRpc20Response, ChioJsonRpc20Response1, ChioJsonRpc20Response2, Error as JsonrpcError
from .kernel import BoundTo, ChioCombinedAdmissionCaptureMetadata, ChioKernelmessageCapabilityList, ChioKernelmessageCapabilityRevoked, ChioKernelmessageHeartbeat, ChioKernelmessageToolCallChunk, ChioKernelmessageToolCallResponse, ChioSignedExecutionNonce, Detail as KernelDetail, Error as KernelError, Error10, Error11, Error12, Error13, Error9, Nonce as KernelNonce, QuotaKey, Result as KernelResult, Result2, Result3, Result4, Result5
from .provenance import ChioProvenanceAttestationBundle, ChioProvenanceCallChainContext, ChioProvenanceStamp, ChioProvenanceVerdictLink, ChioProvenanceVerdictLink1, ChioProvenanceVerdictLink2, ChioProvenanceVerdictLink3, ChioProvenanceVerdictLink4, CredentialKind as ProvenanceCredentialKind, EvidenceClass as ProvenanceEvidenceClass, Scheme as ProvenanceScheme, Statement, Tier as ProvenanceTier, Verdict as ProvenanceVerdict, WorkloadIdentity as ProvenanceWorkloadIdentity
from .receipt import ActorRef, Algorithm as ReceiptAlgorithm, BbsReceiptSignature, BoundaryClass, ChioDeliveryContractReceiptMetadata, ChioDurableAdmissionReceiptMetadata, ChioFindingDeliveryReceiptMetadata, ChioReceiptLineageStatement, ChioReceiptMerkleInclusionProof, ChioReceiptRecord, CompensationStatus, Decision as ReceiptDecision, Decision1, Decision2, Decision3, Decision4, Digest as ReceiptDigest, DigestCheck, DispatchCommit, EvidenceClass as ReceiptEvidenceClass, GuardEvidence, HierarchicalIdentifier, IJsonU64NonZero, Identifier as ReceiptIdentifier, MediaTypeCheck, ObservationOutcome, PositiveIJsonInteger, ProjectedDispatchState, ProjectedState, ProviderAttempt, ReceiptKind, RedactionMode, RelationKind, Result as ReceiptResult, SessionAnchorReference, SettlementMode, StatusProof, StoreFence, ToolCallAction, ToolOrigin, TransformProfile, TrustLevel
from .result import ChioToolcallresultCancelled, ChioToolcallresultErr, ChioToolcallresultIncomplete, ChioToolcallresultOk, ChioToolcallresultStreamComplete, Detail as ResultDetail, Error as ResultError, Error1, Error2, Error3, Error4, Error5
from .security import Algorithm as SecurityAlgorithm, Anchor, Authorizations, CheckpointAnchor, ChioKeyLogActivationCommitBodyV1, ChioKeyLogArtifactTimeAnchorBodyV1, ChioKeyLogAuditServiceReadinessBodyV1, ChioKeyLogCheckpointBodyV1, ChioKeyLogEnterpriseReceiptBodyV1, ChioKeyLogEnterpriseReceiptBodyV11, ChioKeyLogEnterpriseReceiptBodyV12, ChioKeyLogEventBodyV1, ChioKeyLogSynchronizationResponseV1, ChioKeyLogWitnessServiceReadinessBodyV1, ChioKeyLogWitnessSignatureV1, ChioKeyringArtifactSignatureEvidenceV1, ChioSecurityEventBodyV1, ChioSignedKeyLogActivationCommitEnvelopeV1, ChioSignedKeyLogArtifactTimeAnchorV1, ChioSignedKeyLogAuditServiceReadinessProofV1, ChioSignedKeyLogCheckpointEnvelopeV1, ChioSignedKeyLogEnterpriseReceiptEnvelopeV1, ChioSignedKeyLogEventEnvelopeV1, ChioSignedKeyLogWitnessServiceReadinessProofV1, ChioSignedSecurityEventProvenanceEnvelopeV1, ConsistencyProof, Count, EventKind, EventSigner, EventSigner1, EventSigner2, EventSigner3, EventSigner4, ExternalAnchor, FlowIdentifier, Hash, Identifier as SecurityIdentifier, InformationLabel, InformationLabel1, InformationLabel2, KeyAuthorization, KeyLogIdentifier, KeyLogPin, Nonce as SecurityNonce, Operation as SecurityOperation, Operation1, Operation2, Operation3, Operation4, Operation5, Operation6, OperatorAlgorithm, Outcome, PositiveU64, PublicKey, RecoveryAuthorization, Severity, Signature as SecuritySignature, Stage, Subject, Time, TrustClass, Type, U64, WitnessView
from .trust_control import BudgetSnapshotAnchorProvenance, ChioTrustControlAuthorityLease, ChioTrustControlLeaseHeartbeat, ChioTrustControlLeaseTermination, ChioTrustControlRuntimeAttestationEvidence, Commitment, CredentialKind as TrustControlCredentialKind, Digest as TrustControlDigest, Reason, Scheme as TrustControlScheme, SignedCommitment, Tier as TrustControlTier, WorkloadIdentity as TrustControlWorkloadIdentity

CapabilityToken = ChioCapabilitytoken
Decision = ReceiptDecision
CapabilityConstraint = Constraint
CapabilityPromptGrant = PromptGrant
CapabilityResourceGrant = ResourceGrant

__all__ = [
    "ActorRef",
    "AgentBody",
    "AggregateRootPublicKey",
    "AggregateRootSignature",
    "AggregateRootSigningAlgorithm",
    "Anchor",
    "AnchorBody",
    "AnchorKind",
    "Attenuation",
    "AttenuationProof",
    "AttenuationWitness",
    "Authorizations",
    "BbsReceiptSignature",
    "Body3",
    "BoundTo",
    "BoundaryClass",
    "BudgetSnapshotAnchorProvenance",
    "CapabilityAlgorithm",
    "CapabilityBody",
    "CapabilityConstraint",
    "CapabilityDecision",
    "CapabilityKind",
    "CapabilityLeaseRef",
    "CapabilityOperation",
    "CapabilityPromptGrant",
    "CapabilityResourceGrant",
    "CapabilityToken",
    "Caveat",
    "CheckpointAnchor",
    "CheckpointId",
    "ChioAgentmessageHeartbeat",
    "ChioAgentmessageListCapabilities",
    "ChioAgentmessageToolCallRequest",
    "ChioAggregateBudgetRootBinding",
    "ChioAggregateInvocationBudget",
    "ChioAggregateInvocationBudget1",
    "ChioAggregateInvocationBudget2",
    "ChioAnchorBatchV1",
    "ChioBilateralDsseSignatureSliceEnvelope",
    "ChioBilateralDsseSignatureSliceStatement",
    "ChioCapabilityGrant",
    "ChioCapabilityNegotiationV1",
    "ChioCapabilityRevocationEntry",
    "ChioCapabilitytoken",
    "ChioCombinedAdmissionCaptureMetadata",
    "ChioCumulativeApprovalRootBinding",
    "ChioDeliveryContractReceiptMetadata",
    "ChioDurableAdmissionReceiptMetadata",
    "ChioFindingDeliveryReceiptMetadata",
    "ChioGovernedActiveResponseIntentBody",
    "ChioGovernedApprovalToken",
    "ChioGovernedTransactionIntent",
    "ChioJsonRpc20Notification",
    "ChioJsonRpc20Request",
    "ChioJsonRpc20Response",
    "ChioJsonRpc20Response1",
    "ChioJsonRpc20Response2",
    "ChioKernelmessageCapabilityList",
    "ChioKernelmessageCapabilityRevoked",
    "ChioKernelmessageHeartbeat",
    "ChioKernelmessageToolCallChunk",
    "ChioKernelmessageToolCallResponse",
    "ChioKeyLogActivationCommitBodyV1",
    "ChioKeyLogArtifactTimeAnchorBodyV1",
    "ChioKeyLogAuditServiceReadinessBodyV1",
    "ChioKeyLogCheckpointBodyV1",
    "ChioKeyLogEnterpriseReceiptBodyV1",
    "ChioKeyLogEnterpriseReceiptBodyV11",
    "ChioKeyLogEnterpriseReceiptBodyV12",
    "ChioKeyLogEventBodyV1",
    "ChioKeyLogSynchronizationResponseV1",
    "ChioKeyLogWitnessServiceReadinessBodyV1",
    "ChioKeyLogWitnessSignatureV1",
    "ChioKeyringArtifactSignatureEvidenceV1",
    "ChioOpaqueSupplementalAuthorization",
    "ChioProvenanceAttestationBundle",
    "ChioProvenanceCallChainContext",
    "ChioProvenanceStamp",
    "ChioProvenanceVerdictLink",
    "ChioProvenanceVerdictLink1",
    "ChioProvenanceVerdictLink2",
    "ChioProvenanceVerdictLink3",
    "ChioProvenanceVerdictLink4",
    "ChioReceiptLineageStatement",
    "ChioReceiptMerkleInclusionProof",
    "ChioReceiptRecord",
    "ChioScope",
    "ChioSecurityEventBodyV1",
    "ChioSignedExecutionNonce",
    "ChioSignedKeyLogActivationCommitEnvelopeV1",
    "ChioSignedKeyLogArtifactTimeAnchorV1",
    "ChioSignedKeyLogAuditServiceReadinessProofV1",
    "ChioSignedKeyLogCheckpointEnvelopeV1",
    "ChioSignedKeyLogEnterpriseReceiptEnvelopeV1",
    "ChioSignedKeyLogEventEnvelopeV1",
    "ChioSignedKeyLogWitnessServiceReadinessProofV1",
    "ChioSignedSecurityEventProvenanceEnvelopeV1",
    "ChioThresholdApprovalProposal",
    "ChioToolcallerrorCapabilityDenied",
    "ChioToolcallerrorCapabilityExpired",
    "ChioToolcallerrorCapabilityRevoked",
    "ChioToolcallerrorInternalError",
    "ChioToolcallerrorPolicyDenied",
    "ChioToolcallerrorToolServerError",
    "ChioToolcallresultCancelled",
    "ChioToolcallresultErr",
    "ChioToolcallresultIncomplete",
    "ChioToolcallresultOk",
    "ChioToolcallresultStreamComplete",
    "ChioTrustControlAuthorityLease",
    "ChioTrustControlLeaseHeartbeat",
    "ChioTrustControlLeaseTermination",
    "ChioTrustControlRuntimeAttestationEvidence",
    "ChioVerifiedApprovalSetBody",
    "CoSign",
    "Commitment",
    "CompensationStatus",
    "ConsistencyProof",
    "Constraint",
    "Count",
    "CrossOrgVisibility",
    "CumulativeApprovalDelegableConstraint",
    "CumulativeApprovalDirectConstraint",
    "CumulativeRootMonetaryAmount",
    "CumulativeRootPublicKey",
    "CumulativeRootSignature",
    "CumulativeRootSigningAlgorithm",
    "Decision",
    "Decision1",
    "Decision2",
    "Decision3",
    "Decision4",
    "DelegationLink",
    "DigestCheck",
    "DispatchCommit",
    "Error1",
    "Error10",
    "Error11",
    "Error12",
    "Error13",
    "Error2",
    "Error3",
    "Error4",
    "Error5",
    "Error9",
    "ErrorDetail",
    "EventKind",
    "EventSigner",
    "EventSigner1",
    "EventSigner2",
    "EventSigner3",
    "EventSigner4",
    "ExternalAnchor",
    "FederationDigest",
    "FederationSignature",
    "FederationVerdict",
    "FlowIdentifier",
    "GenericConstraint",
    "GovernanceReceiptRef",
    "GovernedApprovalPublicKey",
    "GovernedApprovalSignature",
    "GrantKind",
    "GrantSubsetRelation",
    "GuardEvidence",
    "Hash",
    "HashRecord",
    "HierarchicalIdentifier",
    "IJsonU64NonZero",
    "Inclusion",
    "InformationLabel",
    "InformationLabel1",
    "InformationLabel2",
    "JointDisposition",
    "JsonrpcError",
    "KernelDetail",
    "KernelError",
    "KernelIdentity",
    "KernelNonce",
    "KernelResult",
    "KeyAuthorization",
    "KeyLogIdentifier",
    "KeyLogPin",
    "LegacyApprovalConstraint",
    "MaxAmount",
    "MediaTypeCheck",
    "MonetaryAmount",
    "ObservationOutcome",
    "Operation1",
    "Operation2",
    "Operation3",
    "Operation4",
    "Operation5",
    "Operation6",
    "OperatorAlgorithm",
    "OrderedEffect",
    "Outcome",
    "PolicyEvaluationSummary",
    "PolicyVerdict",
    "PositiveIJsonInteger",
    "PositiveU64",
    "Predicate",
    "ProjectedDispatchState",
    "ProjectedState",
    "PromptGrant",
    "ProvenanceCredentialKind",
    "ProvenanceEvidenceClass",
    "ProvenanceScheme",
    "ProvenanceTier",
    "ProvenanceVerdict",
    "ProvenanceWorkloadIdentity",
    "ProviderAttempt",
    "PublicKey",
    "QuotaKey",
    "Reason",
    "ReceiptAlgorithm",
    "ReceiptDecision",
    "ReceiptDigest",
    "ReceiptEvidenceClass",
    "ReceiptIdentifier",
    "ReceiptKind",
    "ReceiptResult",
    "RecoveryAuthorization",
    "RedactionMode",
    "RelationKind",
    "ResourceGrant",
    "Result2",
    "Result3",
    "Result4",
    "Result5",
    "ResultDetail",
    "ResultError",
    "SCHEMA_SHA256",
    "ScopeAttenuation",
    "SecurityAlgorithm",
    "SecurityIdentifier",
    "SecurityNonce",
    "SecurityOperation",
    "SecuritySignature",
    "SessionAnchorReference",
    "SettlementMode",
    "Severity",
    "SignedCommitment",
    "Stage",
    "Statement",
    "StatusProof",
    "StoreFence",
    "Subject",
    "SubjectItem",
    "Subset",
    "ThresholdProposalPublicKey",
    "ThresholdProposalSignature",
    "Time",
    "TokenDigest",
    "ToolCallAction",
    "ToolGrant",
    "ToolOrigin",
    "TransformProfile",
    "TrustClass",
    "TrustControlCredentialKind",
    "TrustControlDigest",
    "TrustControlScheme",
    "TrustControlTier",
    "TrustControlWorkloadIdentity",
    "TrustLevel",
    "Type",
    "U64",
    "Value",
    "Value1",
    "Value2",
    "Witness",
    "WitnessReceipt",
    "WitnessState",
    "WitnessState1",
    "WitnessState2",
    "WitnessState3",
    "WitnessView",
]
