// Generated by build-wasm.sh before TypeScript compilation.
// @ts-ignore wasm-pack emits no declaration for this helper module.
import * as wasmGlue from './bundler/chio_kernel_browser_bg.js';
import wasmModule from './bundler/chio_kernel_browser_bg.wasm';

type WorkersWasmImports = {
  __wbg_set_wasm: (exports: WebAssembly.Exports) => void;
  __wbindgen_init_externref_table?: () => void;
  evaluate: (requestJson: string) => unknown;
  mint_signing_seed_hex: () => string;
  sign_receipt: (bodyJson: string, signingSeedHex: string) => unknown;
  verify_capability: (tokenJson: string, authorityPubHex: string) => unknown;
  verify_receipt: (envelope: Uint8Array, trustedIssuers?: unknown) => unknown;
};

let wasmReady: Promise<WorkersWasmImports> | undefined;

export async function loadWorkersWasm(): Promise<WorkersWasmImports> {
  if (wasmReady === undefined) {
    wasmReady = (async () => {
      const imports = wasmGlue as unknown as WorkersWasmImports;
      const instance = await WebAssembly.instantiate(wasmModule as WebAssembly.Module, {
        './chio_kernel_browser_bg.js': imports,
      });
      imports.__wbg_set_wasm(instance.exports);
      imports.__wbindgen_init_externref_table?.();
      const start = instance.exports.__wbindgen_start;
      if (typeof start === 'function') {
        start();
      }
      return imports;
    })();
  }

  return wasmReady;
}

export async function evaluate(requestJson: string): Promise<unknown> {
  return (await loadWorkersWasm()).evaluate(requestJson);
}

export async function mint_signing_seed_hex(): Promise<string> {
  return (await loadWorkersWasm()).mint_signing_seed_hex();
}

export async function sign_receipt(bodyJson: string, signingSeedHex: string): Promise<unknown> {
  return (await loadWorkersWasm()).sign_receipt(bodyJson, signingSeedHex);
}

export async function verify_capability(tokenJson: string, authorityPubHex: string): Promise<unknown> {
  return (await loadWorkersWasm()).verify_capability(tokenJson, authorityPubHex);
}

export async function verify_receipt(
  envelope: Uint8Array,
  trustedIssuers?: string | string[],
): Promise<unknown> {
  return (await loadWorkersWasm()).verify_receipt(envelope, trustedIssuers);
}

export async function verifyReceiptHex(
  envelopeHex: string,
  trustedIssuers?: string | string[],
): Promise<unknown> {
  const normalized = envelopeHex.startsWith('0x') ? envelopeHex.slice(2) : envelopeHex;
  if (normalized.length % 2 !== 0) {
    throw new Error('receipt hex must have an even number of characters');
  }
  if (!/^[0-9a-fA-F]*$/.test(normalized)) {
    throw new Error('receipt hex must contain only hexadecimal characters');
  }

  const pairs = normalized.match(/.{2}/g) ?? [];
  const envelope = Uint8Array.from(pairs.map(byte => Number.parseInt(byte, 16)));
  return verify_receipt(envelope, trustedIssuers);
}

const smokeHandler: ExportedHandler = {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname !== '/__chio_workers_smoke') {
      return new Response('not found', { status: 404 });
    }

    const bindings = await loadWorkersWasm();
    return Response.json({
      package: '@chio-protocol/workers',
      runtime: 'workers',
      wasmTarget: 'bundler',
      verifyReceipt: typeof bindings.verify_receipt === 'function',
    });
  },
};

export default smokeHandler;
