// Package chioguardgo provides the Go SDK for writing Chio guard components.
//
// Guards are WebAssembly Component Model modules that evaluate tool-call
// requests and return allow/deny verdicts. This SDK provides ergonomic Go
// types that mirror the WIT contract defined in wit/chio-guard/world.wit.
//
// # Quick Start
//
// 1. Initialize a new guard project:
//
//	mkdir my-guard && cd my-guard
//	go mod init example.com/my-guard
//
// 2. Write your evaluate function in main.go (see examples/tool-gate/).
//
// 3. Generate bindings and compile:
//
//	./scripts/generate-types.sh
//	./scripts/build-guard.sh
//
// The compiled .wasm file in dist/ can be loaded by the Chio kernel.
//
// # Types
//
// The actual types used at compile time are generated by wit-bindgen-go
// from the WIT contract. The types documented below describe the shape
// for developers who want to understand the contract without reading
// generated code.
//
// # WIT Contract
//
// The guard world exports a single function:
//
//	export evaluate: func(request: guard-request) -> verdict
//
// See wit/chio-guard/world.wit for the canonical definition.
package chioguardgo

// GuardRequest represents the read-only request context provided to a
// guard by the Chio kernel host. This documents the shape of the
// wit-bindgen-go generated type.
//
// All 10 fields from the WIT guard-request record:
//
//	record guard-request {
//	    tool-name: string,
//	    server-id: string,
//	    agent-id: string,
//	    arguments: string,
//	    scopes: list<string>,
//	    action-type: option<string>,
//	    extracted-path: option<string>,
//	    extracted-target: option<string>,
//	    filesystem-roots: list<string>,
//	    matched-grant-index: option<u32>,
//	}
type GuardRequest struct {
	// ToolName is the name of the tool being invoked.
	ToolName string

	// ServerID identifies the server hosting the tool.
	ServerID string

	// AgentID identifies the agent making the request.
	AgentID string

	// Arguments contains the tool arguments as a JSON-encoded string.
	Arguments string

	// Scopes lists the capability scopes granted (serialized scope names).
	Scopes []string

	// ActionType is the host-extracted action type (e.g. "file_access",
	// "network_egress"). Nil when not applicable.
	ActionType *string

	// ExtractedPath is the normalized file path for filesystem actions.
	// Nil when not applicable.
	ExtractedPath *string

	// ExtractedTarget is the target domain string for network egress
	// actions. Nil when not applicable.
	ExtractedTarget *string

	// FilesystemRoots lists the session-scoped filesystem roots from the
	// kernel context.
	FilesystemRoots []string

	// MatchedGrantIndex is the index of the matched grant in the
	// capability scope. Nil when not applicable.
	MatchedGrantIndex *uint32
}

// VerdictTag discriminates between allow and deny verdicts.
type VerdictTag int

const (
	// VerdictAllow indicates the guard allows the request to proceed.
	VerdictAllow VerdictTag = iota

	// VerdictDeny indicates the guard denies the request.
	VerdictDeny
)

// Verdict represents the result of a guard evaluation.
//
// WIT definition:
//
//	variant verdict {
//	    allow,
//	    deny(string),
//	}
//
// Use Allow() and Deny(reason) to construct verdicts.
type Verdict struct {
	Tag    VerdictTag
	Reason string // Only meaningful when Tag == VerdictDeny
}

// Allow returns a Verdict that permits the request to proceed.
func Allow() Verdict {
	return Verdict{Tag: VerdictAllow}
}

// Deny returns a Verdict that blocks the request with the given reason.
func Deny(reason string) Verdict {
	return Verdict{Tag: VerdictDeny, Reason: reason}
}
