use std::fs;
use std::path::Path;

use crate::support::{display_path, workspace_root, TempDir};
use crate::XtaskError;

/// Relative path (from workspace root) of the chio-go-http regen script.
const CHIO_GO_REGEN_SCRIPT: &str = "sdks/go/chio-go-http/scripts/regen-types.sh";
/// Relative path (from workspace root) of the generated Go file. Used by the
/// `--check` mode to scope `git diff --exit-code` precisely.
const CHIO_GO_OUTPUT_FILE: &str = "sdks/go/chio-go-http/types.go";

/// Wire `cargo xtask codegen --lang go [--check]`. The Go target is a thin
/// shim around `sdks/go/chio-go-http/scripts/regen-types.sh` because Go
/// follows the checked-in regen pattern (see `xtask/codegen-tools.lock.toml
/// [go]`): the regenerated bytes are committed and a CI lane diffs them,
/// rather than rebuilding live every run like the Rust pipeline.
///
/// The shim does two things:
/// 1. Resolve the workspace root (so `bash regen-types.sh` runs from a
///    well-defined cwd regardless of where the user invoked cargo).
/// 2. With `--check`, render into a temporary output path and compare those
///    bytes with the workspace file without mutating its contents or metadata.
///
/// The script handles its own toolchain checks (go, python3, git on PATH);
/// the xtask does not duplicate them.
pub(super) fn codegen_go(check_only: bool) -> Result<(), XtaskError> {
    let workspace_root = workspace_root()?;
    let script_path = workspace_root.join(CHIO_GO_REGEN_SCRIPT);
    let output_path = workspace_root.join(CHIO_GO_OUTPUT_FILE);

    if !script_path.exists() {
        return Err(XtaskError::Usage(format!(
            "codegen go: regen script not found at {}",
            display_path(&script_path)
        )));
    }

    if check_only {
        let staging = TempDir::new("chio-codegen-go-check").map_err(|err| {
            XtaskError::Io("<temp staging dir for codegen go --check>".to_string(), err)
        })?;
        let staged_output = staging.path().join("types.go");
        run_go_regen_script(&script_path, &workspace_root, &staged_output)?;
        let regen_bytes = fs::read(&staged_output)
            .map_err(|err| XtaskError::Io(display_path(&staged_output), err))?;
        let original = if output_path.exists() {
            fs::read(&output_path).map_err(|err| XtaskError::Io(display_path(&output_path), err))?
        } else {
            return Err(XtaskError::Drift(format!(
                "{} is missing on disk; rerun `cargo xtask codegen --lang go` and commit the result",
                display_path(&output_path)
            )));
        };

        if original == regen_bytes {
            println!(
                "codegen go: {} in sync with committed bytes",
                display_path(&output_path)
            );
            Ok(())
        } else {
            Err(XtaskError::Drift(format!(
                "{} drifted from committed bytes (committed {} bytes, regenerated {} bytes); rerun `cargo xtask codegen --lang go` and commit the result",
                display_path(&output_path),
                original.len(),
                regen_bytes.len()
            )))
        }
    } else {
        run_go_regen_script(&script_path, &workspace_root, &output_path)?;
        let bytes = fs::metadata(&output_path)
            .map(|m| m.len())
            .unwrap_or_default();
        println!(
            "codegen go: wrote {} ({} bytes) via {}",
            display_path(&output_path),
            bytes,
            display_path(&script_path)
        );
        Ok(())
    }
}

/// Invoke the Go regen script with the workspace root as CWD. Surfaces a
/// dedicated `Process` error for shell-level failures so they are not
/// misreported as a Rust-side `Codegen` failure.
fn run_go_regen_script(
    script_path: &Path,
    workspace_root: &Path,
    output_path: &Path,
) -> Result<(), XtaskError> {
    let status = std::process::Command::new("bash")
        .arg(script_path)
        .arg(output_path)
        .current_dir(workspace_root)
        .status()
        .map_err(|err| XtaskError::Io(display_path(script_path), err))?;
    if !status.success() {
        return Err(XtaskError::Process(format!(
            "{} exited with code {}",
            display_path(script_path),
            status.code().unwrap_or(-1)
        )));
    }
    Ok(())
}
