use std::fs;
use std::path::Path;

use crate::support::{display_path, workspace_root};
use crate::XtaskError;

/// Relative path (from workspace root) of the chio-go-http regen script.
const CHIO_GO_REGEN_SCRIPT: &str = "sdks/go/chio-go-http/scripts/regen-types.sh";
/// Relative path (from workspace root) of the generated Go file. Used by the
/// `--check` mode to scope `git diff --exit-code` precisely.
const CHIO_GO_OUTPUT_FILE: &str = "sdks/go/chio-go-http/types.go";

/// Wire `cargo xtask codegen --lang go [--check]`. The Go target is a thin
/// shim around `sdks/go/chio-go-http/scripts/regen-types.sh` because Go
/// follows the checked-in regen pattern (see `xtask/codegen-tools.lock.toml
/// [go]`): the regenerated bytes are committed and a CI lane diffs them,
/// rather than rebuilding live every run like the Rust pipeline.
///
/// The shim does two things:
/// 1. Resolve the workspace root (so `bash regen-types.sh` runs from a
///    well-defined cwd regardless of where the user invoked cargo).
/// 2. With `--check`, additionally invoke `git diff --exit-code` on the
///    generated file so a stale committed copy fails the build instead of
///    silently re-rendering.
///
/// The script handles its own toolchain checks (go, python3, git on PATH);
/// the xtask does not duplicate them.
pub(super) fn codegen_go(check_only: bool) -> Result<(), XtaskError> {
    let workspace_root = workspace_root()?;
    let script_path = workspace_root.join(CHIO_GO_REGEN_SCRIPT);
    let output_path = workspace_root.join(CHIO_GO_OUTPUT_FILE);

    if !script_path.exists() {
        return Err(XtaskError::Usage(format!(
            "codegen go: regen script not found at {}",
            display_path(&script_path)
        )));
    }

    if check_only {
        // `--check` MUST NOT mutate the on-disk types.go. Snapshot the
        // committed bytes, run the regen, compare in-memory, and restore
        // the original bytes regardless of outcome. Any drift yields a
        // hard error rather than a silent rewrite.
        let original = if output_path.exists() {
            Some(
                fs::read(&output_path)
                    .map_err(|err| XtaskError::Io(display_path(&output_path), err))?,
            )
        } else {
            None
        };

        let run_result = run_go_regen_script(&script_path, &workspace_root);
        let regen_bytes = if run_result.is_ok() && output_path.exists() {
            fs::read(&output_path).map_err(|err| XtaskError::Io(display_path(&output_path), err))?
        } else {
            Vec::new()
        };

        // Restore the original committed bytes (or remove the file if it
        // did not exist before the regen) so callers see no on-disk side
        // effects from `--check`.
        match &original {
            Some(bytes) => {
                fs::write(&output_path, bytes)
                    .map_err(|err| XtaskError::Io(display_path(&output_path), err))?;
            }
            None => {
                if output_path.exists() {
                    fs::remove_file(&output_path)
                        .map_err(|err| XtaskError::Io(display_path(&output_path), err))?;
                }
            }
        }

        run_result?;

        match &original {
            Some(bytes) if bytes == &regen_bytes => {
                println!(
                    "codegen go: {} in sync with committed bytes",
                    display_path(&output_path)
                );
                Ok(())
            }
            Some(bytes) => Err(XtaskError::Drift(format!(
                "{} drifted from committed bytes (committed {} bytes, regenerated {} bytes); rerun `cargo xtask codegen --lang go` and commit the result",
                display_path(&output_path),
                bytes.len(),
                regen_bytes.len()
            ))),
            None => Err(XtaskError::Drift(format!(
                "{} is missing on disk; rerun `cargo xtask codegen --lang go` and commit the result",
                display_path(&output_path)
            ))),
        }
    } else {
        run_go_regen_script(&script_path, &workspace_root)?;
        let bytes = fs::metadata(&output_path)
            .map(|m| m.len())
            .unwrap_or_default();
        println!(
            "codegen go: wrote {} ({} bytes) via {}",
            display_path(&output_path),
            bytes,
            display_path(&script_path)
        );
        Ok(())
    }
}

/// Invoke the Go regen script with the workspace root as CWD. Surfaces a
/// dedicated `Process` error for shell-level failures so they are not
/// misreported as a Rust-side `Codegen` failure.
fn run_go_regen_script(script_path: &Path, workspace_root: &Path) -> Result<(), XtaskError> {
    let status = std::process::Command::new("bash")
        .arg(script_path)
        .current_dir(workspace_root)
        .status()
        .map_err(|err| XtaskError::Io(display_path(script_path), err))?;
    if !status.success() {
        return Err(XtaskError::Process(format!(
            "{} exited with code {}",
            display_path(script_path),
            status.code().unwrap_or(-1)
        )));
    }
    Ok(())
}
