-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [formal_aeneas]: function definitions
import Aeneas
import FormalAeneas.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace Chio.AeneasProduction

/-- [formal_aeneas::{core::clone::Clone for formal_aeneas::ReservationLedger}::clone]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:9-14:14
    Visibility: public -/
def ReservationLedger.Insts.CoreCloneClone.clone
  (self : ReservationLedger) : Result ReservationLedger := do
  ok self

/-- Trait implementation: [formal_aeneas::{core::clone::Clone for formal_aeneas::ReservationLedger}]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:9-14:14 -/
@[reducible]
def ReservationLedger.Insts.CoreCloneClone : core.clone.Clone ReservationLedger
  := {
  clone := ReservationLedger.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [formal_aeneas::{core::marker::Copy for formal_aeneas::ReservationLedger}]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:16-14:20 -/
@[reducible]
def ReservationLedger.Insts.CoreMarkerCopy : core.marker.Copy ReservationLedger
  := {
  cloneInst := ReservationLedger.Insts.CoreCloneClone
}

/-- [formal_aeneas::{core::default::Default for formal_aeneas::ReservationLedger}::default]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:22-14:29
    Visibility: public -/
def ReservationLedger.Insts.CoreDefaultDefault.default
  : Result ReservationLedger := do
  ok
    {
      reserved := (core.default.DefaultU64.default),
      committed := (core.default.DefaultU64.default),
      released := (core.default.DefaultU64.default),
      retained := (core.default.DefaultU64.default)
    }

/-- Trait implementation: [formal_aeneas::{core::default::Default for formal_aeneas::ReservationLedger}]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:22-14:29 -/
@[reducible]
def ReservationLedger.Insts.CoreDefaultDefault : core.default.Default
  ReservationLedger := {
  default := ReservationLedger.Insts.CoreDefaultDefault.default
}

/-- Trait implementation: [formal_aeneas::{core::marker::StructuralPartialEq for formal_aeneas::ReservationLedger}]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:31-14:40 -/
@[reducible]
def ReservationLedger.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ReservationLedger := {
}

/-- [formal_aeneas::{core::cmp::PartialEq<formal_aeneas::ReservationLedger> for formal_aeneas::ReservationLedger}::eq]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:31-14:40
    Visibility: public -/
def ReservationLedger.Insts.CoreCmpPartialEqReservationLedger.eq
  (self : ReservationLedger) (other : ReservationLedger) : Result Bool := do
  if self.reserved = other.reserved
  then
    if self.committed = other.committed
    then
      if self.released = other.released
      then ok (self.retained = other.retained)
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [formal_aeneas::{core::cmp::PartialEq<formal_aeneas::ReservationLedger> for formal_aeneas::ReservationLedger}]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:31-14:40 -/
@[reducible]
def ReservationLedger.Insts.CoreCmpPartialEqReservationLedger :
  core.cmp.PartialEq ReservationLedger ReservationLedger := {
  eq := ReservationLedger.Insts.CoreCmpPartialEqReservationLedger.eq
}

/-- [formal_aeneas::{core::cmp::Eq for formal_aeneas::ReservationLedger}::assert_receiver_is_total_eq]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:42-14:44
    Visibility: public -/
def ReservationLedger.Insts.CoreCmpEq.assert_receiver_is_total_eq
  (self : ReservationLedger) : Result Unit := do
  ok ()

/-- Trait implementation: [formal_aeneas::{core::cmp::Eq for formal_aeneas::ReservationLedger}]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 14:42-14:44 -/
@[reducible]
def ReservationLedger.Insts.CoreCmpEq : core.cmp.Eq ReservationLedger := {
  partialEqInst := ReservationLedger.Insts.CoreCmpPartialEqReservationLedger
  assert_receiver_is_total_eq :=
    ReservationLedger.Insts.CoreCmpEq.assert_receiver_is_total_eq
}

/-- [formal_aeneas::ledger_is_terminal]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 34:0-36:1 -/
def ledger_is_terminal (state : ReservationLedger) : Result Bool := do
  if state.reserved = 0#u64
  then
    if state.committed != 0#u64
    then ok true
    else
      if state.released != 0#u64
      then ok true
      else ok (state.retained != 0#u64)
  else ok false

/-- [formal_aeneas::ledger_apply]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 85:0-147:1
    Visibility: public -/
def ledger_apply
  (state : ReservationLedger) (op : Std.U8) (amount : Std.U64) :
  Result (ReservationLedger × Bool)
  := do
  let o ← lift (U64.checked_add state.reserved state.committed)
  match o with
  | none => ok (state, false)
  | some total =>
    let o1 ← lift (U64.checked_add total state.released)
    match o1 with
    | none => ok (state, false)
    | some total1 =>
      let o2 ← lift (U64.checked_add total1 state.retained)
      match o2 with
      | none => ok (state, false)
      | some total2 =>
        if op > 3#u8
        then ok (state, false)
        else
          if op = 0#u8
          then
            let b ← ledger_is_terminal state
            if b
            then ok (state, false)
            else
              if op = 0#u8
              then
                let o3 ← lift (U64.checked_add total2 amount)
                let b1 := core.option.Option.is_none o3
                if b1
                then ok (state, false)
                else
                  let o4 ← lift (U64.checked_add state.reserved amount)
                  match o4 with
                  | none => ok (state, false)
                  | some reserved => ok ({ state with reserved }, true)
              else
                if amount > state.reserved
                then ok (state, false)
                else
                  let outstanding ← state.reserved - amount
                  let updated ←
                    match op with
                    | 1#uscalar =>
                      do
                      let o3 ← lift (U64.checked_add state.committed amount)
                      match o3 with
                      | none => ok none
                      | some committed =>
                        ok (some
                          { state with reserved := outstanding, committed })
                    | 2#uscalar =>
                      do
                      let o3 ← lift (U64.checked_add state.released amount)
                      match o3 with
                      | none => ok none
                      | some released =>
                        ok (some
                          { state with reserved := outstanding, released })
                    | 3#uscalar =>
                      do
                      let o3 ← lift (U64.checked_add state.retained amount)
                      match o3 with
                      | none => ok none
                      | some retained =>
                        ok (some
                          { state with reserved := outstanding, retained })
                    | _ => ok none
                  match updated with
                  | none => ok (state, false)
                  | some next => ok (next, true)
          else
            if op = 0#u8
            then
              let o3 ← lift (U64.checked_add total2 amount)
              let b := core.option.Option.is_none o3
              if b
              then ok (state, false)
              else
                let o4 ← lift (U64.checked_add state.reserved amount)
                match o4 with
                | none => ok (state, false)
                | some reserved => ok ({ state with reserved }, true)
            else
              if amount > state.reserved
              then ok (state, false)
              else
                let outstanding ← state.reserved - amount
                let updated ←
                  match op with
                  | 1#uscalar =>
                    do
                    let o3 ← lift (U64.checked_add state.committed amount)
                    match o3 with
                    | none => ok none
                    | some committed =>
                      ok (some
                        { state with reserved := outstanding, committed })
                  | 2#uscalar =>
                    do
                    let o3 ← lift (U64.checked_add state.released amount)
                    match o3 with
                    | none => ok none
                    | some released =>
                      ok (some
                        { state with reserved := outstanding, released })
                  | 3#uscalar =>
                    do
                    let o3 ← lift (U64.checked_add state.retained amount)
                    match o3 with
                    | none => ok none
                    | some retained =>
                      ok (some
                        { state with reserved := outstanding, retained })
                  | _ => ok none
                match updated with
                | none => ok (state, false)
                | some next => ok (next, true)

/-- [formal_aeneas::inclusion_step]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 157:0-175:1
    Visibility: public -/
def inclusion_step
  (index : Std.U64) (size : Std.U64) : Result InclusionStep := do
  let i ← index % 2#u64
  let o ← lift (U64.checked_add index 1#u64)
  let right_sibling_exists ←
    match o with
    | none => ok false
    | some sibling => if sibling < size
                      then ok true
                      else ok false
  let (sibling_on_left, b) ←
    if i != 0#u64
    then ok (true, true)
    else ok (false, right_sibling_exists)
  let i1 ← index / 2#u64
  let i2 ← size / 2#u64
  let i3 ← size % 2#u64
  let i4 ← i2 + i3
  ok
    { consume_sibling := b, sibling_on_left, next_index := i1, next_size := i4
    }

/-- [formal_aeneas::classify_time_window_code]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 189:0-197:1
    Visibility: public -/
def classify_time_window_code
  (now : Std.U64) (issued_at : Std.U64) (expires_at : Std.U64) :
  Result Std.U8
  := do
  if now < issued_at
  then ok 1#u8
  else if now >= expires_at
       then ok 2#u8
       else ok 0#u8

/-- [formal_aeneas::time_window_valid]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 203:0-205:1
    Visibility: public -/
def time_window_valid
  (now : Std.U64) (issued_at : Std.U64) (expires_at : Std.U64) :
  Result Bool
  := do
  let i ← classify_time_window_code now issued_at expires_at
  ok (i = 0#u8)

/-- [formal_aeneas::exact_or_wildcard_covers_by_flags]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 207:0-212:1
    Visibility: public -/
def exact_or_wildcard_covers_by_flags
  (parent_is_wildcard : Bool) (parent_equals_child : Bool) : Result Bool := do
  if parent_is_wildcard
  then ok true
  else ok parent_equals_child

/-- [formal_aeneas::prefix_wildcard_or_exact_covers_by_flags]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 214:0-221:1
    Visibility: public -/
def prefix_wildcard_or_exact_covers_by_flags
  (parent_is_wildcard : Bool) (parent_has_prefix_wildcard : Bool)
  (prefix_matches : Bool) (exact_matches : Bool) :
  Result Bool
  := do
  if parent_is_wildcard
  then ok true
  else
    if parent_has_prefix_wildcard
    then if prefix_matches
         then ok true
         else ok exact_matches
    else ok exact_matches

/-- [formal_aeneas::optional_u32_cap_is_subset]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 227:0-234:1
    Visibility: public -/
def optional_u32_cap_is_subset
  (child_has_cap : Bool) (child_value : Std.U32) (parent_has_cap : Bool)
  (parent_value : Std.U32) :
  Result Bool
  := do
  if parent_has_cap
  then if child_has_cap
       then ok (child_value <= parent_value)
       else ok false
  else ok true

/-- [formal_aeneas::required_true_is_preserved]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 240:0-242:1
    Visibility: public -/
def required_true_is_preserved
  (parent_requires_true : Bool) (child_requires_true : Bool) :
  Result Bool
  := do
  if parent_requires_true
  then ok child_requires_true
  else ok true

/-- [formal_aeneas::monetary_cap_is_subset_by_parts]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 244:0-252:1
    Visibility: public -/
def monetary_cap_is_subset_by_parts
  (child_has_cap : Bool) (child_units : Std.U64) (parent_has_cap : Bool)
  (parent_units : Std.U64) (currency_matches : Bool) :
  Result Bool
  := do
  if parent_has_cap
  then
    if child_has_cap
    then
      if currency_matches
      then ok (child_units <= parent_units)
      else ok false
    else ok false
  else ok true

/-- [formal_aeneas::budget_precheck]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 260:0-267:1
    Visibility: public -/
def budget_precheck
  (remaining_invocations : Std.U64) (remaining_units : Std.U64)
  (invocation_cost : Std.U64) (unit_cost : Std.U64) :
  Result Bool
  := do
  if invocation_cost <= remaining_invocations
  then ok (unit_cost <= remaining_units)
  else ok false

/-- [formal_aeneas::budget_commit]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 295:0-319:1
    Visibility: public -/
def budget_commit
  (remaining_invocations : Std.U64) (remaining_units : Std.U64)
  (invocation_cost : Std.U64) (unit_cost : Std.U64) :
  Result BudgetCommitResult
  := do
  let b ←
    budget_precheck remaining_invocations remaining_units invocation_cost
      unit_cost
  if b
  then
    let i ← remaining_invocations - invocation_cost
    let i1 ← remaining_units - unit_cost
    ok { accepted := true, remaining_invocations := i, remaining_units := i1 }
  else ok { accepted := false, remaining_invocations, remaining_units }

/-- [formal_aeneas::dpop_freshness_valid]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 321:0-323:1
    Visibility: public -/
def dpop_freshness_valid
  (now : Std.U64) (issued_at : Std.U64) (ttl_secs : Std.U64)
  (max_skew_secs : Std.U64) :
  Result Bool
  := do
  let i ← lift (core.num.U64.saturating_add now max_skew_secs)
  if issued_at <= i
  then
    let i1 ← lift (core.num.U64.saturating_add issued_at ttl_secs)
    ok (i1 >= now)
  else ok false

/-- [formal_aeneas::dpop_admits]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 329:0-336:1
    Visibility: public -/
def dpop_admits
  (dpop_required : Bool) (proof_present : Bool) (proof_valid : Bool)
  (nonce_fresh : Bool) :
  Result Bool
  := do
  if dpop_required
  then
    if proof_present
    then if proof_valid
         then ok nonce_fresh
         else ok false
    else ok false
  else ok true

/-- [formal_aeneas::nonce_admits]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 338:0-340:1
    Visibility: public -/
def nonce_admits (already_live : Bool) : Result Bool := do
  ok (¬ already_live)

/-- [formal_aeneas::guard_step_allows]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 342:0-344:1
    Visibility: public -/
def guard_step_allows
  (core_authorized : Bool) (guard_allows : Bool) : Result Bool := do
  if core_authorized
  then ok guard_allows
  else ok false

/-- [formal_aeneas::revocation_snapshot_denies]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 350:0-352:1
    Visibility: public -/
def revocation_snapshot_denies
  (token_revoked : Bool) (ancestor_revoked : Bool) : Result Bool := do
  if token_revoked
  then ok true
  else ok ancestor_revoked

/-- [formal_aeneas::receipt_fields_coupled]:
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 364:0-376:1
    Visibility: public -/
def receipt_fields_coupled
  (capability_matches : Bool) (request_matches : Bool) (verdict_matches : Bool)
  (policy_hash_matches : Bool) (evidence_class_matches : Bool) :
  Result Bool
  := do
  if capability_matches
  then
    if request_matches
    then
      if verdict_matches
      then if policy_hash_matches
           then ok evidence_class_matches
           else ok false
      else ok false
    else ok false
  else ok false

end Chio.AeneasProduction
