-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [formal_aeneas]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace Chio.AeneasProduction

/-- [formal_aeneas::BudgetCommitResult]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 7:0-11:1
    Visibility: public -/
structure BudgetCommitResult where
  accepted : Bool
  remaining_invocations : Std.U64
  remaining_units : Std.U64

/-- [formal_aeneas::ReservationLedger]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 16:0-25:1
    Visibility: public -/
structure ReservationLedger where
  reserved : Std.U64
  committed : Std.U64
  released : Std.U64
  retained : Std.U64

/-- [formal_aeneas::InclusionStep]
    Source: 'crates/kernel/chio-kernel-core/src/formal_aeneas.rs', lines 149:0-154:1
    Visibility: public -/
structure InclusionStep where
  consume_sibling : Bool
  sibling_on_left : Bool
  next_index : Std.U64
  next_size : Std.U64

end Chio.AeneasProduction
