pub const CHIO_RUNTIME_ADMISSION_PROFILE_SCHEMA: &str = "chio.runtime.admission-profile.v1";
pub const CHIO_RUNTIME_ADMISSION_BUNDLE_SCHEMA: &str = "chio.runtime.admission-bundle.v1";
pub const CHIO_RUNTIME_VERIFIER_TRUST_BUNDLE_SCHEMA: &str = "chio.runtime.verifier-trust-bundle.v1";
pub const CHIO_RUNTIME_ADMISSION_REPORT_SCHEMA: &str = "chio.runtime.admission-report.v1";
pub const CHIO_RUNTIME_WORKFLOW_RUN_REPORT_SCHEMA: &str = "chio.runtime.workflow-run-report.v1";
pub const CHIO_RUNTIME_STEP_EVIDENCE_SCHEMA: &str = "chio.runtime.step-evidence.v1";
pub const CHIO_RUNTIME_EVIDENCE_MANIFEST_SCHEMA: &str = "chio.runtime.evidence-manifest.v1";
pub const CHIO_RUNTIME_PROOF_REGENERATION_INPUT_SCHEMA: &str =
    "chio.runtime.proof-regeneration-input.v1";
pub const CHIO_RUNTIME_PROOF_REGENERATION_REPORT_SCHEMA: &str =
    "chio.runtime.proof-regeneration-report.v1";
pub const CHIO_RUNTIME_PROOF_PARITY_REPORT_SCHEMA: &str = "chio.runtime.proof-parity-report.v1";
pub const CHIO_RUNTIME_ADMISSION_STORE_SCHEMA: &str = "chio.runtime.admission-store.v1";
pub const CHIO_RUNTIME_TRUSTED_VERIFIERS_SCHEMA: &str = "chio.runtime.trusted-verifiers.v1";
pub const CHIO_RUNTIME_PHEROMONE_POLICY_SCHEMA: &str = "chio.runtime.pheromone-policy.v1";
pub const CHIO_RUNTIME_PHEROMONE_POLICY_DECISION_SCHEMA: &str =
    "chio.runtime.pheromone-policy-decision.v1";
pub const CHIO_RUNTIME_PEER_WEIGHTS_SCHEMA: &str = "chio.runtime.peer-weights.v1";
pub const CHIO_RUNTIME_TRUST_FLOOR_STATE_SCHEMA: &str = "chio.runtime.trust-floor-state.v1";
pub const CHIO_RUNTIME_ORCHESTRATION_PLAN_SCHEMA: &str = "chio.runtime.orchestration-plan.v1";
pub const CHIO_RUNTIME_ORCHESTRATION_PROFILE_SCHEMA: &str = "chio.runtime.orchestration-profile.v1";
pub const CHIO_RUNTIME_RUN_CONTRACT_SCHEMA: &str = "chio.runtime.run-contract.v1";
pub const CHIO_RUNTIME_ORCHESTRATION_RUN_REPORT_SCHEMA: &str =
    "chio.runtime.orchestration-run-report.v1";
pub const CHIO_RUNTIME_ORCHESTRATION_RESUME_PLAN_SCHEMA: &str =
    "chio.runtime.orchestration-resume-plan.v1";
pub const CHIO_RUNTIME_ORCHESTRATION_STATUS_REPORT_SCHEMA: &str =
    "chio.runtime.orchestration-status-report.v1";
pub const CHIO_RUNTIME_PROOF_DRIFT_REPORT_SCHEMA: &str = "chio.runtime.proof-drift-report.v1";
pub const CHIO_RUNTIME_ORCHESTRATION_NEGATIVE_CORPUS_SCHEMA: &str =
    "chio.runtime.orchestration-negative-fixture-corpus.v1";
pub const CHIO_RUNTIME_SUPERVISOR_PROFILE_SCHEMA: &str = "chio.runtime.supervisor-profile.v1";
pub const CHIO_RUNTIME_RUN_LEASE_SCHEMA: &str = "chio.runtime.run-lease.v1";
pub const CHIO_RUNTIME_SCHEDULER_TICK_REPORT_SCHEMA: &str = "chio.runtime.scheduler-tick-report.v1";
pub const CHIO_RUNTIME_EVIDENCE_SINK_HEALTH_REPORT_SCHEMA: &str =
    "chio.runtime.evidence-sink-health-report.v1";
pub const CHIO_RUNTIME_RECOVERY_DRILL_REPORT_SCHEMA: &str = "chio.runtime.recovery-drill-report.v1";
pub const CHIO_RUNTIME_ARTIFACT_RETENTION_PROFILE_SCHEMA: &str =
    "chio.runtime.artifact-retention-profile.v1";
pub const CHIO_RUNTIME_ARTIFACT_RETENTION_PLAN_SCHEMA: &str =
    "chio.runtime.artifact-retention-plan.v1";
pub const CHIO_RUNTIME_PROVIDER_BINDINGS_SCHEMA: &str = "chio.runtime.provider-bindings.v1";
pub const CHIO_RUNTIME_PROVIDER_HEALTH_REPORT_SCHEMA: &str =
    "chio.runtime.provider-health-report.v1";
pub const CHIO_RUNTIME_OPS_STATUS_REPORT_SCHEMA: &str = "chio.runtime.ops-status-report.v1";
pub const CHIO_RUNTIME_OPS_NEGATIVE_CORPUS_SCHEMA: &str =
    "chio.runtime.ops-negative-fixture-corpus.v1";
pub const CHIO_RUNTIME_FAILURE_CODE_REGISTRY_SCHEMA: &str = "chio.runtime.failure-code-registry.v1";

pub const CHIO_GOVERNANCE_LADDER_MANIFEST_SCHEMA: &str =
    "chio.federation.governance-ladder-manifest.v1";
pub const CHIO_FEDERATION_TREATY_SCOPE_SCHEMA: &str = "chio.federation.treaty-scope.v1";
pub const CHIO_TREATY_SCOPE_SCHEMA: &str = CHIO_FEDERATION_TREATY_SCOPE_SCHEMA;
pub const CHIO_FEDERATION_LADDER_INTERSECTION_SCHEMA: &str =
    "chio.federation.ladder-intersection.v1";
pub const CHIO_LADDER_INTERSECTION_SCHEMA: &str = CHIO_FEDERATION_LADDER_INTERSECTION_SCHEMA;
pub const CHIO_FEDERATION_CROSS_KERNEL_CONTINUATION_SCHEMA: &str =
    "chio.federation.cross-kernel-continuation.v1";
pub const CHIO_CROSS_KERNEL_CONTINUATION_SCHEMA: &str =
    CHIO_FEDERATION_CROSS_KERNEL_CONTINUATION_SCHEMA;
pub const CHIO_FEDERATION_RECEIPT_LINEAGE_STATEMENT_SCHEMA: &str =
    "chio.federation.receipt-lineage-statement.v1";
pub const CHIO_RECEIPT_LINEAGE_STATEMENT_SCHEMA: &str =
    CHIO_FEDERATION_RECEIPT_LINEAGE_STATEMENT_SCHEMA;
pub const CHIO_FEDERATION_CROSS_BOUNDARY_ADMISSION_REPORT_SCHEMA: &str =
    "chio.federation.cross-boundary-admission-report.v1";
pub const CHIO_CROSS_BOUNDARY_ADMISSION_REPORT_SCHEMA: &str =
    CHIO_FEDERATION_CROSS_BOUNDARY_ADMISSION_REPORT_SCHEMA;
pub const CHIO_FEDERATION_BILATERAL_INVOCATION_SCHEMA: &str =
    "chio.federation.bilateral-invocation.v1";
pub const CHIO_BILATERAL_INVOCATION_SCHEMA: &str = CHIO_FEDERATION_BILATERAL_INVOCATION_SCHEMA;
pub const CHIO_FEDERATION_RECEIPT_LINEAGE_BUNDLE_SCHEMA: &str =
    "chio.federation.receipt-lineage-bundle.v1";
pub const CHIO_RECEIPT_LINEAGE_BUNDLE_SCHEMA: &str = CHIO_FEDERATION_RECEIPT_LINEAGE_BUNDLE_SCHEMA;
pub const CHIO_TREATY_NEGATIVE_CORPUS_SCHEMA: &str =
    "chio.federation.treaty-negative-fixture-corpus.v1";
pub const CHIO_TREATY_RUNTIME_NEGATIVE_CORPUS_SCHEMA: &str =
    "chio.federation.treaty-runtime-negative-fixture-corpus.v1";

pub const CHIO_ATTEST_BUYER_ATTESTATION_PACKET_SCHEMA: &str =
    "chio.attest.buyer-attestation-packet.v1";
pub const CHIO_BUYER_ATTESTATION_PACKET_SCHEMA: &str = CHIO_ATTEST_BUYER_ATTESTATION_PACKET_SCHEMA;
pub const CHIO_ATTEST_BUYER_ATTESTATION_VERIFICATION_REPORT_SCHEMA: &str =
    "chio.attest.buyer-attestation-verification-report.v1";
pub const CHIO_BUYER_ATTESTATION_VERIFICATION_REPORT_SCHEMA: &str =
    CHIO_ATTEST_BUYER_ATTESTATION_VERIFICATION_REPORT_SCHEMA;
pub const CHIO_ATTEST_BUYER_ATTESTATION_REVIEW_PACKAGE_SCHEMA: &str =
    "chio.attest.buyer-attestation-review-package.v1";
pub const CHIO_BUYER_ATTESTATION_REVIEW_PACKAGE_SCHEMA: &str =
    CHIO_ATTEST_BUYER_ATTESTATION_REVIEW_PACKAGE_SCHEMA;
pub const CHIO_ATTEST_BUYER_ATTESTATION_REVIEW_REPORT_SCHEMA: &str =
    "chio.attest.buyer-attestation-review-report.v1";
pub const CHIO_BUYER_ATTESTATION_REVIEW_REPORT_SCHEMA: &str =
    CHIO_ATTEST_BUYER_ATTESTATION_REVIEW_REPORT_SCHEMA;

pub const CHIO_RUNTIME_FAILURE_CODES: &[&str] = &[
    "admission_bundle_hash_mismatch",
    "bilateral_invocation_duplicate_signer",
    "bilateral_invocation_empty_action_class",
    "bilateral_invocation_empty_capability",
    "bilateral_invocation_empty_id",
    "bilateral_invocation_empty_signer",
    "bilateral_invocation_empty_treaty",
    "bilateral_invocation_invalid_continuation_hash",
    "bilateral_invocation_invalid_intersection_hash",
    "bilateral_invocation_invalid_lineage_hash",
    "bilateral_invocation_invalid_local_receipt_hash",
    "bilateral_invocation_invalid_outcome_hash",
    "bilateral_invocation_invalid_remote_receipt_hash",
    "bilateral_invocation_invalid_request_hash",
    "bilateral_invocation_signer_count_mismatch",
    "buyer_packet_empty_buyer",
    "buyer_packet_empty_capability",
    "buyer_packet_empty_id",
    "buyer_packet_invalid_admission_hash",
    "buyer_packet_invalid_bilateral_dsse_hash",
    "buyer_packet_invalid_bilateral_hash",
    "buyer_packet_invalid_continuation_hash",
    "buyer_packet_invalid_intersection_hash",
    "buyer_packet_invalid_lineage_hash",
    "buyer_packet_invalid_package_hash",
    "buyer_packet_invalid_treaty_hash",
    "buyer_packet_invalid_verifier_hash",
    "buyer_packet_invalid_workflow_hash",
    "buyer_review_artifact_empty_bytes",
    "buyer_review_artifact_empty_relative_path",
    "buyer_review_artifact_empty_role",
    "buyer_review_artifact_invalid_hash",
    "buyer_review_package_empty_buyer",
    "buyer_review_package_empty_id",
    "buyer_review_package_empty_packet",
    "buyer_review_report_empty_package",
    "buyer_review_report_empty_packet",
    "buyer_review_report_missing_failure_code",
    "buyer_verification_empty_packet",
    "buyer_verification_invalid_state",
    "buyer_verification_missing_failure_code",
    "chio_buyer_packet_dsse_unresolved",
    "chio_buyer_packet_hash_mismatch",
    "chio_buyer_packet_lineage_not_verified",
    "chio_buyer_packet_settlement_claimed",
    "chio_buyer_packet_source_missing",
    "chio_buyer_review_artifact_hash_mismatch",
    "chio_buyer_review_artifact_path_mismatch",
    "chio_buyer_review_duplicate_artifact_path",
    "chio_buyer_review_duplicate_artifact_role",
    "chio_buyer_review_lineage_hash_mismatch",
    "chio_buyer_review_missing_artifact_role",
    "chio_buyer_review_missing_treaty_dsse_binding",
    "chio_buyer_review_non_strict_dsse",
    "chio_buyer_review_package_manifest_timestamp_mismatch",
    "chio_buyer_review_package_stale",
    "chio_buyer_review_packet_hash_mismatch",
    "chio_buyer_review_proof_package_incomplete",
    "chio_buyer_review_proof_package_mismatch",
    "chio_buyer_review_runtime_report_mismatch",
    "chio_buyer_review_runtime_timestamp_mismatch",
    "chio_buyer_review_strict_dsse_binding_mismatch",
    "chio_buyer_review_strict_dsse_signature_invalid",
    "chio_buyer_review_strict_dsse_signer_mismatch",
    "chio_buyer_review_verifier_report_rejected",
    "chio_ladder_alias_conflict",
    "chio_ladder_consistency_mismatch",
    "chio_ladder_destructive_below_floor",
    "chio_ladder_destructive_crdt_not_allowed",
    "chio_ladder_duplicate_action_class",
    "chio_ladder_invalid_consistency_model",
    "chio_ladder_invalid_cosign_mode",
    "chio_ladder_invalid_mode",
    "chio_ladder_manifest_hash_mismatch",
    "chio_ladder_manifest_stale",
    "chio_lineage_bundle_cycle",
    "chio_lineage_bundle_incomplete",
    "chio_lineage_bundle_unverified_edge",
    "chio_swarm_authority_ref_mismatch",
    "chio_swarm_authority_rejected",
    "chio_swarm_continuation_replay",
    "chio_swarm_continuation_store_unsupported",
    "chio_treaty_action_class_not_allowed",
    "chio_treaty_bilateral_hash_mismatch",
    "chio_treaty_bilateral_mismatch",
    "chio_treaty_continuation_hash_mismatch",
    "chio_treaty_continuation_mismatch",
    "chio_treaty_continuation_replay",
    "chio_treaty_continuation_stale",
    "chio_treaty_dsse_binding_mismatch",
    "chio_treaty_intersection_mismatch",
    "chio_treaty_lineage_hash_mismatch",
    "chio_treaty_lineage_mismatch",
    "chio_treaty_missing_bilateral_evidence",
    "chio_treaty_missing_continuation",
    "chio_treaty_missing_intersection",
    "chio_treaty_missing_intersection_binding",
    "chio_treaty_missing_participant",
    "chio_treaty_missing_required_evidence",
    "chio_treaty_missing_scope",
    "chio_treaty_policy_denied",
    "chio_treaty_scope_hash_mismatch",
    "chio_treaty_stale",
    "chio_treaty_unverified_required_evidence",
    "continuation_empty_action_class",
    "continuation_empty_audience",
    "continuation_empty_capability",
    "continuation_empty_id",
    "continuation_empty_nonce",
    "continuation_empty_source_kernel",
    "continuation_empty_target_kernel",
    "continuation_invalid_parent_hash",
    "continuation_invalid_session_anchor_hash",
    "continuation_invalid_window",
    "cross_boundary_admission_empty_action_class",
    "cross_boundary_admission_empty_treaty",
    "cross_boundary_admission_invalid_evidence_class",
    "cross_boundary_admission_invalid_evidence_hash",
    "cross_boundary_admission_invalid_intersection_hash",
    "cross_boundary_admission_invalid_treaty_hash",
    "cross_boundary_admission_missing_failure_code",
    "cross_boundary_admission_unexpected_failure_code",
    "destructive_lease_replay",
    "duplicate_admission_bundle_mismatch",
    "duplicate_consumed_lease",
    "duplicate_consumed_swarm_continuation",
    "duplicate_consumed_treaty_continuation",
    "duplicate_runtime_trust_floor",
    "duplicate_swarm_authority_bundle_mismatch",
    "duplicate_treaty_runtime_artifact_mismatch",
    "duplicate_trusted_verifier_key",
    "governance_ladder_action_empty_id",
    "governance_ladder_destructive_missing_evidence",
    "governance_ladder_duplicate_evidence",
    "governance_ladder_empty_alias",
    "governance_ladder_invalid_evidence_label",
    "governance_ladder_manifest_empty_id",
    "governance_ladder_manifest_empty_issuer",
    "governance_ladder_manifest_empty_kernel",
    "governance_ladder_manifest_empty_key",
    "governance_ladder_manifest_invalid_window",
    "governance_ladder_manifest_missing_action_classes",
    "governance_ladder_manifest_unknown_default_not_deny",
    "host_kernel_mismatch",
    "invalid_chio_admission_context",
    "invalid_chio_swarm_context",
    "invalid_chio_swarm_evidence_ref",
    "invalid_chio_treaty_context",
    "invalid_chio_treaty_evidence_ref",
    "invalid_chio_treaty_hash",
    "invalid_pheromone_query_report",
    "ladder_intersection_empty_action_class",
    "ladder_intersection_empty_id",
    "ladder_intersection_empty_treaty",
    "missing_action_class_id",
    "missing_admission_bundle",
    "missing_admission_id",
    "missing_chio_admission_context",
    "missing_chio_swarm_authority_bundle",
    "missing_chio_swarm_evidence_ref",
    "missing_chio_treaty_context",
    "missing_chio_treaty_evidence_ref",
    "missing_destructive_lease",
    "missing_governance_receipt",
    "missing_governed_intent",
    "missing_ladder_intersection_hash",
    "missing_ladder_intersection_id",
    "missing_pheromone_concentration",
    "missing_runtime_peer_weights",
    "missing_runtime_pheromone_advisory",
    "missing_runtime_pheromone_policy",
    "missing_runtime_trust_input",
    "missing_treaty_scope_hash",
    "missing_treaty_scope_id",
    "receipt_lineage_bundle_empty_id",
    "receipt_lineage_bundle_invalid_leaf_hash",
    "receipt_lineage_bundle_invalid_root_hash",
    "receipt_lineage_empty_id",
    "receipt_lineage_empty_source_kernel",
    "receipt_lineage_empty_target_kernel",
    "receipt_lineage_invalid_bilateral_hash",
    "receipt_lineage_invalid_child_hash",
    "receipt_lineage_invalid_continuation_hash",
    "receipt_lineage_invalid_evidence_class",
    "receipt_lineage_invalid_parent_hash",
    "request_binding_mismatch",
    "request_smuggled_dynamic_trust",
    "request_smuggled_trust_root",
    "runtime_admission_canonical",
    "runtime_evidence_artifact_byte_count_mismatch",
    "runtime_evidence_artifact_hash_mismatch",
    "runtime_evidence_health_empty_run_id",
    "runtime_evidence_health_invalid_required_role",
    "runtime_evidence_health_invalid_root_hash",
    "runtime_evidence_manifest_duplicate_path",
    "runtime_evidence_manifest_empty_role",
    "runtime_evidence_manifest_invalid_artifact_hash",
    "runtime_evidence_manifest_invalid_proof_report_hash",
    "runtime_evidence_manifest_invalid_workflow_report_hash",
    "runtime_evidence_manifest_missing_entries",
    "runtime_evidence_manifest_run_mismatch",
    "runtime_evidence_missing_required_role",
    "runtime_evidence_sink_unavailable",
    "runtime_ops_status_accepted_degraded",
    "runtime_ops_status_degraded",
    "runtime_ops_status_invalid_profile_hash",
    "runtime_ops_status_invalid_run_state",
    "runtime_orchestration_plan_duplicate_step",
    "runtime_orchestration_plan_empty_admission_id",
    "runtime_orchestration_plan_empty_run_id",
    "runtime_orchestration_plan_invalid_contract_hash",
    "runtime_orchestration_plan_invalid_profile_hash",
    "runtime_orchestration_plan_invalid_step_state",
    "runtime_orchestration_plan_missing_failure_code",
    "runtime_orchestration_plan_missing_steps",
    "runtime_orchestration_plan_unexpected_failure_code",
    "runtime_orchestration_profile_duplicate_fail_closed_code",
    "runtime_orchestration_profile_empty_id",
    "runtime_orchestration_profile_empty_kernel",
    "runtime_orchestration_profile_empty_verifier",
    "runtime_orchestration_profile_invalid_fail_closed_code",
    "runtime_orchestration_profile_invalid_mode",
    "runtime_orchestration_profile_invalid_window",
    "runtime_orchestration_profile_stale",
    "runtime_orchestration_profile_zero_concurrency",
    "runtime_orchestration_resume_accepted_blocked",
    "runtime_orchestration_resume_empty_run_id",
    "runtime_orchestration_resume_missing_failure_code",
    "runtime_orchestration_resume_unexpected_failure_code",
    "runtime_orchestration_run_accepted_without_proof",
    "runtime_orchestration_run_duplicate_step",
    "runtime_orchestration_run_empty_id",
    "runtime_orchestration_run_invalid_contract_hash",
    "runtime_orchestration_run_invalid_manifest_hash",
    "runtime_orchestration_run_invalid_profile_hash",
    "runtime_orchestration_run_invalid_proof_hash",
    "runtime_orchestration_run_invalid_status",
    "runtime_orchestration_run_invalid_verifier_hash",
    "runtime_orchestration_run_invalid_workflow_hash",
    "runtime_orchestration_run_missing_accepted_hash",
    "runtime_orchestration_run_missing_failure_code",
    "runtime_orchestration_run_missing_steps",
    "runtime_orchestration_run_unexpected_failure_code",
    "runtime_orchestration_status_accepted_degraded",
    "runtime_orchestration_status_invalid_profile_hash",
    "runtime_orchestration_status_invalid_run_state",
    "runtime_orchestration_status_invalid_store_backend",
    "runtime_orchestration_status_invalid_store_hash",
    "runtime_orchestration_step_empty_admission_id",
    "runtime_orchestration_step_invalid_admission_hash",
    "runtime_orchestration_step_invalid_receipt_hash",
    "runtime_orchestration_step_invalid_state",
    "runtime_orchestration_step_missing_destructive_lease",
    "runtime_orchestration_verifier_report_rejected",
    "runtime_ops_supervisor_profile_stale",
    "runtime_peer_weights_duplicate_peer",
    "runtime_peer_weights_hash_failed",
    "runtime_peer_weights_hash_mismatch",
    "runtime_peer_weights_invalid",
    "runtime_peer_weights_stale",
    "runtime_peer_weights_untrusted",
    "runtime_pheromone_advisory_future_dated",
    "runtime_pheromone_advisory_not_observe_only",
    "runtime_pheromone_advisory_rejected",
    "runtime_pheromone_advisory_stale",
    "runtime_pheromone_distinct_origin_floor",
    "runtime_pheromone_policy_action_class_missing",
    "runtime_pheromone_policy_allow",
    "runtime_pheromone_policy_deny",
    "runtime_pheromone_policy_direction_unsupported",
    "runtime_pheromone_policy_effect_unsupported",
    "runtime_pheromone_policy_escalate",
    "runtime_pheromone_policy_mode_unsupported",
    "runtime_pheromone_policy_query_report_signer_mismatch",
    "runtime_pheromone_policy_stale",
    "runtime_pheromone_policy_trust_mismatch",
    "runtime_pheromone_policy_untrusted",
    "runtime_pheromone_policy_verifier_mismatch",
    "runtime_pheromone_query_report_signature_invalid",
    "runtime_pheromone_required_for_destructive",
    "runtime_policy_hash_failed",
    "runtime_proof_drift_accepted_with_drifts",
    "runtime_proof_drift_detected",
    "runtime_proof_drift_empty_artifact_role",
    "runtime_proof_drift_empty_baseline",
    "runtime_proof_drift_empty_candidate",
    "runtime_proof_drift_empty_field",
    "runtime_proof_drift_invalid_baseline_artifact_hash",
    "runtime_proof_drift_invalid_baseline_manifest_hash",
    "runtime_proof_drift_invalid_baseline_proof_hash",
    "runtime_proof_drift_invalid_baseline_value_hash",
    "runtime_proof_drift_invalid_candidate_artifact_hash",
    "runtime_proof_drift_invalid_candidate_manifest_hash",
    "runtime_proof_drift_invalid_candidate_proof_hash",
    "runtime_proof_drift_invalid_candidate_value_hash",
    "runtime_proof_drift_invalid_severity",
    "runtime_proof_parity_accepted_with_mismatches",
    "runtime_proof_parity_empty_mismatch_field",
    "runtime_proof_parity_invalid_runtime_package_hash",
    "runtime_proof_parity_invalid_runtime_report_hash",
    "runtime_proof_parity_invalid_runtime_value_hash",
    "runtime_proof_parity_invalid_static_package_hash",
    "runtime_proof_parity_invalid_static_report_hash",
    "runtime_proof_parity_invalid_static_value_hash",
    "runtime_proof_parity_missing_compared_fields",
    "runtime_proof_regeneration_duplicate_source_record",
    "runtime_proof_regeneration_input_invalid_admission_hash",
    "runtime_proof_regeneration_input_invalid_context_hash",
    "runtime_proof_regeneration_input_invalid_manifest_hash",
    "runtime_proof_regeneration_input_invalid_trust_bundle_hash",
    "runtime_proof_regeneration_input_invalid_workflow_report_hash",
    "runtime_proof_regeneration_input_missing_source_records",
    "runtime_proof_regeneration_invalid_admission_hash",
    "runtime_proof_regeneration_invalid_dsse_hash",
    "runtime_proof_regeneration_invalid_package_hash",
    "runtime_proof_regeneration_invalid_tool_receipt_hash",
    "runtime_proof_regeneration_invalid_verifier_report_hash",
    "runtime_proof_regeneration_invalid_workflow_receipt_hash",
    "runtime_proof_regeneration_invalid_workflow_step_hash",
    "runtime_proof_regeneration_missing_package_hash",
    "runtime_proof_regeneration_missing_run_id",
    "runtime_proof_regeneration_missing_source_records",
    "runtime_proof_regeneration_missing_verifier_report_hash",
    "runtime_proof_regeneration_missing_workflow_receipt_hash",
    "runtime_proof_regeneration_run_id_mismatch",
    "runtime_provider_discovery_not_allowed",
    "runtime_provider_duplicate_loaded_weights_evidence",
    "runtime_provider_duplicate_id",
    "runtime_provider_empty_id",
    "runtime_provider_empty_kernel",
    "runtime_provider_empty_server",
    "runtime_provider_empty_tool",
    "runtime_provider_health_accepted_with_failed_check",
    "runtime_provider_health_check_count_mismatch",
    "runtime_provider_health_degraded",
    "runtime_provider_health_degraded_ids_mismatch",
    "runtime_provider_health_empty_binding_id",
    "runtime_provider_health_empty_degraded_id",
    "runtime_provider_health_healthy_count_mismatch",
    "runtime_provider_health_invalid_bindings_hash",
    "runtime_provider_health_invalid_check",
    "runtime_provider_health_missing_failure_code",
    "runtime_provider_health_unexpected_failure_code",
    "runtime_provider_invalid_binding_id",
    "runtime_provider_invalid_loaded_weights_evidence",
    "runtime_provider_invalid_loaded_weights_hash",
    "runtime_provider_invalid_model_card_digest",
    "runtime_provider_invalid_model_card_id",
    "runtime_provider_loaded_weights_hash_mismatch",
    "runtime_provider_loaded_weights_unavailable",
    "runtime_provider_model_card_digest_mismatch",
    "runtime_provider_model_card_missing",
    "runtime_provider_model_card_scope_not_allowed",
    "runtime_provider_model_card_stale",
    "runtime_provider_model_card_tool_banned",
    "runtime_provider_supervisor_profile_stale",
    "runtime_recovery_accepted_blocked",
    "runtime_recovery_empty_run_id",
    "runtime_recovery_run_not_found",
    "runtime_recovery_supervisor_profile_stale",
    "runtime_reputation_epoch_mismatch",
    "runtime_resume_destructive_repair_required",
    "runtime_resume_non_contiguous_recovery_steps",
    "runtime_retention_dry_run_only",
    "runtime_retention_empty_kernel",
    "runtime_retention_empty_profile_id",
    "runtime_retention_empty_run_id",
    "runtime_retention_invalid_action",
    "runtime_retention_invalid_profile_hash",
    "runtime_retention_invalid_reason",
    "runtime_retention_invalid_window",
    "runtime_retention_legal_hold",
    "runtime_retention_mutation_not_allowed",
    "runtime_retention_plan_missing_failure_code",
    "runtime_retention_plan_unexpected_failure_code",
    "runtime_retention_profile_stale",
    "runtime_run_contract_duplicate_admission_id",
    "runtime_run_contract_empty_admission_id",
    "runtime_run_contract_empty_evidence_sink",
    "runtime_run_contract_empty_run_id",
    "runtime_run_contract_empty_store",
    "runtime_run_contract_empty_workflow",
    "runtime_run_contract_invalid_profile_hash",
    "runtime_run_contract_step_count_mismatch",
    "runtime_run_contract_zero_steps",
    "runtime_run_empty_id",
    "runtime_run_invalid_status",
    "runtime_run_lease_conflict",
    "runtime_run_lease_empty_lease_id",
    "runtime_run_lease_empty_owner",
    "runtime_run_lease_empty_run_id",
    "runtime_run_lease_expired",
    "runtime_run_lease_invalid_state",
    "runtime_run_lease_invalid_time_order",
    "runtime_run_lease_invalid_ttl",
    "runtime_run_lease_missing",
    "runtime_run_stale_fencing_token",
    "runtime_scheduler_empty_owner",
    "runtime_scheduler_empty_tick_id",
    "runtime_scheduler_profile_stale",
    "runtime_sqlite_integer_negative",
    "runtime_sqlite_integer_out_of_range",
    "runtime_swarm_authority_empty_graph_id",
    "runtime_step_evidence_invalid_admission_hash",
    "runtime_step_evidence_invalid_dsse_hash",
    "runtime_step_evidence_invalid_output_hash",
    "runtime_step_evidence_invalid_parent_hash",
    "runtime_step_evidence_invalid_tool_receipt_hash",
    "runtime_step_evidence_invalid_workflow_step_hash",
    "runtime_step_evidence_missing_admission_id",
    "runtime_step_evidence_missing_consistency_anchor",
    "runtime_step_evidence_missing_governance",
    "runtime_supervisor_empty_kernel",
    "runtime_supervisor_empty_profile_id",
    "runtime_supervisor_invalid_fail_closed_code",
    "runtime_supervisor_invalid_limits",
    "runtime_supervisor_invalid_required_role",
    "runtime_supervisor_invalid_window",
    "runtime_treaty_artifact_empty_id",
    "runtime_treaty_artifact_invalid_kind",
    "runtime_trust_bundle_hash_mismatch",
    "runtime_trust_context_hash_mismatch",
    "runtime_trust_floor_version_zero",
    "runtime_trust_hash_failed",
    "runtime_trust_input_verifier_mismatch",
    "runtime_trust_previous_hash_mismatch",
    "runtime_trust_previous_hash_missing",
    "runtime_trust_revocation_roots_missing",
    "runtime_trust_rollback",
    "runtime_trust_same_version_mismatch",
    "runtime_trust_signature_invalid",
    "runtime_trust_signer_inactive",
    "runtime_trust_signer_stale",
    "runtime_trust_signer_untrusted",
    "runtime_trust_stale",
    "runtime_trust_version_zero",
    "runtime_workflow_duplicate_step_evidence",
    "runtime_workflow_invalid_admission_report_hash",
    "runtime_workflow_invalid_proof_regeneration_hash",
    "runtime_workflow_missing_proof_regeneration_report",
    "runtime_workflow_missing_step_evidence",
    "signature_invalid",
    "signer_inactive",
    "signer_stale",
    "signer_untrusted",
    "stale_profile",
    "treaty_scope_duplicate_participant",
    "treaty_scope_duplicate_participant_key",
    "treaty_scope_empty_action_class",
    "treaty_scope_empty_id",
    "treaty_scope_empty_participant",
    "treaty_scope_invalid_revocation_epoch_hash",
    "treaty_scope_invalid_trust_bundle_hash",
    "unsupported_bilateral_invocation_schema",
    "unsupported_bundle_schema",
    "unsupported_buyer_attestation_packet_schema",
    "unsupported_buyer_attestation_review_package_schema",
    "unsupported_buyer_attestation_review_report_schema",
    "unsupported_buyer_attestation_verification_report_schema",
    "unsupported_cross_boundary_admission_report_schema",
    "unsupported_cross_kernel_continuation_schema",
    "unsupported_governance_ladder_manifest_schema",
    "unsupported_ladder_intersection_schema",
    "unsupported_pheromone_query_report_schema",
    "unsupported_profile_schema",
    "unsupported_receipt_lineage_bundle_schema",
    "unsupported_receipt_lineage_statement_schema",
    "unsupported_runtime_evidence_manifest_schema",
    "unsupported_runtime_evidence_sink_health_report_schema",
    "unsupported_runtime_ops_status_report_schema",
    "unsupported_runtime_orchestration_plan_schema",
    "unsupported_runtime_orchestration_profile_schema",
    "unsupported_runtime_orchestration_resume_plan_schema",
    "unsupported_runtime_orchestration_run_report_schema",
    "unsupported_runtime_orchestration_status_report_schema",
    "unsupported_runtime_peer_weights_schema",
    "unsupported_runtime_pheromone_policy_schema",
    "unsupported_runtime_proof_drift_report_schema",
    "unsupported_runtime_proof_parity_report_schema",
    "unsupported_runtime_proof_regeneration_input_schema",
    "unsupported_runtime_proof_regeneration_report_schema",
    "unsupported_runtime_provider_bindings_schema",
    "unsupported_runtime_provider_health_report_schema",
    "unsupported_runtime_recovery_drill_report_schema",
    "unsupported_runtime_retention_plan_schema",
    "unsupported_runtime_retention_profile_schema",
    "unsupported_runtime_run_contract_schema",
    "unsupported_runtime_run_lease_schema",
    "unsupported_runtime_scheduler_tick_report_schema",
    "unsupported_runtime_step_evidence_schema",
    "unsupported_runtime_store_schema",
    "unsupported_runtime_supervisor_profile_schema",
    "unsupported_runtime_trust_floor_state_schema",
    "unsupported_runtime_trust_schema",
    "unsupported_runtime_workflow_report_schema",
    "unsupported_treaty_scope_schema",
    "unsupported_trusted_verifiers_schema",
];
