//! Tenant-scoped encrypted BLOB persistence for tee capture payloads.
//!
//! The tee stores redacted request and response bodies as opaque
//! binary payloads. This module keeps those payloads encrypted at rest
//! with a tenant-provided 32-byte key and a per-blob ChaCha20-Poly1305
//! nonce. Authentication failures on read are surfaced as errors and do
//! not return plaintext.

use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use chacha20poly1305::aead::rand_core::RngCore;
use chacha20poly1305::aead::{Aead, KeyInit, OsRng, Payload};
use chacha20poly1305::{ChaCha20Poly1305, Key, Nonce};
use r2d2::Pool;
use r2d2_sqlite::SqliteConnectionManager;
use rusqlite::{params, Connection, OptionalExtension, TransactionBehavior};
use uuid::Uuid;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Tenant identifier used to isolate encrypted BLOB rows.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct TenantId(String);

impl TenantId {
    /// Construct a tenant id from a string-like value.
    #[must_use]
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    /// Borrow the tenant id as stored in SQLite.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for TenantId {
    fn from(value: &str) -> Self {
        Self::new(value)
    }
}

impl From<String> for TenantId {
    fn from(value: String) -> Self {
        Self::new(value)
    }
}

/// Tenant-scoped 256-bit AEAD key.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct TenantKey([u8; 32]);

impl TenantKey {
    /// Construct from exactly 32 bytes.
    #[must_use]
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Borrow key bytes for callers that already own secure key custody.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Ciphertext plus the unique nonce required for decryption.
#[derive(Clone, PartialEq, Eq)]
pub struct EncryptedBlob {
    /// ChaCha20-Poly1305 ciphertext and authentication tag.
    pub ciphertext: Vec<u8>,
    /// 96-bit nonce generated per encrypted blob.
    pub nonce: [u8; 12],
}

struct StoredEncryptedBlob {
    blob: EncryptedBlob,
    blob_id: String,
    tenant_id: TenantId,
    created_at: i64,
}

impl std::fmt::Debug for EncryptedBlob {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EncryptedBlob")
            .field("ciphertext_len", &self.ciphertext.len())
            .field("nonce", &self.nonce)
            .finish()
    }
}

/// Opaque handle returned after a blob is written.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct BlobHandle {
    blob_id: String,
    tenant_id: TenantId,
}

/// Tenant-scoped opaque lookup key for an encrypted blob.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct BlobReference {
    namespace: String,
    tenant_id: TenantId,
    reference_key: [u8; 32],
}

/// Result of an operation-id-bound reference mutation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BlobReferenceMutationOutcome {
    /// This call applied the mutation.
    Applied,
    /// The exact mutation was already durably applied.
    Replayed,
}

impl BlobReference {
    /// Construct a closed reference key in a service-owned namespace.
    pub fn new(
        namespace: impl Into<String>,
        tenant_id: TenantId,
        reference_key: [u8; 32],
    ) -> Result<Self, BlobStoreError> {
        let namespace = namespace.into();
        validate_tenant_id(&tenant_id)?;
        if namespace.is_empty()
            || namespace.len() > 128
            || !namespace
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
        {
            return Err(BlobStoreError::InvalidReference);
        }
        Ok(Self {
            namespace,
            tenant_id,
            reference_key,
        })
    }

    /// Return the namespace that owns the opaque mapping.
    #[must_use]
    pub fn namespace(&self) -> &str {
        &self.namespace
    }

    /// Return the tenant scope bound into the mapping.
    #[must_use]
    pub fn tenant_id(&self) -> &TenantId {
        &self.tenant_id
    }

    fn reference_key(&self) -> &[u8; 32] {
        &self.reference_key
    }
}

impl BlobHandle {
    fn new(blob_id: String, tenant_id: TenantId) -> Self {
        Self { blob_id, tenant_id }
    }

    /// Stable blob id generated by the store.
    #[must_use]
    pub fn blob_id(&self) -> &str {
        &self.blob_id
    }

    /// Tenant scope bound into this handle.
    #[must_use]
    pub fn tenant_id(&self) -> &TenantId {
        &self.tenant_id
    }
}

/// Decryption failure. Authentication failure is intentionally coarse so
/// callers cannot distinguish a wrong key from ciphertext tampering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecryptError {
    /// AEAD authentication failed.
    AuthenticationFailed,
}

impl std::fmt::Display for DecryptError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::AuthenticationFailed => f.write_str("blob authentication failed"),
        }
    }
}

impl std::error::Error for DecryptError {}

/// Errors returned by SQLite encrypted BLOB persistence.
#[derive(Debug)]
pub enum BlobStoreError {
    /// SQLite connection pool acquisition failed.
    Pool(String),
    /// SQLite returned an error.
    Sqlite(String),
    /// Filesystem operation failed while opening a store.
    Io(String),
    /// Tenant ids must be present before a blob can be persisted.
    EmptyTenantId,
    /// Tenant ids must be exact storage scope keys.
    InvalidTenantId,
    /// Stored nonce length was not the required 12 bytes.
    InvalidNonceLength(usize),
    /// Opaque reference namespace or key was malformed.
    InvalidReference,
    /// The handle did not identify a row in its tenant scope.
    NotFound,
    /// A durable mutation id was reused for different mutation content.
    MutationConflict,
    /// AEAD authentication failed.
    Decrypt(DecryptError),
}

impl std::fmt::Display for BlobStoreError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Pool(error) => write!(f, "sqlite encrypted blob pool error: {error}"),
            Self::Sqlite(error) => write!(f, "sqlite encrypted blob error: {error}"),
            Self::Io(error) => write!(f, "sqlite encrypted blob io error: {error}"),
            Self::EmptyTenantId => f.write_str("tenant id must not be empty"),
            Self::InvalidTenantId => {
                f.write_str("tenant id must be unpadded and contain no control characters")
            }
            Self::InvalidNonceLength(len) => {
                write!(f, "encrypted blob nonce must be 12 bytes, got {len}")
            }
            Self::InvalidReference => f.write_str("encrypted blob reference is invalid"),
            Self::NotFound => f.write_str("encrypted blob handle not found"),
            Self::MutationConflict => {
                f.write_str("encrypted blob mutation id conflicts with durable content")
            }
            Self::Decrypt(error) => write!(f, "encrypted blob decrypt error: {error}"),
        }
    }
}

impl std::error::Error for BlobStoreError {}

impl From<rusqlite::Error> for BlobStoreError {
    fn from(error: rusqlite::Error) -> Self {
        Self::Sqlite(error.to_string())
    }
}

impl From<r2d2::Error> for BlobStoreError {
    fn from(error: r2d2::Error) -> Self {
        Self::Pool(error.to_string())
    }
}

impl From<std::io::Error> for BlobStoreError {
    fn from(error: std::io::Error) -> Self {
        Self::Io(error.to_string())
    }
}

impl From<DecryptError> for BlobStoreError {
    fn from(error: DecryptError) -> Self {
        Self::Decrypt(error)
    }
}

/// Encryption failure surfaced without panicking in public helpers.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EncryptError {
    /// AEAD encryption failed.
    EncryptionFailed,
}

impl std::fmt::Display for EncryptError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EncryptionFailed => f.write_str("blob encryption failed"),
        }
    }
}

impl std::error::Error for EncryptError {}

/// Encrypt `plaintext` with the tenant key.
pub fn encrypt_blob(
    tenant_key: &TenantKey,
    plaintext: &[u8],
) -> Result<EncryptedBlob, EncryptError> {
    try_encrypt_blob(tenant_key, plaintext).map_err(|_| EncryptError::EncryptionFailed)
}

/// Decrypt `blob` with the tenant key.
pub fn decrypt_blob(tenant_key: &TenantKey, blob: &EncryptedBlob) -> Result<Vec<u8>, DecryptError> {
    let cipher = cipher_for_key(tenant_key);
    cipher
        .decrypt(Nonce::from_slice(&blob.nonce), blob.ciphertext.as_ref())
        .map_err(|_| DecryptError::AuthenticationFailed)
}

fn decrypt_blob_with_aad(
    tenant_key: &TenantKey,
    blob: &EncryptedBlob,
    aad: &[u8],
) -> Result<Vec<u8>, DecryptError> {
    let cipher = cipher_for_key(tenant_key);
    cipher
        .decrypt(
            Nonce::from_slice(&blob.nonce),
            Payload {
                msg: blob.ciphertext.as_ref(),
                aad,
            },
        )
        .map_err(|_| DecryptError::AuthenticationFailed)
}

fn try_encrypt_blob(tenant_key: &TenantKey, plaintext: &[u8]) -> Result<EncryptedBlob, ()> {
    try_encrypt_blob_with_aad(tenant_key, plaintext, &[])
}

fn try_encrypt_blob_with_aad(
    tenant_key: &TenantKey,
    plaintext: &[u8],
    aad: &[u8],
) -> Result<EncryptedBlob, ()> {
    let cipher = cipher_for_key(tenant_key);
    let mut nonce = [0_u8; 12];
    OsRng.fill_bytes(&mut nonce);
    let ciphertext = cipher
        .encrypt(
            Nonce::from_slice(&nonce),
            Payload {
                msg: plaintext,
                aad,
            },
        )
        .map_err(|_| ())?;
    Ok(EncryptedBlob { ciphertext, nonce })
}

fn cipher_for_key(tenant_key: &TenantKey) -> ChaCha20Poly1305 {
    ChaCha20Poly1305::new(Key::from_slice(tenant_key.as_bytes()))
}

/// SQLite-backed encrypted BLOB store.
pub struct SqliteEncryptedBlobStore {
    pool: Pool<SqliteConnectionManager>,
}

/// Encrypted-blob-store schema revision. Bump on every schema-affecting change.
const ENCRYPTED_BLOB_STORE_SUPPORTED_SCHEMA_VERSION: i32 = 0;
/// Stable key under which this store records its schema revision in the shared
/// keyed metadata table, distinct from any co-located store's key.
const ENCRYPTED_BLOB_STORE_SCHEMA_KEY: &str = "encrypted_blob";
/// Tables shipped before schema stamping existed, used to adopt a pre-stamping
/// encrypted-blob database rather than reject it as foreign.
const ENCRYPTED_BLOB_STORE_LEGACY_ANCHOR_TABLES: &[&str] =
    &["chio_encrypted_blobs", "security_transitions"];

impl SqliteEncryptedBlobStore {
    /// Open the store at `path`, creating parent directories if needed.
    pub fn open(path: impl AsRef<Path>) -> Result<Self, BlobStoreError> {
        let path = path.as_ref();
        // Resolve any `file:` URI to its on-disk parent before creating it, so a
        // URI-configured store creates the real backing directory rather than a
        // bogus scheme-prefixed one.
        if let Some(parent) = crate::sqlite_parent_dir_to_create(path) {
            fs::create_dir_all(&parent)?;
        }
        let manager = SqliteConnectionManager::file(path)
            .with_flags(
                rusqlite::OpenFlags::SQLITE_OPEN_READ_WRITE
                    | rusqlite::OpenFlags::SQLITE_OPEN_CREATE
                    | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
            )
            .with_init(configure_blob_connection);
        let pool = Pool::builder().max_size(8).build(manager)?;
        let store = Self { pool };
        store.run_migrations()?;
        Ok(store)
    }

    /// Open an in-memory store for tests.
    pub fn open_in_memory() -> Result<Self, BlobStoreError> {
        let manager = SqliteConnectionManager::memory().with_init(configure_blob_connection);
        let pool = Pool::builder().max_size(1).build(manager)?;
        let store = Self { pool };
        store.run_migrations()?;
        Ok(store)
    }

    fn run_migrations(&self) -> Result<(), BlobStoreError> {
        let conn = self.pool.get()?;
        crate::check_schema_version(
            &conn,
            ENCRYPTED_BLOB_STORE_SCHEMA_KEY,
            ENCRYPTED_BLOB_STORE_SUPPORTED_SCHEMA_VERSION,
            ENCRYPTED_BLOB_STORE_LEGACY_ANCHOR_TABLES,
        )
        .map_err(|error| BlobStoreError::Sqlite(error.to_string()))?;
        conn.execute_batch(
            r#"
            PRAGMA journal_mode = WAL;
            PRAGMA synchronous = FULL;
            PRAGMA busy_timeout = 5000;

            CREATE TABLE IF NOT EXISTS chio_encrypted_blobs (
                blob_id TEXT PRIMARY KEY,
                tenant_id TEXT NOT NULL,
                nonce BLOB NOT NULL CHECK(length(nonce) = 12),
                ciphertext BLOB NOT NULL,
                created_at INTEGER NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_chio_encrypted_blobs_tenant
                ON chio_encrypted_blobs(tenant_id, created_at);

            CREATE TABLE IF NOT EXISTS chio_encrypted_blob_references (
                namespace TEXT NOT NULL,
                tenant_id TEXT NOT NULL,
                reference_key BLOB NOT NULL CHECK(length(reference_key) = 32),
                blob_id TEXT NOT NULL,
                enabled INTEGER NOT NULL CHECK(enabled IN (0, 1)),
                PRIMARY KEY (namespace, tenant_id, reference_key),
                FOREIGN KEY (blob_id) REFERENCES chio_encrypted_blobs(blob_id)
                    ON DELETE RESTRICT
            );

            CREATE UNIQUE INDEX IF NOT EXISTS idx_chio_encrypted_blob_reference_blob
                ON chio_encrypted_blob_references(blob_id);

            CREATE TABLE IF NOT EXISTS chio_encrypted_blob_reference_mutations (
                operation_id TEXT PRIMARY KEY,
                mutation_digest TEXT NOT NULL,
                mutation_kind TEXT NOT NULL CHECK(
                    mutation_kind IN ('provision', 'disable', 'delete')
                ),
                namespace TEXT NOT NULL,
                tenant_id TEXT NOT NULL,
                reference_key BLOB NOT NULL CHECK(length(reference_key) = 32),
                result_blob_id TEXT,
                applied_at INTEGER NOT NULL CHECK(applied_at >= 0)
            );

            CREATE TRIGGER IF NOT EXISTS chio_encrypted_blob_reference_mutations_no_update
            BEFORE UPDATE ON chio_encrypted_blob_reference_mutations
            BEGIN
                SELECT RAISE(ABORT, 'encrypted blob reference mutations are append-only');
            END;

            CREATE TRIGGER IF NOT EXISTS chio_encrypted_blob_reference_mutations_no_delete
            BEFORE DELETE ON chio_encrypted_blob_reference_mutations
            BEGIN
                SELECT RAISE(ABORT, 'encrypted blob reference mutations are append-only');
            END;
            "#,
        )?;
        crate::stamp_schema_version(
            &conn,
            ENCRYPTED_BLOB_STORE_SCHEMA_KEY,
            ENCRYPTED_BLOB_STORE_SUPPORTED_SCHEMA_VERSION,
        )
        .map_err(|error| BlobStoreError::Sqlite(error.to_string()))?;
        Ok(())
    }

    /// Write `payload` encrypted under `key` and return an opaque handle.
    pub fn write_encrypted_blob(
        &self,
        tenant_id: &TenantId,
        key: &TenantKey,
        payload: &[u8],
    ) -> Result<BlobHandle, BlobStoreError> {
        validate_tenant_id(tenant_id)?;
        let blob_id = format!("blob-{}", Uuid::now_v7());
        let created_at = now_secs();
        let aad = blob_aad(&blob_id, tenant_id.as_str(), created_at);
        let encrypted = try_encrypt_blob_with_aad(key, payload, &aad)
            .map_err(|_| BlobStoreError::Decrypt(DecryptError::AuthenticationFailed))?;
        let conn = self.pool.get()?;
        conn.execute(
            r#"
            INSERT INTO chio_encrypted_blobs
                (blob_id, tenant_id, nonce, ciphertext, created_at)
            VALUES
                (?1, ?2, ?3, ?4, ?5)
            "#,
            params![
                blob_id,
                tenant_id.as_str(),
                encrypted.nonce.as_slice(),
                encrypted.ciphertext,
                created_at,
            ],
        )?;
        Ok(BlobHandle::new(blob_id, tenant_id.clone()))
    }

    /// Atomically write encrypted bytes and bind an opaque service reference.
    pub fn write_encrypted_blob_with_reference(
        &self,
        reference: &BlobReference,
        key: &TenantKey,
        payload: &[u8],
    ) -> Result<BlobHandle, BlobStoreError> {
        validate_tenant_id(reference.tenant_id())?;
        let blob_id = format!("blob-{}", Uuid::now_v7());
        let created_at = now_secs();
        let aad = blob_aad(&blob_id, reference.tenant_id().as_str(), created_at);
        let encrypted = try_encrypt_blob_with_aad(key, payload, &aad)
            .map_err(|_| BlobStoreError::Decrypt(DecryptError::AuthenticationFailed))?;
        let mut conn = self.pool.get()?;
        let transaction = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
        transaction.execute(
            r#"
            INSERT INTO chio_encrypted_blobs
                (blob_id, tenant_id, nonce, ciphertext, created_at)
            VALUES
                (?1, ?2, ?3, ?4, ?5)
            "#,
            params![
                blob_id,
                reference.tenant_id().as_str(),
                encrypted.nonce.as_slice(),
                encrypted.ciphertext,
                created_at,
            ],
        )?;
        transaction.execute(
            r#"
            INSERT INTO chio_encrypted_blob_references
                (namespace, tenant_id, reference_key, blob_id, enabled)
            VALUES
                (?1, ?2, ?3, ?4, 1)
            "#,
            params![
                reference.namespace(),
                reference.tenant_id().as_str(),
                reference.reference_key().as_slice(),
                blob_id,
            ],
        )?;
        transaction.commit()?;
        Ok(BlobHandle::new(blob_id, reference.tenant_id().clone()))
    }

    /// Atomically apply an encrypted reference write once for an exact
    /// operation and mutation digest. Exact retries return the original
    /// handle. Reuse of an operation id for different content fails closed.
    pub fn write_encrypted_blob_with_reference_once(
        &self,
        reference: &BlobReference,
        key: &TenantKey,
        payload: &[u8],
        operation_id: &str,
        mutation_digest: &str,
    ) -> Result<(BlobHandle, BlobReferenceMutationOutcome), BlobStoreError> {
        validate_tenant_id(reference.tenant_id())?;
        validate_mutation_binding(operation_id, mutation_digest)?;
        let mut conn = self.pool.get()?;
        let transaction = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
        if let Some(blob_id) = exact_reference_mutation(
            &transaction,
            operation_id,
            mutation_digest,
            "provision",
            reference,
        )? {
            let blob_id = blob_id.ok_or(BlobStoreError::MutationConflict)?;
            transaction.commit()?;
            return Ok((
                BlobHandle::new(blob_id, reference.tenant_id().clone()),
                BlobReferenceMutationOutcome::Replayed,
            ));
        }

        let blob_id = format!("blob-{}", Uuid::now_v7());
        let created_at = now_secs();
        let aad = blob_aad(&blob_id, reference.tenant_id().as_str(), created_at);
        let encrypted = try_encrypt_blob_with_aad(key, payload, &aad)
            .map_err(|_| BlobStoreError::Decrypt(DecryptError::AuthenticationFailed))?;
        transaction.execute(
            r#"
            INSERT INTO chio_encrypted_blobs
                (blob_id, tenant_id, nonce, ciphertext, created_at)
            VALUES
                (?1, ?2, ?3, ?4, ?5)
            "#,
            params![
                blob_id,
                reference.tenant_id().as_str(),
                encrypted.nonce.as_slice(),
                encrypted.ciphertext,
                created_at,
            ],
        )?;
        transaction.execute(
            r#"
            INSERT INTO chio_encrypted_blob_references
                (namespace, tenant_id, reference_key, blob_id, enabled)
            VALUES
                (?1, ?2, ?3, ?4, 1)
            "#,
            params![
                reference.namespace(),
                reference.tenant_id().as_str(),
                reference.reference_key().as_slice(),
                blob_id,
            ],
        )?;
        record_reference_mutation(
            &transaction,
            ReferenceMutation {
                operation_id,
                mutation_digest,
                mutation_kind: "provision",
                reference,
                result_blob_id: Some(&blob_id),
                applied_at: created_at,
            },
        )?;
        transaction.commit()?;
        Ok((
            BlobHandle::new(blob_id, reference.tenant_id().clone()),
            BlobReferenceMutationOutcome::Applied,
        ))
    }

    /// Resolve an enabled opaque reference inside its tenant scope.
    pub fn resolve_blob_reference(
        &self,
        reference: &BlobReference,
    ) -> Result<BlobHandle, BlobStoreError> {
        validate_tenant_id(reference.tenant_id())?;
        let conn = self.pool.get()?;
        let blob_id = conn
            .query_row(
                r#"
                SELECT reference.blob_id
                FROM chio_encrypted_blob_references AS reference
                INNER JOIN chio_encrypted_blobs AS blob
                    ON blob.blob_id = reference.blob_id
                   AND blob.tenant_id = reference.tenant_id
                WHERE reference.namespace = ?1
                  AND reference.tenant_id = ?2
                  AND reference.reference_key = ?3
                  AND reference.enabled = 1
                "#,
                params![
                    reference.namespace(),
                    reference.tenant_id().as_str(),
                    reference.reference_key().as_slice(),
                ],
                |row| row.get::<_, String>(0),
            )
            .optional()?;
        blob_id
            .map(|blob_id| BlobHandle::new(blob_id, reference.tenant_id().clone()))
            .ok_or(BlobStoreError::NotFound)
    }

    /// Disable an opaque reference without deleting its encrypted bytes.
    pub fn disable_blob_reference(&self, reference: &BlobReference) -> Result<(), BlobStoreError> {
        validate_tenant_id(reference.tenant_id())?;
        let conn = self.pool.get()?;
        let changed = conn.execute(
            r#"
            UPDATE chio_encrypted_blob_references
            SET enabled = 0
            WHERE namespace = ?1 AND tenant_id = ?2 AND reference_key = ?3
            "#,
            params![
                reference.namespace(),
                reference.tenant_id().as_str(),
                reference.reference_key().as_slice(),
            ],
        )?;
        if changed == 1 {
            Ok(())
        } else {
            Err(BlobStoreError::NotFound)
        }
    }

    /// Atomically disable a reference once for an exact mutation id.
    pub fn disable_blob_reference_once(
        &self,
        reference: &BlobReference,
        operation_id: &str,
        mutation_digest: &str,
    ) -> Result<BlobReferenceMutationOutcome, BlobStoreError> {
        validate_tenant_id(reference.tenant_id())?;
        validate_mutation_binding(operation_id, mutation_digest)?;
        let mut conn = self.pool.get()?;
        let transaction = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
        if exact_reference_mutation(
            &transaction,
            operation_id,
            mutation_digest,
            "disable",
            reference,
        )?
        .is_some()
        {
            transaction.commit()?;
            return Ok(BlobReferenceMutationOutcome::Replayed);
        }
        let changed = transaction.execute(
            r#"
            UPDATE chio_encrypted_blob_references
            SET enabled = 0
            WHERE namespace = ?1 AND tenant_id = ?2 AND reference_key = ?3
              AND enabled = 1
            "#,
            params![
                reference.namespace(),
                reference.tenant_id().as_str(),
                reference.reference_key().as_slice(),
            ],
        )?;
        if changed != 1 {
            return Err(BlobStoreError::NotFound);
        }
        record_reference_mutation(
            &transaction,
            ReferenceMutation {
                operation_id,
                mutation_digest,
                mutation_kind: "disable",
                reference,
                result_blob_id: None,
                applied_at: now_secs(),
            },
        )?;
        transaction.commit()?;
        Ok(BlobReferenceMutationOutcome::Applied)
    }

    /// Delete an opaque reference and its encrypted bytes in one transaction.
    pub fn delete_blob_reference(&self, reference: &BlobReference) -> Result<(), BlobStoreError> {
        validate_tenant_id(reference.tenant_id())?;
        let mut conn = self.pool.get()?;
        let transaction = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
        let blob_id = transaction
            .query_row(
                r#"
                SELECT blob_id
                FROM chio_encrypted_blob_references
                WHERE namespace = ?1 AND tenant_id = ?2 AND reference_key = ?3
                "#,
                params![
                    reference.namespace(),
                    reference.tenant_id().as_str(),
                    reference.reference_key().as_slice(),
                ],
                |row| row.get::<_, String>(0),
            )
            .optional()?
            .ok_or(BlobStoreError::NotFound)?;
        transaction.execute(
            r#"
            DELETE FROM chio_encrypted_blob_references
            WHERE namespace = ?1 AND tenant_id = ?2 AND reference_key = ?3
            "#,
            params![
                reference.namespace(),
                reference.tenant_id().as_str(),
                reference.reference_key().as_slice(),
            ],
        )?;
        let deleted = transaction.execute(
            "DELETE FROM chio_encrypted_blobs WHERE blob_id = ?1 AND tenant_id = ?2",
            params![blob_id, reference.tenant_id().as_str()],
        )?;
        if deleted != 1 {
            return Err(BlobStoreError::NotFound);
        }
        transaction.commit()?;
        Ok(())
    }

    /// Atomically delete a reference once for an exact mutation id.
    pub fn delete_blob_reference_once(
        &self,
        reference: &BlobReference,
        operation_id: &str,
        mutation_digest: &str,
    ) -> Result<BlobReferenceMutationOutcome, BlobStoreError> {
        validate_tenant_id(reference.tenant_id())?;
        validate_mutation_binding(operation_id, mutation_digest)?;
        let mut conn = self.pool.get()?;
        let transaction = conn.transaction_with_behavior(TransactionBehavior::Immediate)?;
        if exact_reference_mutation(
            &transaction,
            operation_id,
            mutation_digest,
            "delete",
            reference,
        )?
        .is_some()
        {
            transaction.commit()?;
            return Ok(BlobReferenceMutationOutcome::Replayed);
        }
        let blob_id = transaction
            .query_row(
                r#"
                SELECT blob_id
                FROM chio_encrypted_blob_references
                WHERE namespace = ?1 AND tenant_id = ?2 AND reference_key = ?3
                "#,
                params![
                    reference.namespace(),
                    reference.tenant_id().as_str(),
                    reference.reference_key().as_slice(),
                ],
                |row| row.get::<_, String>(0),
            )
            .optional()?
            .ok_or(BlobStoreError::NotFound)?;
        transaction.execute(
            r#"
            DELETE FROM chio_encrypted_blob_references
            WHERE namespace = ?1 AND tenant_id = ?2 AND reference_key = ?3
            "#,
            params![
                reference.namespace(),
                reference.tenant_id().as_str(),
                reference.reference_key().as_slice(),
            ],
        )?;
        let deleted = transaction.execute(
            "DELETE FROM chio_encrypted_blobs WHERE blob_id = ?1 AND tenant_id = ?2",
            params![blob_id, reference.tenant_id().as_str()],
        )?;
        if deleted != 1 {
            return Err(BlobStoreError::NotFound);
        }
        record_reference_mutation(
            &transaction,
            ReferenceMutation {
                operation_id,
                mutation_digest,
                mutation_kind: "delete",
                reference,
                result_blob_id: None,
                applied_at: now_secs(),
            },
        )?;
        transaction.commit()?;
        Ok(BlobReferenceMutationOutcome::Applied)
    }

    /// Load encrypted material without decrypting it. Intended for
    /// audit, migration, and test verification paths.
    pub fn load_encrypted_blob(
        &self,
        handle: &BlobHandle,
    ) -> Result<EncryptedBlob, BlobStoreError> {
        let conn = self.pool.get()?;
        let row = conn
            .query_row(
                r#"
                SELECT nonce, ciphertext
                FROM chio_encrypted_blobs
                WHERE blob_id = ?1 AND tenant_id = ?2
                "#,
                params![handle.blob_id(), handle.tenant_id().as_str()],
                |row| {
                    let nonce: Vec<u8> = row.get("nonce")?;
                    let ciphertext: Vec<u8> = row.get("ciphertext")?;
                    Ok((nonce, ciphertext))
                },
            )
            .optional()?;

        let Some((nonce, ciphertext)) = row else {
            return Err(BlobStoreError::NotFound);
        };
        let nonce_len = nonce.len();
        let nonce = match <[u8; 12]>::try_from(nonce) {
            Ok(value) => value,
            Err(_) => return Err(BlobStoreError::InvalidNonceLength(nonce_len)),
        };
        Ok(EncryptedBlob { ciphertext, nonce })
    }

    /// Read and decrypt a blob. Wrong keys, wrong handles, and tampered
    /// ciphertext all fail closed by returning an error.
    pub fn read_encrypted_blob(
        &self,
        handle: &BlobHandle,
        key: &TenantKey,
    ) -> Result<Vec<u8>, BlobStoreError> {
        let stored = self.load_encrypted_blob_record(handle)?;
        let aad = blob_aad(
            &stored.blob_id,
            stored.tenant_id.as_str(),
            stored.created_at,
        );
        Ok(decrypt_blob_with_aad(key, &stored.blob, &aad)?)
    }

    fn load_encrypted_blob_record(
        &self,
        handle: &BlobHandle,
    ) -> Result<StoredEncryptedBlob, BlobStoreError> {
        let conn = self.pool.get()?;
        let row = conn
            .query_row(
                r#"
                SELECT blob_id, tenant_id, nonce, ciphertext, created_at
                FROM chio_encrypted_blobs
                WHERE blob_id = ?1 AND tenant_id = ?2
                "#,
                params![handle.blob_id(), handle.tenant_id().as_str()],
                |row| {
                    let blob_id: String = row.get("blob_id")?;
                    let tenant_id: String = row.get("tenant_id")?;
                    let nonce: Vec<u8> = row.get("nonce")?;
                    let ciphertext: Vec<u8> = row.get("ciphertext")?;
                    let created_at: i64 = row.get("created_at")?;
                    Ok((blob_id, tenant_id, nonce, ciphertext, created_at))
                },
            )
            .optional()?;

        let Some((blob_id, tenant_id, nonce, ciphertext, created_at)) = row else {
            return Err(BlobStoreError::NotFound);
        };
        let nonce_len = nonce.len();
        let nonce = match <[u8; 12]>::try_from(nonce) {
            Ok(value) => value,
            Err(_) => return Err(BlobStoreError::InvalidNonceLength(nonce_len)),
        };
        Ok(StoredEncryptedBlob {
            blob: EncryptedBlob { ciphertext, nonce },
            blob_id,
            tenant_id: TenantId::new(tenant_id),
            created_at,
        })
    }
}

fn validate_mutation_binding(
    operation_id: &str,
    mutation_digest: &str,
) -> Result<(), BlobStoreError> {
    let valid = |value: &str| {
        value.len() == 64
            && value
                .bytes()
                .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
    };
    if !valid(operation_id) || !valid(mutation_digest) {
        return Err(BlobStoreError::InvalidReference);
    }
    Ok(())
}

fn exact_reference_mutation(
    transaction: &rusqlite::Transaction<'_>,
    operation_id: &str,
    mutation_digest: &str,
    mutation_kind: &str,
    reference: &BlobReference,
) -> Result<Option<Option<String>>, BlobStoreError> {
    let existing = transaction
        .query_row(
            r#"
            SELECT mutation_digest, mutation_kind, namespace, tenant_id,
                   reference_key, result_blob_id
            FROM chio_encrypted_blob_reference_mutations
            WHERE operation_id = ?1
            "#,
            params![operation_id],
            |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, String>(2)?,
                    row.get::<_, String>(3)?,
                    row.get::<_, Vec<u8>>(4)?,
                    row.get::<_, Option<String>>(5)?,
                ))
            },
        )
        .optional()?;
    let Some((digest, kind, namespace, tenant_id, reference_key, blob_id)) = existing else {
        return Ok(None);
    };
    if digest != mutation_digest
        || kind != mutation_kind
        || namespace != reference.namespace()
        || tenant_id != reference.tenant_id().as_str()
        || reference_key.as_slice() != reference.reference_key()
    {
        return Err(BlobStoreError::MutationConflict);
    }
    Ok(Some(blob_id))
}

struct ReferenceMutation<'a> {
    operation_id: &'a str,
    mutation_digest: &'a str,
    mutation_kind: &'a str,
    reference: &'a BlobReference,
    result_blob_id: Option<&'a str>,
    applied_at: i64,
}

fn record_reference_mutation(
    transaction: &rusqlite::Transaction<'_>,
    mutation: ReferenceMutation<'_>,
) -> Result<(), BlobStoreError> {
    let ReferenceMutation {
        operation_id,
        mutation_digest,
        mutation_kind,
        reference,
        result_blob_id,
        applied_at,
    } = mutation;
    transaction.execute(
        r#"
        INSERT INTO chio_encrypted_blob_reference_mutations (
            operation_id, mutation_digest, mutation_kind, namespace,
            tenant_id, reference_key, result_blob_id, applied_at
        ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
        "#,
        params![
            operation_id,
            mutation_digest,
            mutation_kind,
            reference.namespace(),
            reference.tenant_id().as_str(),
            reference.reference_key().as_slice(),
            result_blob_id,
            applied_at,
        ],
    )?;
    Ok(())
}

fn blob_aad(blob_id: &str, tenant_id: &str, created_at: i64) -> Vec<u8> {
    format!("{blob_id}\0{tenant_id}\0{created_at}").into_bytes()
}

fn configure_blob_connection(connection: &mut Connection) -> rusqlite::Result<()> {
    connection.execute_batch(
        r#"
        PRAGMA foreign_keys = ON;
        PRAGMA synchronous = FULL;
        PRAGMA busy_timeout = 5000;
        "#,
    )
}

fn validate_tenant_id(tenant_id: &TenantId) -> Result<(), BlobStoreError> {
    let value = tenant_id.as_str();
    if value.trim().is_empty() {
        return Err(BlobStoreError::EmptyTenantId);
    }
    if value.trim() != value || value.chars().any(char::is_control) {
        return Err(BlobStoreError::InvalidTenantId);
    }
    Ok(())
}

fn now_secs() -> i64 {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => i64::try_from(duration.as_secs()).unwrap_or(i64::MAX),
        Err(_) => 0,
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    struct TraitProbe<T>(std::marker::PhantomData<T>);

    trait DebugAmbiguity<Marker> {
        fn assert_absent() {}
    }

    impl<T> DebugAmbiguity<()> for TraitProbe<T> {}
    impl<T: std::fmt::Debug> DebugAmbiguity<u8> for TraitProbe<T> {}

    #[test]
    fn encrypt_decrypt_round_trip() {
        let key = TenantKey::from_bytes([7; 32]);
        let plaintext = b"redacted fixture payload";
        let blob = encrypt_blob(&key, plaintext).expect("encrypt with valid key");
        assert_ne!(blob.ciphertext, plaintext);
        let decrypted = decrypt_blob(&key, &blob).expect("decrypt with correct key");
        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn decrypt_rejects_wrong_key() {
        let key = TenantKey::from_bytes([7; 32]);
        let wrong_key = TenantKey::from_bytes([8; 32]);
        let blob = encrypt_blob(&key, b"payload").expect("encrypt with valid key");
        let error = decrypt_blob(&wrong_key, &blob).expect_err("wrong key must fail");
        assert_eq!(error, DecryptError::AuthenticationFailed);
    }

    #[test]
    fn stored_blob_ciphertext_is_bound_to_handle_metadata() {
        let store = SqliteEncryptedBlobStore::open_in_memory().unwrap();
        let tenant = TenantId::new("tenant-a");
        let key = TenantKey::from_bytes([9; 32]);
        let source = store
            .write_encrypted_blob(&tenant, &key, b"source payload")
            .unwrap();
        let target = store
            .write_encrypted_blob(&tenant, &key, b"target payload")
            .unwrap();

        let conn = store.pool.get().unwrap();
        conn.execute(
            r#"
            UPDATE chio_encrypted_blobs
            SET nonce = (
                    SELECT nonce FROM chio_encrypted_blobs WHERE blob_id = ?1
                ),
                ciphertext = (
                    SELECT ciphertext FROM chio_encrypted_blobs WHERE blob_id = ?1
                )
            WHERE blob_id = ?2
            "#,
            params![source.blob_id(), target.blob_id()],
        )
        .unwrap();
        drop(conn);

        let error = store
            .read_encrypted_blob(&target, &key)
            .expect_err("transplanted ciphertext should fail metadata-bound AEAD");
        assert!(matches!(
            error,
            BlobStoreError::Decrypt(DecryptError::AuthenticationFailed)
        ));
    }

    #[test]
    fn write_rejects_padded_or_control_tenant_id_before_persistence() {
        let store = SqliteEncryptedBlobStore::open_in_memory().unwrap();
        let key = TenantKey::from_bytes([9; 32]);

        for tenant in [" tenant-a", "tenant-a ", "tenant-a\n"] {
            let error = store
                .write_encrypted_blob(&TenantId::new(tenant), &key, b"payload")
                .expect_err("malformed tenant id must fail closed");
            assert!(
                error.to_string().contains("tenant id"),
                "unexpected tenant validation error: {error}"
            );
        }

        let count: i64 = store
            .pool
            .get()
            .unwrap()
            .query_row("SELECT COUNT(*) FROM chio_encrypted_blobs", [], |row| {
                row.get(0)
            })
            .unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn store_schema_does_not_publish_plaintext_hashes() {
        let store = SqliteEncryptedBlobStore::open_in_memory().unwrap();
        let conn = store.pool.get().unwrap();
        let mut statement = conn
            .prepare("PRAGMA table_info(chio_encrypted_blobs)")
            .unwrap();
        let names = statement
            .query_map([], |row| row.get::<_, String>(1))
            .unwrap()
            .collect::<Result<Vec<_>, _>>()
            .unwrap();
        assert!(
            !names.iter().any(|name| name == "plaintext_sha256"),
            "encrypted blob store must not persist plaintext-derived hashes"
        );
    }

    #[test]
    fn tenant_key_implements_zeroize_on_drop() {
        fn assert_zod<T: ZeroizeOnDrop>() {}
        assert_zod::<TenantKey>();
    }

    #[test]
    fn tenant_key_exposes_no_debug_trait() {
        <TraitProbe<TenantKey> as DebugAmbiguity<_>>::assert_absent();
    }

    #[test]
    fn reference_write_is_atomic_and_tenant_scoped() {
        let store = SqliteEncryptedBlobStore::open_in_memory().unwrap();
        let tenant_a = TenantId::new("tenant-a");
        let tenant_b = TenantId::new("tenant-b");
        let key = TenantKey::from_bytes([9; 32]);
        let reference_a = BlobReference::new(
            "chio.secret-broker.credentials.v1",
            tenant_a.clone(),
            [1; 32],
        )
        .unwrap();
        let reference_b =
            BlobReference::new("chio.secret-broker.credentials.v1", tenant_b, [1; 32]).unwrap();

        let handle = store
            .write_encrypted_blob_with_reference(&reference_a, &key, b"first")
            .unwrap();
        assert_eq!(store.resolve_blob_reference(&reference_a).unwrap(), handle);
        assert!(store.resolve_blob_reference(&reference_b).is_err());
        assert!(store
            .pool
            .get()
            .unwrap()
            .execute(
                "DELETE FROM chio_encrypted_blobs WHERE blob_id = ?1",
                params![handle.blob_id],
            )
            .is_err());

        assert!(store
            .write_encrypted_blob_with_reference(&reference_a, &key, b"orphan")
            .is_err());
        let count: i64 = store
            .pool
            .get()
            .unwrap()
            .query_row("SELECT COUNT(*) FROM chio_encrypted_blobs", [], |row| {
                row.get(0)
            })
            .unwrap();
        assert_eq!(count, 1, "a rejected mapping must not leave an orphan blob");
    }

    #[test]
    fn reference_disable_and_delete_fail_closed() {
        let store = SqliteEncryptedBlobStore::open_in_memory().unwrap();
        let tenant = TenantId::new("tenant-a");
        let key = TenantKey::from_bytes([9; 32]);
        let reference =
            BlobReference::new("chio.secret-broker.credentials.v1", tenant, [2; 32]).unwrap();
        let handle = store
            .write_encrypted_blob_with_reference(&reference, &key, b"payload")
            .unwrap();

        store.disable_blob_reference(&reference).unwrap();
        assert!(store.resolve_blob_reference(&reference).is_err());
        assert_eq!(
            store.read_encrypted_blob(&handle, &key).unwrap(),
            b"payload",
            "disablement must retain encrypted material for audited recovery"
        );

        store.delete_blob_reference(&reference).unwrap();
        assert!(store.resolve_blob_reference(&reference).is_err());
        assert!(store.read_encrypted_blob(&handle, &key).is_err());
    }

    #[test]
    fn reference_mutations_replay_exactly_and_reject_operation_rebinding() {
        let store = SqliteEncryptedBlobStore::open_in_memory().unwrap();
        let tenant = TenantId::new("tenant-a");
        let key = TenantKey::from_bytes([9; 32]);
        let provision_reference =
            BlobReference::new("chio.secret-broker.credentials.v1", tenant.clone(), [3; 32])
                .unwrap();
        let operation_id = "11".repeat(32);
        let mutation_digest = "22".repeat(32);

        let (first_handle, first_outcome) = store
            .write_encrypted_blob_with_reference_once(
                &provision_reference,
                &key,
                b"payload",
                &operation_id,
                &mutation_digest,
            )
            .unwrap();
        let (replayed_handle, replayed_outcome) = store
            .write_encrypted_blob_with_reference_once(
                &provision_reference,
                &key,
                b"payload",
                &operation_id,
                &mutation_digest,
            )
            .unwrap();
        assert_eq!(first_handle, replayed_handle);
        assert_eq!(first_outcome, BlobReferenceMutationOutcome::Applied);
        assert_eq!(replayed_outcome, BlobReferenceMutationOutcome::Replayed);

        let rebound =
            BlobReference::new("chio.secret-broker.credentials.v1", tenant.clone(), [4; 32])
                .unwrap();
        assert!(matches!(
            store.write_encrypted_blob_with_reference_once(
                &rebound,
                &key,
                b"payload",
                &operation_id,
                &mutation_digest,
            ),
            Err(BlobStoreError::MutationConflict)
        ));

        let disable_operation = "33".repeat(32);
        let disable_digest = "44".repeat(32);
        assert_eq!(
            store
                .disable_blob_reference_once(
                    &provision_reference,
                    &disable_operation,
                    &disable_digest,
                )
                .unwrap(),
            BlobReferenceMutationOutcome::Applied
        );
        assert_eq!(
            store
                .disable_blob_reference_once(
                    &provision_reference,
                    &disable_operation,
                    &disable_digest,
                )
                .unwrap(),
            BlobReferenceMutationOutcome::Replayed
        );

        let delete_operation = "55".repeat(32);
        let delete_digest = "66".repeat(32);
        assert_eq!(
            store
                .delete_blob_reference_once(
                    &provision_reference,
                    &delete_operation,
                    &delete_digest,
                )
                .unwrap(),
            BlobReferenceMutationOutcome::Applied
        );
        assert_eq!(
            store
                .delete_blob_reference_once(
                    &provision_reference,
                    &delete_operation,
                    &delete_digest,
                )
                .unwrap(),
            BlobReferenceMutationOutcome::Replayed
        );
    }
}
