use std::fmt;

use chio_core_types::{
    canonical_json_bytes, PublicKey, Signature, SigningAlgorithm, SigningBackend,
};
use rand_core::{OsRng, RngCore};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;
use zeroize::Zeroizing;

use crate::authority_ipc::{AuthorityOperation, AuthorityResult, VerifiedAuthorityExchange};
use crate::capability::capability_digest;
use crate::proof::proof_digest;
use crate::protocol::{BrokerExecuteRequest, MAX_BODY_BYTES, MAX_WIRE_BYTES};
use crate::provision::{
    verify_governed_admin_authorization_evidence, AdminAuthorization, GovernedAdminPolicy,
};
use crate::registration::broker_execute_request_registration_digest;
use crate::revocation::{
    validate_parent_liveness, validate_revocation_snapshot, BrokerRevocationRequest,
    CanonicalBrokerRevocationSet, CapabilityLivenessRequest,
};
use crate::{validate_digest, validate_identifier, BrokerError, Result};

pub const BROKER_AUDIT_COMPARISON_SCHEMA: &str = "chio.broker-audit-comparison.v1";
pub const BROKER_AUDIT_RUNNER_AUTHORIZATION_SCHEMA: &str =
    "chio.broker-audit-runner-authorization.v1";
const BROKER_AUDIT_COMPARISON_SIGNATURE_DOMAIN: &str =
    "chio.broker-audit-comparison-signature.v1\0";
const BROKER_AUDIT_RUNNER_AUTHORIZATION_SIGNATURE_DOMAIN: &[u8] =
    b"chio.broker-audit-runner-authorization-signature.v1\0";
const BROKER_AUDIT_RUNNER_AUTHORIZATION_DIGEST_DOMAIN: &[u8] =
    b"chio.broker-audit-runner-authorization-digest.v1\0";
const BROKER_AUDIT_PROJECTION_DOMAIN: &[u8] = b"chio.broker-audit-wire-projection.v1\0";
const BROKER_AUDIT_AUTHORITY_CONTEXT_DOMAIN: &str = "chio.broker-audit-authority-context.v1\0";
const BROKER_AUDIT_TRUSTED_CONFIGURATION_DOMAIN: &[u8] =
    b"chio.broker-audit-trusted-configuration.v2\0";
const BROKER_AUDIT_GOVERNED_INTENT_SCHEMA: &str = "chio.broker-audit-intent.v1";
const BROKER_AUDIT_GOVERNED_INTENT_DOMAIN: &[u8] = b"chio.broker-audit-intent.v1\0";
const BROKER_AUDIT_REFERENCE_DIGEST_DOMAIN: &[u8] = b"chio.broker-audit-reference-request.v1\0";
const BROKER_AUDIT_REFERENCE_SOURCE_DOMAIN: &[u8] = b"chio.broker-audit-reference-source.v1\0";
const BROKER_AUDIT_ID_DOMAIN: &[u8] = b"chio.broker-audit-id.v1\0";
const MAX_AUDIT_RUNNER_AUTHORIZATION_LIFETIME_SECONDS: u64 = 300;
const MAX_AUDIT_COMPARISON_BYTES: usize = 16 * 1_024;
pub const BROKER_AUDIT_REFERENCE_COMMITMENT_SALT_BYTES: usize = 32;

/// Runner-owned commitment retained before any privileged broker connection.
///
/// The salt is generated by the audit runner and the commitment is derived
/// from the runner's original reference bytes. Private fields prevent a caller
/// from manufacturing this typed expectation by copying a digest out of a
/// broker-signed response.
pub struct BrokerAuditReferencePrecommitment {
    commitment_salt: Zeroizing<String>,
    commitment_sha256: String,
}

impl BrokerAuditReferencePrecommitment {
    pub fn generate(request_head: &[u8], request_body: &[u8]) -> Result<Self> {
        validate_reference_request_parts(request_head, request_body)?;
        let mut salt = Zeroizing::new([0_u8; BROKER_AUDIT_REFERENCE_COMMITMENT_SALT_BYTES]);
        OsRng.try_fill_bytes(&mut salt[..]).map_err(|_| {
            BrokerError::AuthorityUnavailable(
                "broker audit runner precommitment randomness is unavailable".to_string(),
            )
        })?;
        if salt.iter().all(|byte| *byte == 0) {
            return Err(BrokerError::AuthorityUnavailable(
                "broker audit runner precommitment randomness is invalid".to_string(),
            ));
        }
        let commitment_salt = Zeroizing::new(hex::encode(salt.as_slice()));
        let commitment_sha256 = broker_audit_reference_commitment_sha256(
            commitment_salt.as_str(),
            request_head,
            request_body,
        )?;
        Ok(Self {
            commitment_salt,
            commitment_sha256,
        })
    }

    #[must_use]
    pub fn commitment_salt(&self) -> &str {
        self.commitment_salt.as_str()
    }

    #[must_use]
    pub fn commitment_sha256(&self) -> &str {
        &self.commitment_sha256
    }
}

impl fmt::Debug for BrokerAuditReferencePrecommitment {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BrokerAuditReferencePrecommitment")
            .field("commitment_salt", &"<redacted>")
            .field("commitment_sha256", &self.commitment_sha256)
            .finish()
    }
}

/// Exact legacy outbound bytes admitted only into the privileged in-process
/// migration audit path. The buffers are zeroized on every return path and
/// cannot be cloned, serialized, or inspected through `Debug`.
pub struct BrokerAuditReferenceRequest {
    commitment_salt: Zeroizing<String>,
    request_head: Zeroizing<Vec<u8>>,
    request_body: Zeroizing<Vec<u8>>,
}

impl BrokerAuditReferenceRequest {
    pub fn new_with_precommitment(
        request_head: Vec<u8>,
        request_body: Vec<u8>,
    ) -> Result<(Self, BrokerAuditReferencePrecommitment)> {
        let precommitment =
            BrokerAuditReferencePrecommitment::generate(&request_head, &request_body)?;
        let reference = Self::from_precommitment(
            request_head,
            request_body,
            precommitment.commitment_salt().to_string(),
            precommitment.commitment_sha256(),
        )?;
        Ok((reference, precommitment))
    }

    pub(crate) fn from_precommitment(
        request_head: Vec<u8>,
        request_body: Vec<u8>,
        commitment_salt: String,
        expected_commitment_sha256: &str,
    ) -> Result<Self> {
        let observed_commitment_sha256 = broker_audit_reference_commitment_sha256(
            &commitment_salt,
            &request_head,
            &request_body,
        )?;
        if observed_commitment_sha256 != expected_commitment_sha256 {
            return Err(BrokerError::AuthorizationDenied(
                "broker audit reference does not match the runner precommitment".to_string(),
            ));
        }
        let reference = Self {
            commitment_salt: Zeroizing::new(commitment_salt),
            request_head: Zeroizing::new(request_head),
            request_body: Zeroizing::new(request_body),
        };
        reference.validate()?;
        Ok(reference)
    }

    pub(crate) fn validate(&self) -> Result<()> {
        validate_reference_request_parts(
            self.request_head.as_slice(),
            self.request_body.as_slice(),
        )?;
        validate_reference_commitment_salt(self.commitment_salt.as_str())
    }
}

impl fmt::Debug for BrokerAuditReferenceRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BrokerAuditReferenceRequest")
            .field("commitment_salt", &"<redacted>")
            .field("request_head", &"<redacted>")
            .field("request_body", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrokerAuditRunnerAuthorizationBody {
    pub schema: String,
    pub audit_id: String,
    pub deployment_id: String,
    pub broker_instance_id: String,
    pub tenant_scope: String,
    pub runner_id: String,
    pub reference_source: String,
    pub reference_commitment_sha256: String,
    pub capability_sha256: String,
    pub proof_sha256: String,
    pub canonical_request_sha256: String,
    pub provider_adapter_id: String,
    pub provider_adapter_version: u32,
    pub credential_provider: String,
    pub revocation_authority_domain: String,
    pub issued_at_unix_seconds: u64,
    pub expires_at_unix_seconds: u64,
}

impl BrokerAuditRunnerAuthorizationBody {
    pub fn for_request(
        request: &BrokerExecuteRequest,
        reference: &BrokerAuditReferenceRequest,
        scope: BrokerAuditRunnerScope<'_>,
        issued_at_unix_seconds: u64,
        expires_at_unix_seconds: u64,
    ) -> Result<Self> {
        reference.validate()?;
        request.validate_bounds()?;
        let body = Self {
            schema: BROKER_AUDIT_RUNNER_AUTHORIZATION_SCHEMA.to_string(),
            audit_id: scope.audit_id.to_string(),
            deployment_id: scope.deployment_id.to_string(),
            broker_instance_id: scope.broker_instance_id.to_string(),
            tenant_scope: scope.tenant_scope.to_string(),
            runner_id: scope.runner_id.to_string(),
            reference_source: scope.reference_source.to_string(),
            reference_commitment_sha256: reference_request_digest(reference)?,
            capability_sha256: capability_digest(&request.capability)?,
            proof_sha256: proof_digest(&request.proof)?,
            canonical_request_sha256: broker_execute_request_registration_digest(request)?,
            provider_adapter_id: request.capability.body.provider_adapter_id.clone(),
            provider_adapter_version: request.capability.body.provider_adapter_version,
            credential_provider: request.capability.body.credential.provider.clone(),
            revocation_authority_domain: scope.revocation_authority_domain.to_string(),
            issued_at_unix_seconds,
            expires_at_unix_seconds,
        };
        body.validate()?;
        Ok(body)
    }

    pub fn validate(&self) -> Result<()> {
        if self.schema != BROKER_AUDIT_RUNNER_AUTHORIZATION_SCHEMA
            || self.issued_at_unix_seconds == 0
            || self.expires_at_unix_seconds <= self.issued_at_unix_seconds
            || self
                .expires_at_unix_seconds
                .saturating_sub(self.issued_at_unix_seconds)
                > MAX_AUDIT_RUNNER_AUTHORIZATION_LIFETIME_SECONDS
            || self.provider_adapter_version == 0
        {
            return Err(BrokerError::InvalidRequest(
                "broker audit runner authorization schema, time, or version is invalid".to_string(),
            ));
        }
        for (value, label) in [
            (&self.audit_id, "broker audit identifier"),
            (&self.deployment_id, "broker audit deployment identifier"),
            (&self.broker_instance_id, "broker audit instance identifier"),
            (&self.tenant_scope, "broker audit tenant scope"),
            (&self.runner_id, "broker audit runner identifier"),
            (&self.reference_source, "broker audit reference source"),
            (&self.provider_adapter_id, "broker audit provider adapter"),
            (
                &self.credential_provider,
                "broker audit credential provider",
            ),
            (
                &self.revocation_authority_domain,
                "broker audit revocation authority domain",
            ),
        ] {
            validate_identifier(value, label, 512)?;
        }
        for (digest, label) in [
            (
                &self.reference_commitment_sha256,
                "broker audit reference commitment",
            ),
            (&self.capability_sha256, "broker audit capability digest"),
            (&self.proof_sha256, "broker audit proof digest"),
            (
                &self.canonical_request_sha256,
                "broker audit canonical request digest",
            ),
        ] {
            validate_digest(digest, label)?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SignedBrokerAuditRunnerAuthorization {
    pub body: BrokerAuditRunnerAuthorizationBody,
    pub signer: PublicKey,
    pub algorithm: SigningAlgorithm,
    pub signature: Signature,
}

impl SignedBrokerAuditRunnerAuthorization {
    pub fn sign(
        body: BrokerAuditRunnerAuthorizationBody,
        signer: &dyn SigningBackend,
    ) -> Result<Self> {
        body.validate()?;
        let canonical = runner_authorization_signing_bytes(&body)?;
        let outcome = signer
            .sign_bytes_with_identity(&canonical)
            .map_err(|error| {
                BrokerError::AuthorityUnavailable(format!(
                    "broker audit runner authorization signing failed: {error}"
                ))
            })?;
        if outcome.public_key.algorithm() != outcome.algorithm
            || outcome.signature.algorithm() != outcome.algorithm
            || !outcome.public_key.verify(&canonical, &outcome.signature)
        {
            return Err(BrokerError::Invariant(
                "broker audit runner signer returned invalid identity metadata".to_string(),
            ));
        }
        Ok(Self {
            body,
            signer: outcome.public_key,
            algorithm: outcome.algorithm,
            signature: outcome.signature,
        })
    }

    pub fn canonical_bytes(&self) -> Result<Vec<u8>> {
        self.verify_signature()?;
        canonical_json_bytes(self).map_err(|error| {
            BrokerError::Invariant(format!(
                "broker audit runner authorization encoding failed: {error}"
            ))
        })
    }

    pub fn from_canonical_bytes(bytes: &[u8]) -> Result<Self> {
        if bytes.is_empty() || bytes.len() > MAX_WIRE_BYTES {
            return Err(BrokerError::InvalidRequest(
                "broker audit runner authorization is empty or oversized".to_string(),
            ));
        }
        let authorization: Self = serde_json::from_slice(bytes).map_err(|error| {
            BrokerError::InvalidRequest(format!(
                "broker audit runner authorization decoding failed: {error}"
            ))
        })?;
        authorization.verify_signature()?;
        if canonical_json_bytes(&authorization).map_err(|error| {
            BrokerError::InvalidRequest(format!(
                "broker audit runner authorization encoding failed: {error}"
            ))
        })? != bytes
        {
            return Err(BrokerError::InvalidRequest(
                "broker audit runner authorization is not canonical JSON".to_string(),
            ));
        }
        Ok(authorization)
    }

    fn verify_signature(&self) -> Result<()> {
        self.body.validate()?;
        if self.signer.algorithm() != self.algorithm
            || self.signature.algorithm() != self.algorithm
            || !self.signer.verify(
                &runner_authorization_signing_bytes(&self.body)?,
                &self.signature,
            )
        {
            return Err(BrokerError::AuthorizationDenied(
                "broker audit runner authorization signature is invalid".to_string(),
            ));
        }
        Ok(())
    }
}

#[derive(Clone, Copy)]
pub struct BrokerAuditRunnerScope<'a> {
    pub audit_id: &'a str,
    pub deployment_id: &'a str,
    pub broker_instance_id: &'a str,
    pub tenant_scope: &'a str,
    pub runner_id: &'a str,
    pub reference_source: &'a str,
    pub revocation_authority_domain: &'a str,
}

#[derive(Clone, Copy)]
pub struct BrokerAuditRunnerTrust<'a> {
    pub deployment_id: &'a str,
    pub broker_instance_id: &'a str,
    pub tenant_scope: &'a str,
    pub runner_id: &'a str,
    pub trusted_runner: &'a PublicKey,
}

pub struct VerifiedBrokerAuditRunnerAuthorization {
    governed_intent_sha256: String,
    runner_authorization_sha256: String,
    audit_id_sha256: String,
    reference_source_sha256: String,
    revocation_authority_domain: String,
    deployment_id: String,
    broker_instance_id: String,
    tenant_scope: String,
    runner_id: String,
    trusted_runner: PublicKey,
}

impl VerifiedBrokerAuditRunnerAuthorization {
    #[must_use]
    pub fn governed_intent_sha256(&self) -> &str {
        &self.governed_intent_sha256
    }

    pub(crate) fn revocation_authority_domain(&self) -> &str {
        &self.revocation_authority_domain
    }

    pub(crate) fn audit_id_sha256(&self) -> &str {
        &self.audit_id_sha256
    }

    pub(crate) fn runner_authorization_sha256(&self) -> &str {
        &self.runner_authorization_sha256
    }

    pub(crate) fn reference_source_sha256(&self) -> &str {
        &self.reference_source_sha256
    }

    pub(crate) fn deployment_id(&self) -> &str {
        &self.deployment_id
    }

    pub(crate) fn broker_instance_id(&self) -> &str {
        &self.broker_instance_id
    }

    pub(crate) fn tenant_scope(&self) -> &str {
        &self.tenant_scope
    }

    pub(crate) fn runner_id(&self) -> &str {
        &self.runner_id
    }

    pub(crate) fn trusted_runner(&self) -> &PublicKey {
        &self.trusted_runner
    }
}

pub fn verify_broker_audit_runner_authorization(
    authorization: &SignedBrokerAuditRunnerAuthorization,
    request: &BrokerExecuteRequest,
    reference: &BrokerAuditReferenceRequest,
    trust: BrokerAuditRunnerTrust<'_>,
    now_unix_seconds: u64,
) -> Result<VerifiedBrokerAuditRunnerAuthorization> {
    authorization.verify_signature()?;
    reference.validate()?;
    for (value, label) in [
        (trust.deployment_id, "trusted audit deployment identifier"),
        (trust.broker_instance_id, "trusted audit broker instance"),
        (trust.tenant_scope, "trusted audit tenant scope"),
        (trust.runner_id, "trusted audit runner identifier"),
    ] {
        validate_identifier(value, label, 512)?;
    }
    let body = &authorization.body;
    if &authorization.signer != trust.trusted_runner
        || now_unix_seconds < body.issued_at_unix_seconds
        || now_unix_seconds >= body.expires_at_unix_seconds
        || body.deployment_id != trust.deployment_id
        || body.broker_instance_id != trust.broker_instance_id
        || body.tenant_scope != trust.tenant_scope
        || body.runner_id != trust.runner_id
        || body.reference_commitment_sha256 != reference_request_digest(reference)?
        || body.capability_sha256 != capability_digest(&request.capability)?
        || body.proof_sha256 != proof_digest(&request.proof)?
        || body.canonical_request_sha256 != broker_execute_request_registration_digest(request)?
        || body.provider_adapter_id != request.capability.body.provider_adapter_id
        || body.provider_adapter_version != request.capability.body.provider_adapter_version
        || body.credential_provider != request.capability.body.credential.provider
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit runner authorization is stale, untrusted, or rebound".to_string(),
        ));
    }
    let runner_authorization_sha256 = runner_authorization_digest(authorization)?;
    let governed_intent_sha256 =
        broker_audit_governed_intent_digest(body, &runner_authorization_sha256)?;
    Ok(VerifiedBrokerAuditRunnerAuthorization {
        governed_intent_sha256,
        runner_authorization_sha256,
        audit_id_sha256: broker_audit_id_digest(&body.audit_id)?,
        reference_source_sha256: broker_audit_reference_source_digest(&body.reference_source)?,
        revocation_authority_domain: body.revocation_authority_domain.clone(),
        deployment_id: body.deployment_id.clone(),
        broker_instance_id: body.broker_instance_id.clone(),
        tenant_scope: body.tenant_scope.clone(),
        runner_id: body.runner_id.clone(),
        trusted_runner: trust.trusted_runner.clone(),
    })
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct BrokerAuditComparisonBody {
    pub schema: String,
    pub issued_at_unix_seconds: u64,
    pub capability_sha256: String,
    pub proof_sha256: String,
    pub canonical_request_sha256: String,
    pub authority_context_sha256: String,
    pub audit_id_sha256: String,
    pub governed_audit_intent_sha256: String,
    pub audit_authorization_sha256: String,
    pub runner_authorization_sha256: String,
    pub reference_source_sha256: String,
    pub broker_outbound_projection_commitment_sha256: String,
    pub reference_outbound_projection_commitment_sha256: String,
    pub projections_equal: bool,
    pub network_dispatch_count: u8,
    pub accounting_mutation_count: u8,
    pub raw_credential_returned: bool,
}

impl BrokerAuditComparisonBody {
    pub fn validate(&self) -> Result<()> {
        if self.schema != BROKER_AUDIT_COMPARISON_SCHEMA || self.issued_at_unix_seconds == 0 {
            return Err(BrokerError::InvalidRequest(
                "broker audit comparison schema or issue time is invalid".to_string(),
            ));
        }
        for (digest, label) in [
            (&self.capability_sha256, "audit capability digest"),
            (&self.proof_sha256, "audit proof digest"),
            (
                &self.canonical_request_sha256,
                "audit canonical request digest",
            ),
            (
                &self.authority_context_sha256,
                "audit authority context digest",
            ),
            (&self.audit_id_sha256, "audit identifier digest"),
            (
                &self.governed_audit_intent_sha256,
                "governed audit intent digest",
            ),
            (
                &self.audit_authorization_sha256,
                "audit authorization digest",
            ),
            (
                &self.runner_authorization_sha256,
                "audit runner authorization digest",
            ),
            (
                &self.reference_source_sha256,
                "audit reference source digest",
            ),
            (
                &self.broker_outbound_projection_commitment_sha256,
                "audit broker projection digest",
            ),
            (
                &self.reference_outbound_projection_commitment_sha256,
                "audit reference projection digest",
            ),
        ] {
            validate_digest(digest, label)?;
        }
        if self.projections_equal
            != (self.broker_outbound_projection_commitment_sha256
                == self.reference_outbound_projection_commitment_sha256)
            || self.network_dispatch_count != 0
            || self.accounting_mutation_count != 0
            || self.raw_credential_returned
        {
            return Err(BrokerError::InvalidRequest(
                "broker audit comparison safety claims are inconsistent".to_string(),
            ));
        }
        Ok(())
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct BrokerAuditGovernedIntent<'a> {
    schema: &'static str,
    audit_id: &'a str,
    runner_authorization_sha256: &'a str,
}

/// Compute the exact governed intent that operators approve for one audit
/// comparison. The digest binds the live request, the secret-bearing reference,
/// its provenance label, and the authority domain without exposing reference
/// bytes in the signed comparison artifact.
fn broker_audit_governed_intent_digest(
    runner: &BrokerAuditRunnerAuthorizationBody,
    runner_authorization_sha256: &str,
) -> Result<String> {
    runner.validate()?;
    validate_digest(
        runner_authorization_sha256,
        "broker audit runner authorization digest",
    )?;
    let canonical = canonical_json_bytes(&BrokerAuditGovernedIntent {
        schema: BROKER_AUDIT_GOVERNED_INTENT_SCHEMA,
        audit_id: &runner.audit_id,
        runner_authorization_sha256,
    })
    .map_err(|error| {
        BrokerError::Invariant(format!("broker audit intent encoding failed: {error}"))
    })?;
    let mut hasher = Sha256::new();
    hasher.update(BROKER_AUDIT_GOVERNED_INTENT_DOMAIN);
    hasher.update(canonical);
    Ok(hex::encode(hasher.finalize()))
}

fn runner_authorization_signing_bytes(
    body: &BrokerAuditRunnerAuthorizationBody,
) -> Result<Vec<u8>> {
    body.validate()?;
    let canonical = canonical_json_bytes(body).map_err(|error| {
        BrokerError::Invariant(format!(
            "broker audit runner authorization body encoding failed: {error}"
        ))
    })?;
    let mut signing = Vec::with_capacity(
        BROKER_AUDIT_RUNNER_AUTHORIZATION_SIGNATURE_DOMAIN.len() + canonical.len(),
    );
    signing.extend_from_slice(BROKER_AUDIT_RUNNER_AUTHORIZATION_SIGNATURE_DOMAIN);
    signing.extend_from_slice(&canonical);
    Ok(signing)
}

fn runner_authorization_digest(
    authorization: &SignedBrokerAuditRunnerAuthorization,
) -> Result<String> {
    authorization.verify_signature()?;
    let canonical = canonical_json_bytes(authorization).map_err(|error| {
        BrokerError::Invariant(format!(
            "broker audit runner authorization digest encoding failed: {error}"
        ))
    })?;
    let mut hasher = Sha256::new();
    hasher.update(BROKER_AUDIT_RUNNER_AUTHORIZATION_DIGEST_DOMAIN);
    hasher.update(canonical);
    Ok(hex::encode(hasher.finalize()))
}

/// Compute the exact governed intent that threshold operators must approve for
/// one self-signed runner authorization.
pub fn broker_audit_governed_intent_for_runner_authorization(
    authorization: &SignedBrokerAuditRunnerAuthorization,
) -> Result<String> {
    let runner_authorization_sha256 = runner_authorization_digest(authorization)?;
    broker_audit_governed_intent_digest(&authorization.body, &runner_authorization_sha256)
}

pub(crate) fn broker_audit_id_digest(audit_id: &str) -> Result<String> {
    validate_identifier(audit_id, "broker audit identifier", 512)?;
    let mut hasher = Sha256::new();
    hasher.update(BROKER_AUDIT_ID_DOMAIN);
    hasher.update(audit_id.as_bytes());
    Ok(hex::encode(hasher.finalize()))
}

pub(crate) fn broker_audit_reference_source_digest(reference_source: &str) -> Result<String> {
    validate_identifier(reference_source, "audit reference source", 512)?;
    let mut hasher = Sha256::new();
    hasher.update(BROKER_AUDIT_REFERENCE_SOURCE_DOMAIN);
    hasher.update(reference_source.as_bytes());
    Ok(hex::encode(hasher.finalize()))
}

fn validate_reference_request_parts(request_head: &[u8], request_body: &[u8]) -> Result<()> {
    if request_head.is_empty()
        || request_head.len() > MAX_WIRE_BYTES
        || !request_head.ends_with(b"\r\n\r\n")
        || request_body.len() > MAX_BODY_BYTES
    {
        return Err(BrokerError::InvalidRequest(
            "broker audit reference request is malformed or oversized".to_string(),
        ));
    }
    Ok(())
}

fn validate_reference_commitment_salt(commitment_salt: &str) -> Result<()> {
    validate_digest(
        commitment_salt,
        "broker audit runner reference commitment salt",
    )?;
    if commitment_salt.bytes().all(|byte| byte == b'0') {
        return Err(BrokerError::InvalidRequest(
            "broker audit runner reference commitment salt is all zero".to_string(),
        ));
    }
    Ok(())
}

/// Derive the blinded reference commitment from runner-owned inputs.
///
/// Audit runners call this before connecting to the broker and retain the
/// typed [`BrokerAuditReferencePrecommitment`] through evidence verification.
pub fn broker_audit_reference_commitment_sha256(
    commitment_salt: &str,
    request_head: &[u8],
    request_body: &[u8],
) -> Result<String> {
    validate_reference_request_parts(request_head, request_body)?;
    validate_reference_commitment_salt(commitment_salt)?;
    let salt = Zeroizing::new(hex::decode(commitment_salt).map_err(|_| {
        BrokerError::InvalidRequest(
            "broker audit runner reference commitment salt is invalid".to_string(),
        )
    })?);
    if salt.len() != BROKER_AUDIT_REFERENCE_COMMITMENT_SALT_BYTES {
        return Err(BrokerError::InvalidRequest(
            "broker audit runner reference commitment salt has the wrong length".to_string(),
        ));
    }
    let head_len = u64::try_from(request_head.len()).map_err(|_| {
        BrokerError::InvalidRequest("audit reference head length overflow".to_string())
    })?;
    let body_len = u64::try_from(request_body.len()).map_err(|_| {
        BrokerError::InvalidRequest("audit reference body length overflow".to_string())
    })?;
    let mut hasher = Sha256::new();
    hasher.update(BROKER_AUDIT_REFERENCE_DIGEST_DOMAIN);
    hasher.update(salt.as_slice());
    hasher.update(head_len.to_be_bytes());
    hasher.update(request_head);
    hasher.update(body_len.to_be_bytes());
    hasher.update(request_body);
    Ok(hex::encode(hasher.finalize()))
}

fn reference_request_digest(reference: &BrokerAuditReferenceRequest) -> Result<String> {
    broker_audit_reference_commitment_sha256(
        reference.commitment_salt.as_str(),
        reference.request_head.as_slice(),
        reference.request_body.as_slice(),
    )
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SignedBrokerAuditComparison {
    pub body: BrokerAuditComparisonBody,
    pub signer: PublicKey,
    pub algorithm: SigningAlgorithm,
    pub signature: Signature,
}

impl SignedBrokerAuditComparison {
    pub fn canonical_bytes(&self) -> Result<Vec<u8>> {
        self.verify_signature()?;
        let canonical = canonical_json_bytes(self).map_err(|error| {
            BrokerError::Invariant(format!(
                "broker audit comparison canonical encoding failed: {error}"
            ))
        })?;
        if canonical.len() > MAX_AUDIT_COMPARISON_BYTES {
            return Err(BrokerError::InvalidRequest(
                "broker audit comparison exceeds its canonical wire limit".to_string(),
            ));
        }
        Ok(canonical)
    }

    pub fn from_canonical_bytes(bytes: &[u8]) -> Result<Self> {
        if bytes.is_empty() || bytes.len() > MAX_AUDIT_COMPARISON_BYTES {
            return Err(BrokerError::InvalidRequest(
                "broker audit comparison is empty or oversized".to_string(),
            ));
        }
        let comparison: Self = serde_json::from_slice(bytes).map_err(|error| {
            BrokerError::InvalidRequest(format!("broker audit comparison decoding failed: {error}"))
        })?;
        comparison.verify_signature()?;
        if canonical_json_bytes(&comparison).map_err(|error| {
            BrokerError::InvalidRequest(format!(
                "broker audit comparison canonicalization failed: {error}"
            ))
        })? != bytes
        {
            return Err(BrokerError::InvalidRequest(
                "broker audit comparison is not canonical JSON".to_string(),
            ));
        }
        Ok(comparison)
    }

    fn verify_signature(&self) -> Result<()> {
        verify_broker_audit_comparison(self, &self.signer)
    }
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct BrokerAuditComparisonSigningInput<'a> {
    domain: &'static str,
    body: &'a BrokerAuditComparisonBody,
}

pub fn sign_broker_audit_comparison(
    body: BrokerAuditComparisonBody,
    signer: &dyn SigningBackend,
) -> Result<SignedBrokerAuditComparison> {
    body.validate()?;
    let signing = BrokerAuditComparisonSigningInput {
        domain: BROKER_AUDIT_COMPARISON_SIGNATURE_DOMAIN,
        body: &body,
    };
    let canonical = canonical_json_bytes(&signing).map_err(|error| {
        BrokerError::Invariant(format!(
            "broker audit comparison signing input encoding failed: {error}"
        ))
    })?;
    let signed = signer
        .sign_bytes_with_identity(&canonical)
        .map_err(|error| {
            BrokerError::Invariant(format!("broker audit comparison signing failed: {error}"))
        })?;
    if signed.public_key.algorithm() != signed.algorithm
        || signed.signature.algorithm() != signed.algorithm
        || !signed.public_key.verify(&canonical, &signed.signature)
    {
        return Err(BrokerError::Invariant(
            "broker audit comparison signer returned a mismatched identity or signature"
                .to_string(),
        ));
    }
    Ok(SignedBrokerAuditComparison {
        body,
        signer: signed.public_key,
        algorithm: signed.algorithm,
        signature: signed.signature,
    })
}

pub fn verify_broker_audit_comparison(
    comparison: &SignedBrokerAuditComparison,
    trusted_signer: &PublicKey,
) -> Result<()> {
    comparison.body.validate().map_err(|error| {
        BrokerError::AuthorizationDenied(format!(
            "broker audit comparison body is invalid: {error}"
        ))
    })?;
    if &comparison.signer != trusted_signer
        || comparison.signer.algorithm() != comparison.algorithm
        || comparison.signature.algorithm() != comparison.algorithm
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit comparison signer or algorithm is invalid".to_string(),
        ));
    }
    let signing = BrokerAuditComparisonSigningInput {
        domain: BROKER_AUDIT_COMPARISON_SIGNATURE_DOMAIN,
        body: &comparison.body,
    };
    if !comparison
        .signer
        .verify_canonical(&signing, &comparison.signature)
        .map_err(|error| {
            BrokerError::AuthorizationDenied(format!(
                "broker audit comparison verification failed: {error}"
            ))
        })?
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit comparison signature is invalid".to_string(),
        ));
    }
    Ok(())
}

#[derive(Clone, Copy)]
pub struct BrokerAuditTrustConfiguration<'a> {
    pub trusted_capability_issuer: &'a PublicKey,
    pub broker_audience: &'a str,
    pub parent_audience: &'a str,
    pub provider_adapter_id: &'a str,
    pub provider_adapter_version: u32,
    pub receipt_signer: &'a PublicKey,
    pub maximum_clock_skew_seconds: u64,
    pub maximum_liveness_snapshot_age_seconds: u64,
    pub maximum_revocation_snapshot_age_seconds: u64,
    pub trusted_authority: &'a PublicKey,
    pub deployment_id: &'a str,
    pub broker_instance_id: &'a str,
    pub tenant_scope: &'a str,
    pub runner_id: &'a str,
    pub trusted_runner: &'a PublicKey,
    pub governed_admin_policy: &'a GovernedAdminPolicy,
}

impl BrokerAuditTrustConfiguration<'_> {
    fn validate(&self) -> Result<()> {
        for (value, label) in [
            (self.broker_audience, "audit broker audience"),
            (self.parent_audience, "audit parent audience"),
            (self.provider_adapter_id, "audit provider adapter"),
            (self.deployment_id, "audit deployment identifier"),
            (self.broker_instance_id, "audit broker instance"),
            (self.tenant_scope, "audit tenant scope"),
            (self.runner_id, "audit runner identifier"),
        ] {
            validate_identifier(value, label, 512)?;
        }
        if self.provider_adapter_version == 0
            || self.maximum_clock_skew_seconds > 60
            || self.maximum_liveness_snapshot_age_seconds == 0
            || self.maximum_liveness_snapshot_age_seconds > 60
            || self.maximum_revocation_snapshot_age_seconds == 0
            || self.maximum_revocation_snapshot_age_seconds > 60
        {
            return Err(BrokerError::InvalidRequest(
                "broker audit trust configuration bounds are invalid".to_string(),
            ));
        }
        self.governed_admin_policy.validate_for_runtime()
    }

    pub fn digest(&self) -> Result<String> {
        self.validate()?;
        let mut trusted_approvers = self.governed_admin_policy.trusted_approvers.clone();
        trusted_approvers.sort_unstable_by_key(PublicKey::to_hex);

        #[derive(Serialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct CanonicalAdminPolicy<'a> {
            trusted_approvers: &'a [PublicKey],
            subject: &'a PublicKey,
            threshold: usize,
            maximum_token_lifetime_seconds: u64,
        }

        #[derive(Serialize)]
        #[serde(rename_all = "camelCase", deny_unknown_fields)]
        struct CanonicalTrustConfiguration<'a> {
            trusted_capability_issuer: &'a PublicKey,
            broker_audience: &'a str,
            parent_audience: &'a str,
            provider_adapter_id: &'a str,
            provider_adapter_version: u32,
            receipt_signer: &'a PublicKey,
            maximum_clock_skew_seconds: u64,
            maximum_liveness_snapshot_age_seconds: u64,
            maximum_revocation_snapshot_age_seconds: u64,
            trusted_authority: &'a PublicKey,
            deployment_id: &'a str,
            broker_instance_id: &'a str,
            tenant_scope: &'a str,
            runner_id: &'a str,
            trusted_runner: &'a PublicKey,
            governed_admin_policy: CanonicalAdminPolicy<'a>,
        }

        let canonical = canonical_json_bytes(&CanonicalTrustConfiguration {
            trusted_capability_issuer: self.trusted_capability_issuer,
            broker_audience: self.broker_audience,
            parent_audience: self.parent_audience,
            provider_adapter_id: self.provider_adapter_id,
            provider_adapter_version: self.provider_adapter_version,
            receipt_signer: self.receipt_signer,
            maximum_clock_skew_seconds: self.maximum_clock_skew_seconds,
            maximum_liveness_snapshot_age_seconds: self.maximum_liveness_snapshot_age_seconds,
            maximum_revocation_snapshot_age_seconds: self.maximum_revocation_snapshot_age_seconds,
            trusted_authority: self.trusted_authority,
            deployment_id: self.deployment_id,
            broker_instance_id: self.broker_instance_id,
            tenant_scope: self.tenant_scope,
            runner_id: self.runner_id,
            trusted_runner: self.trusted_runner,
            governed_admin_policy: CanonicalAdminPolicy {
                trusted_approvers: &trusted_approvers,
                subject: &self.governed_admin_policy.subject,
                threshold: self.governed_admin_policy.threshold,
                maximum_token_lifetime_seconds: self
                    .governed_admin_policy
                    .maximum_token_lifetime_seconds,
            },
        })
        .map_err(|error| {
            BrokerError::Invariant(format!(
                "broker audit trust configuration encoding failed: {error}"
            ))
        })?;
        let mut hasher = Sha256::new();
        hasher.update(BROKER_AUDIT_TRUSTED_CONFIGURATION_DOMAIN);
        hasher.update(canonical);
        Ok(hex::encode(hasher.finalize()))
    }
}

#[derive(Clone, Copy)]
pub struct BrokerAuditAuthorityEvidence<'a> {
    pub liveness: &'a VerifiedAuthorityExchange,
    pub revocation: &'a VerifiedAuthorityExchange,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompletedBrokerAuditComparison {
    pub comparison: SignedBrokerAuditComparison,
    pub liveness_authority_exchange: VerifiedAuthorityExchange,
    pub revocation_authority_exchange: VerifiedAuthorityExchange,
}

impl CompletedBrokerAuditComparison {
    #[must_use]
    pub fn authority_evidence(&self) -> BrokerAuditAuthorityEvidence<'_> {
        BrokerAuditAuthorityEvidence {
            liveness: &self.liveness_authority_exchange,
            revocation: &self.revocation_authority_exchange,
        }
    }
}

impl std::ops::Deref for CompletedBrokerAuditComparison {
    type Target = SignedBrokerAuditComparison;

    fn deref(&self) -> &Self::Target {
        &self.comparison
    }
}

pub struct BrokerAuditEvidenceBundle<'a> {
    pub comparison: &'a SignedBrokerAuditComparison,
    pub runner_authorization: &'a SignedBrokerAuditRunnerAuthorization,
    pub admin_authorization: &'a AdminAuthorization,
    pub authority: BrokerAuditAuthorityEvidence<'a>,
}

pub struct BrokerAuditExpectedContext<'a> {
    pub request: &'a BrokerExecuteRequest,
    pub audit_id: &'a str,
    pub reference_source: &'a str,
    pub reference_precommitment: &'a BrokerAuditReferencePrecommitment,
    pub revocation_authority_domain: &'a str,
    pub trust: BrokerAuditTrustConfiguration<'a>,
    pub not_before_unix_seconds: u64,
    pub expires_at_unix_seconds: u64,
}

/// Verify every public link in one audit comparison from independently trusted
/// typed evidence. No body digest is accepted as its own expected value.
pub fn verify_broker_audit_evidence(
    bundle: BrokerAuditEvidenceBundle<'_>,
    expected: BrokerAuditExpectedContext<'_>,
) -> Result<()> {
    expected.trust.validate()?;
    validate_identifier(expected.audit_id, "expected audit identifier", 512)?;
    validate_identifier(
        expected.reference_source,
        "expected audit reference source",
        512,
    )?;
    validate_digest(
        expected.reference_precommitment.commitment_sha256(),
        "expected audit reference commitment",
    )?;
    validate_identifier(
        expected.revocation_authority_domain,
        "expected audit revocation authority domain",
        512,
    )?;
    if expected.not_before_unix_seconds == 0
        || expected.expires_at_unix_seconds <= expected.not_before_unix_seconds
        || bundle.comparison.body.issued_at_unix_seconds < expected.not_before_unix_seconds
        || bundle.comparison.body.issued_at_unix_seconds >= expected.expires_at_unix_seconds
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit comparison is outside the expected evidence interval".to_string(),
        ));
    }
    verify_broker_audit_comparison(bundle.comparison, expected.trust.receipt_signer)?;
    crate::capability::verify_capability(
        &expected.request.capability,
        expected.trust.trusted_capability_issuer,
        expected.trust.broker_audience,
        bundle.comparison.body.issued_at_unix_seconds,
        true,
    )?;
    crate::proof::verify_request_proof(
        &expected.request.proof,
        &expected.request.capability,
        &expected.request.request,
        bundle.comparison.body.issued_at_unix_seconds,
        expected.trust.maximum_clock_skew_seconds,
    )?;
    if expected.request.capability.body.provider_adapter_id != expected.trust.provider_adapter_id
        || expected.request.capability.body.provider_adapter_version
            != expected.trust.provider_adapter_version
        || expected.request.request.destination != expected.request.capability.body.destination
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit request does not match the trusted provider configuration".to_string(),
        ));
    }

    let runner_body = &bundle.runner_authorization.body;
    bundle.runner_authorization.verify_signature()?;
    if &bundle.runner_authorization.signer != expected.trust.trusted_runner
        || runner_body.audit_id != expected.audit_id
        || runner_body.deployment_id != expected.trust.deployment_id
        || runner_body.broker_instance_id != expected.trust.broker_instance_id
        || runner_body.tenant_scope != expected.trust.tenant_scope
        || runner_body.runner_id != expected.trust.runner_id
        || runner_body.reference_source != expected.reference_source
        || runner_body.reference_commitment_sha256
            != expected.reference_precommitment.commitment_sha256()
        || runner_body.revocation_authority_domain != expected.revocation_authority_domain
        || runner_body.provider_adapter_id != expected.trust.provider_adapter_id
        || runner_body.provider_adapter_version != expected.trust.provider_adapter_version
        || runner_body.credential_provider != expected.request.capability.body.credential.provider
        || runner_body.capability_sha256 != capability_digest(&expected.request.capability)?
        || runner_body.proof_sha256 != proof_digest(&expected.request.proof)?
        || runner_body.canonical_request_sha256
            != broker_execute_request_registration_digest(expected.request)?
        || bundle.comparison.body.issued_at_unix_seconds < runner_body.issued_at_unix_seconds
        || bundle.comparison.body.issued_at_unix_seconds >= runner_body.expires_at_unix_seconds
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit runner evidence does not match the expected context".to_string(),
        ));
    }

    let runner_authorization_sha256 = runner_authorization_digest(bundle.runner_authorization)?;
    let governed_audit_intent_sha256 =
        broker_audit_governed_intent_digest(runner_body, &runner_authorization_sha256)?;
    let audit_authorization_sha256 = verify_governed_admin_authorization_evidence(
        bundle.admin_authorization,
        &governed_audit_intent_sha256,
        expected.trust.governed_admin_policy,
        bundle.comparison.body.issued_at_unix_seconds,
    )?;
    let authority_context_sha256 = broker_audit_authority_context_digest(
        expected.request,
        bundle.authority,
        expected.trust,
        expected.revocation_authority_domain,
        bundle.comparison.body.issued_at_unix_seconds,
    )?;

    if bundle.comparison.body.capability_sha256 != capability_digest(&expected.request.capability)?
        || bundle.comparison.body.proof_sha256 != proof_digest(&expected.request.proof)?
        || bundle.comparison.body.canonical_request_sha256
            != broker_execute_request_registration_digest(expected.request)?
        || bundle.comparison.body.authority_context_sha256 != authority_context_sha256
        || bundle.comparison.body.audit_id_sha256 != broker_audit_id_digest(expected.audit_id)?
        || bundle.comparison.body.governed_audit_intent_sha256 != governed_audit_intent_sha256
        || bundle.comparison.body.audit_authorization_sha256 != audit_authorization_sha256
        || bundle.comparison.body.runner_authorization_sha256 != runner_authorization_sha256
        || bundle.comparison.body.reference_source_sha256
            != broker_audit_reference_source_digest(expected.reference_source)?
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit comparison does not bind the independently verified evidence".to_string(),
        ));
    }
    Ok(())
}

pub(crate) struct BrokerAuditWireComparison {
    pub(crate) broker_projection_commitment_sha256: String,
    pub(crate) reference_projection_commitment_sha256: String,
    pub(crate) projections_equal: bool,
}

pub(crate) struct BrokerAuditComparisonSalt(Zeroizing<[u8; 32]>);

impl BrokerAuditComparisonSalt {
    pub(crate) fn generate() -> Result<Self> {
        let mut salt = Zeroizing::new([0_u8; 32]);
        OsRng.try_fill_bytes(&mut salt[..]).map_err(|_| {
            BrokerError::AuthorityUnavailable(
                "broker audit comparison randomness is unavailable".to_string(),
            )
        })?;
        if salt.iter().all(|byte| *byte == 0) {
            return Err(BrokerError::AuthorityUnavailable(
                "broker audit comparison randomness is invalid".to_string(),
            ));
        }
        Ok(Self(salt))
    }

    fn as_bytes(&self) -> &[u8] {
        &self.0[..]
    }
}

pub(crate) fn compare_audit_wire_requests(
    comparison_salt: &BrokerAuditComparisonSalt,
    broker_request_head: &[u8],
    broker_request_body: &[u8],
    reference: BrokerAuditReferenceRequest,
) -> Result<BrokerAuditWireComparison> {
    reference.validate()?;
    if broker_request_head.is_empty()
        || broker_request_head.len() > MAX_WIRE_BYTES
        || !broker_request_head.ends_with(b"\r\n\r\n")
        || broker_request_body.len() > MAX_BODY_BYTES
    {
        return Err(BrokerError::Invariant(
            "prepared broker audit request is malformed or oversized".to_string(),
        ));
    }
    let broker_tag = audit_projection_commitment(
        comparison_salt.as_bytes(),
        broker_request_head,
        broker_request_body,
    )?;
    let reference_tag = audit_projection_commitment(
        comparison_salt.as_bytes(),
        &reference.request_head,
        &reference.request_body,
    )?;
    let projections_equal = bool::from(
        broker_request_head.ct_eq(reference.request_head.as_slice())
            & broker_request_body.ct_eq(reference.request_body.as_slice()),
    );
    Ok(BrokerAuditWireComparison {
        broker_projection_commitment_sha256: hex::encode(broker_tag),
        reference_projection_commitment_sha256: hex::encode(reference_tag),
        projections_equal,
    })
}

pub fn broker_audit_authority_context_digest(
    request: &BrokerExecuteRequest,
    authority: BrokerAuditAuthorityEvidence<'_>,
    trust: BrokerAuditTrustConfiguration<'_>,
    revocation_authority_domain: &str,
    validated_at_unix_seconds: u64,
) -> Result<String> {
    request.validate_bounds()?;
    trust.validate()?;
    validate_identifier(
        revocation_authority_domain,
        "audit revocation authority domain",
        512,
    )?;
    if validated_at_unix_seconds == 0 {
        return Err(BrokerError::InvalidRequest(
            "audit authority validation time is invalid".to_string(),
        ));
    }

    for exchange in [authority.liveness, authority.revocation] {
        if exchange.trusted_authority() != trust.trusted_authority {
            return Err(BrokerError::AuthorizationDenied(
                "broker audit authority evidence uses an unexpected trust root".to_string(),
            ));
        }
        crate::authority_ipc::verify_authority_exchange(
            exchange.request().clone(),
            exchange.response().clone(),
            trust.trusted_authority,
            validated_at_unix_seconds,
            trust.maximum_clock_skew_seconds,
        )?;
    }

    let liveness_request = CapabilityLivenessRequest {
        parent_capability_id: request.capability.body.parent_capability_id.clone(),
        expected_subject: request.capability.body.subject.clone(),
        expected_audience: trust.parent_audience.to_string(),
        now_unix_seconds: validated_at_unix_seconds,
    };
    if authority.liveness.request().body.operation
        != AuthorityOperation::VerifyLiveParent(liveness_request.clone())
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit liveness evidence is bound to another request".to_string(),
        ));
    }
    let AuthorityResult::LiveParent(live_parent) = &authority.liveness.response().body.result
    else {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit liveness evidence has the wrong result".to_string(),
        ));
    };
    validate_parent_liveness(
        &liveness_request,
        live_parent,
        trust.maximum_liveness_snapshot_age_seconds,
    )?;

    let revocation_request = BrokerRevocationRequest {
        broker_capability_id: request.capability.body.capability_id.clone(),
        revocation_id: request.capability.body.revocation_id.clone(),
        now_unix_seconds: validated_at_unix_seconds,
    };
    if authority.revocation.request().body.operation
        != AuthorityOperation::CheckBrokerRevocation(revocation_request.clone())
    {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit revocation evidence is bound to another request".to_string(),
        ));
    }
    let AuthorityResult::Revocation(revocation_snapshot) =
        &authority.revocation.response().body.result
    else {
        return Err(BrokerError::AuthorizationDenied(
            "broker audit revocation evidence has the wrong result".to_string(),
        ));
    };
    validate_revocation_snapshot(
        revocation_snapshot,
        validated_at_unix_seconds,
        trust.maximum_revocation_snapshot_age_seconds,
        revocation_authority_domain,
    )?;
    let revocation_set = CanonicalBrokerRevocationSet::new(
        &request.capability.body.parent_capability_id,
        &live_parent.delegation_ancestor_ids,
        &request.capability.body.capability_id,
        &request.capability.body.revocation_id,
    )?;
    let trusted_configuration_sha256 = trust.digest()?;
    let liveness_authority_request_sha256 = authority.liveness.request_sha256()?;
    let liveness_authority_response_sha256 = authority.liveness.response_sha256()?;
    let revocation_authority_request_sha256 = authority.revocation.request_sha256()?;
    let revocation_authority_response_sha256 = authority.revocation.response_sha256()?;

    #[derive(Serialize)]
    #[serde(rename_all = "camelCase", deny_unknown_fields)]
    struct AuthorityContext<'a> {
        domain: &'static str,
        revocation_authority_domain: &'a str,
        revocation_set_sha256: &'a str,
        live_parent: &'a crate::revocation::LiveParentCapability,
        revocation_snapshot: &'a crate::revocation::BrokerRevocationSnapshot,
        trusted_authority: &'a PublicKey,
        liveness_authority_request_sha256: &'a str,
        liveness_authority_response_sha256: &'a str,
        revocation_authority_request_sha256: &'a str,
        revocation_authority_response_sha256: &'a str,
        trusted_configuration_sha256: &'a str,
        validated_at_unix_seconds: u64,
    }
    let canonical = canonical_json_bytes(&AuthorityContext {
        domain: BROKER_AUDIT_AUTHORITY_CONTEXT_DOMAIN,
        revocation_authority_domain,
        revocation_set_sha256: revocation_set.digest(),
        live_parent,
        revocation_snapshot,
        trusted_authority: trust.trusted_authority,
        liveness_authority_request_sha256: &liveness_authority_request_sha256,
        liveness_authority_response_sha256: &liveness_authority_response_sha256,
        revocation_authority_request_sha256: &revocation_authority_request_sha256,
        revocation_authority_response_sha256: &revocation_authority_response_sha256,
        trusted_configuration_sha256: &trusted_configuration_sha256,
        validated_at_unix_seconds,
    })
    .map_err(|error| {
        BrokerError::Invariant(format!(
            "broker audit authority context encoding failed: {error}"
        ))
    })?;
    Ok(hex::encode(Sha256::digest(canonical)))
}

fn audit_projection_commitment(
    salt: &[u8],
    request_head: &[u8],
    request_body: &[u8],
) -> Result<[u8; 32]> {
    let request_head_len = u64::try_from(request_head.len()).map_err(|_| {
        BrokerError::InvalidRequest("broker audit request head length overflow".to_string())
    })?;
    let request_body_len = u64::try_from(request_body.len()).map_err(|_| {
        BrokerError::InvalidRequest("broker audit request body length overflow".to_string())
    })?;
    if salt.len() != 32 || salt.iter().all(|byte| *byte == 0) {
        return Err(BrokerError::Invariant(
            "broker audit comparison salt is invalid".to_string(),
        ));
    }
    let mut hasher = Sha256::new();
    hasher.update(BROKER_AUDIT_PROJECTION_DOMAIN);
    hasher.update(request_head_len.to_be_bytes());
    hasher.update(request_head);
    hasher.update(request_body_len.to_be_bytes());
    hasher.update(request_body);
    hasher.update(salt);
    hasher.update([0_u8; 64]);
    Ok(hasher.finalize().into())
}

#[cfg(test)]
mod tests {
    use chio_test_support::prelude::*;

    use super::*;

    struct TraitProbe<T>(std::marker::PhantomData<T>);

    trait DebugAmbiguity<Marker> {
        fn assert_absent() {}
    }

    impl<T> DebugAmbiguity<()> for TraitProbe<T> {}
    impl<T: std::fmt::Debug> DebugAmbiguity<u8> for TraitProbe<T> {}

    trait CloneAmbiguity<Marker> {
        fn assert_absent() {}
    }

    impl<T> CloneAmbiguity<()> for TraitProbe<T> {}
    impl<T: Clone> CloneAmbiguity<u8> for TraitProbe<T> {}

    trait SerializeAmbiguity<Marker> {
        fn assert_absent() {}
    }

    impl<T> SerializeAmbiguity<()> for TraitProbe<T> {}
    impl<T: serde::Serialize> SerializeAmbiguity<u8> for TraitProbe<T> {}

    #[test]
    fn secret_bearing_audit_inputs_expose_no_clone_or_serialize_path() {
        <TraitProbe<BrokerAuditReferencePrecommitment> as CloneAmbiguity<_>>::assert_absent();
        <TraitProbe<BrokerAuditReferencePrecommitment> as SerializeAmbiguity<_>>::assert_absent();
        <TraitProbe<BrokerAuditReferenceRequest> as CloneAmbiguity<_>>::assert_absent();
        <TraitProbe<BrokerAuditReferenceRequest> as SerializeAmbiguity<_>>::assert_absent();
        <TraitProbe<BrokerAuditComparisonSalt> as DebugAmbiguity<_>>::assert_absent();
        <TraitProbe<BrokerAuditComparisonSalt> as CloneAmbiguity<_>>::assert_absent();
        <TraitProbe<BrokerAuditComparisonSalt> as SerializeAmbiguity<_>>::assert_absent();
    }

    #[test]
    fn runner_reference_precommitment_derivation_matches_the_public_wire_vector() {
        let salt = "4444444444444444444444444444444444444444444444444444444444444444";
        let request_head = b"POST /v1 HTTP/1.1\r\nHost: example.com\r\n\r\n";
        let request_body = b"production-body";
        let commitment = broker_audit_reference_commitment_sha256(salt, request_head, request_body)
            .test_expect("derive runner reference commitment");
        assert_eq!(
            commitment,
            "7dfb74e7ee0beefc73c04f8cb38aef03918d5bbc35d5675e00cbb39573405001"
        );

        let mut rebound_body = request_body.to_vec();
        rebound_body.push(b'!');
        assert_ne!(
            broker_audit_reference_commitment_sha256(salt, request_head, &rebound_body)
                .test_expect("derive rebound runner reference commitment"),
            commitment
        );
        assert!(broker_audit_reference_commitment_sha256(
            "0000000000000000000000000000000000000000000000000000000000000000",
            request_head,
            request_body,
        )
        .is_err());
    }

    #[test]
    fn exported_audit_vectors_have_real_signatures_and_runtime_links() {
        let comparison_bytes = include_bytes!(
            "../../../../tests/bindings/vectors/security/signed-wire/positive/broker-audit-comparison-envelope-v1.json"
        );
        let runner_bytes = include_bytes!(
            "../../../../tests/bindings/vectors/security/signed-wire/positive/broker-audit-runner-authorization-envelope-v1.json"
        );
        let comparison_canonical = comparison_bytes
            .strip_suffix(b"\n")
            .unwrap_or(comparison_bytes);
        let runner_canonical = runner_bytes.strip_suffix(b"\n").unwrap_or(runner_bytes);
        let comparison = SignedBrokerAuditComparison::from_canonical_bytes(comparison_canonical)
            .test_expect("canonical signed audit comparison vector");
        let runner = SignedBrokerAuditRunnerAuthorization::from_canonical_bytes(runner_canonical)
            .test_expect("canonical signed audit runner vector");
        let runner_sha256 =
            runner_authorization_digest(&runner).test_expect("runner authorization digest");
        assert_eq!(comparison.body.runner_authorization_sha256, runner_sha256);
        assert_eq!(
            comparison.body.governed_audit_intent_sha256,
            broker_audit_governed_intent_digest(&runner.body, &runner_sha256)
                .test_expect("governed audit intent digest")
        );
        assert_eq!(
            comparison.body.audit_id_sha256,
            broker_audit_id_digest(&runner.body.audit_id).test_expect("audit identifier digest")
        );
        assert_eq!(
            comparison.body.reference_source_sha256,
            broker_audit_reference_source_digest(&runner.body.reference_source)
                .test_expect("audit reference source digest")
        );
        let encoded = comparison.canonical_bytes().test_expect("comparison bytes");
        assert_eq!(encoded.as_slice(), comparison_canonical);
    }

    #[test]
    fn comparison_decoder_rejects_noncanonical_tampered_and_oversized_inputs() {
        let fixture = include_bytes!(
            "../../../../tests/bindings/vectors/security/signed-wire/positive/broker-audit-comparison-envelope-v1.json"
        );
        let canonical = fixture.strip_suffix(b"\n").unwrap_or(fixture);
        let mut noncanonical = canonical.to_vec();
        noncanonical.push(b'\n');
        assert!(SignedBrokerAuditComparison::from_canonical_bytes(&noncanonical).is_err());

        let mut tampered: SignedBrokerAuditComparison =
            serde_json::from_slice(canonical).test_expect("decode audit comparison for tampering");
        tampered.body.audit_id_sha256 = "0".repeat(64);
        assert!(tampered.canonical_bytes().is_err());
        let tampered_bytes =
            canonical_json_bytes(&tampered).test_expect("encode tampered audit comparison");
        assert!(SignedBrokerAuditComparison::from_canonical_bytes(&tampered_bytes).is_err());

        let oversized = vec![b' '; MAX_AUDIT_COMPARISON_BYTES + 1];
        assert!(SignedBrokerAuditComparison::from_canonical_bytes(&oversized).is_err());
    }
}
