#![cfg(unix)]

use std::{fs, path::PathBuf, process::Command, time::SystemTime};

type TestResult = Result<(), Box<dyn std::error::Error>>;

struct Fixture(PathBuf);

impl Fixture {
    fn new() -> Result<Self, Box<dyn std::error::Error>> {
        let stamp = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)?
            .as_nanos();
        let root =
            std::env::temp_dir().join(format!("chio-go-check-{}-{stamp}", std::process::id()));
        fs::create_dir(&root)?;
        let fixture = Self(root);
        for directory in [
            "xtask",
            "crates/core/chio-core",
            "sdks/go/chio-go-http/scripts",
        ] {
            fs::create_dir_all(fixture.0.join(directory))?;
        }
        fs::write(
            fixture.0.join("Cargo.toml"),
            "[workspace]\nmembers = [\"xtask\", \"crates/core/chio-core\"]\n",
        )?;
        for (path, name) in [("xtask", "xtask"), ("crates/core/chio-core", "chio-core")] {
            fs::write(
                fixture.0.join(path).join("Cargo.toml"),
                format!("[package]\nname = \"{name}\"\nversion = \"0.0.0\"\n"),
            )?;
        }
        fs::write(fixture.0.join("baseline.go"), "// retained bytes\n")?;
        fs::write(
            fixture.0.join("sdks/go/chio-go-http/types.go"),
            "// retained bytes\n",
        )?;
        fs::write(
            fixture
                .0
                .join("sdks/go/chio-go-http/scripts/regen-types.sh"),
            r#"#!/bin/sh
set -eu
tracked="$PWD/sdks/go/chio-go-http/types.go"
output="$tracked"
if [ "$#" -eq 2 ] && [ "$1" = "--output" ]; then output="$2"; fi
printf '// regenerated bytes\n' > "$output"
if cmp -s "$tracked" "$PWD/baseline.go"; then
    printf 'untouched' > "$PWD/observation"
else
    printf 'modified' > "$PWD/observation"
fi
exit "${CHIO_TEST_GO_REGEN_EXIT:-0}"
"#,
        )?;
        Ok(fixture)
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

#[test]
fn go_check_never_publishes_transient_bytes_on_drift_or_generator_failure() -> TestResult {
    for exit in ["0", "7"] {
        let fixture = Fixture::new()?;
        let result = Command::new(env!("CARGO_BIN_EXE_xtask"))
            .args(["codegen", "--lang", "go", "--check"])
            .env("CHIO_TEST_GO_REGEN_EXIT", exit)
            .current_dir(&fixture.0)
            .output()?;
        assert!(
            !result.status.success(),
            "drift or failed generator must refuse"
        );
        assert_eq!(
            fs::read_to_string(fixture.0.join("observation"))?,
            "untouched",
            "check mutated the maintained path before restoring it"
        );
        assert_eq!(
            fs::read(fixture.0.join("sdks/go/chio-go-http/types.go"))?,
            b"// retained bytes\n"
        );
    }
    Ok(())
}
