"""Install the bundled runtime offline, then prepare or resume a repository review."""

import argparse
import hashlib
import json
import os
import platform
import signal
import subprocess
import sys
import venv
from pathlib import Path

HERE = Path(__file__).resolve().parent


def require(condition, message):
    if not condition:
        raise ValueError(message)


def digest(path):
    with path.open("rb") as source:
        return hashlib.file_digest(source, "sha256").hexdigest()


def persist(path, value):
    temporary = path.with_suffix(".tmp")
    with temporary.open("w") as output:
        json.dump(value, output, indent=2, allow_nan=False)
        output.write("\n")
        output.flush()
        os.fsync(output.fileno())
    temporary.replace(path)
    descriptor = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def environment():
    # Keep provider configuration private in the environment. Imports must come
    # from the bundled application and its installed environment, not a checkout.
    return {
        key: value for key, value in os.environ.items() if not key.startswith("PYTHON")
    }


def manifest():
    value = json.loads((HERE / "manifest.json").read_text())
    require(
        value["schema"] == "chio.repository.review-kit.v1", "unsupported kit manifest"
    )
    require(sys.platform == "linux", "the native worker runner requires Linux")
    require(
        value["system"] == platform.system() and value["machine"] == platform.machine(),
        "this kit was built for another operating system or architecture",
    )
    require(
        value["python"] == list(sys.version_info[:2]),
        "use the Python major and minor version recorded in manifest.json",
    )
    for name, expected in value["files"].items():
        path = HERE / name
        require(path.resolve().is_relative_to(HERE), "artifact path escapes the kit")
        require(
            path.is_file() and digest(path) == expected, f"artifact changed: {name}"
        )
    return value


def command(args, *, cwd, log, timeout=180):
    with log.open("ab") as errors:
        process = subprocess.Popen(
            list(map(str, args)),
            cwd=cwd,
            env=environment(),
            stdout=subprocess.PIPE,
            stderr=errors,
        )
        try:
            output, _ = process.communicate(timeout=timeout)
            require(process.returncode == 0, f"command failed; inspect private {log}")
            return output
        finally:
            if process.poll() is None:
                process.terminate()
                try:
                    process.communicate(timeout=40)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.communicate(timeout=10)


# Run in isolated mode so qualification cannot accidentally import SDKs from
# PYTHONPATH, the user site or a development checkout. Distribution RECORDs
# select installed files; generated bytecode is excluded from drift checks.
INVENTORY = """
import hashlib, importlib.metadata, json, sys
from pathlib import Path
import chio_process, chio_langgraph, chio_sdk, chio_adapter_base
import langgraph.graph, langgraph.checkpoint.sqlite
root = Path(sys.prefix).resolve()
files, packages = {}, {}
for dist in importlib.metadata.distributions():
    name = dist.metadata['Name'].lower().replace('_', '-')
    if name in ('pip', 'setuptools', 'wheel'):
        continue
    packages[name] = dist.version
    for entry in dist.files or ():
        path = Path(dist.locate_file(entry)).resolve()
        if path.suffix == '.pyc':
            continue
        if not path.is_relative_to(root) or not path.is_file():
            raise ValueError('installed distribution escapes its environment or has missing files')
        with path.open('rb') as source:
            files[str(path.relative_to(root))] = hashlib.file_digest(source, 'sha256').hexdigest()
modules = {
    module.__name__: str(Path(module.__file__).resolve()) for module in
    (chio_process, chio_langgraph, chio_sdk, chio_adapter_base, langgraph.graph, langgraph.checkpoint.sqlite)
}
if any(not Path(path).is_relative_to(root) for path in modules.values()):
    raise ValueError('application dependencies were imported outside the installed environment')
print(json.dumps({'packages': packages, 'files': files, 'modules': modules}))
"""


def installed(state):
    return json.loads(
        command(
            [state / "venv/bin/python", "-I", "-c", INVENTORY],
            cwd=state,
            log=state / "install.log",
        )
    )


def prepare(args, pins):
    state = args.state.resolve()
    state.mkdir(mode=0o700, exist_ok=False)
    venv.EnvBuilder(with_pip=True).create(state / "venv")
    python = state / "venv/bin/python"
    command(
        [
            python,
            "-I",
            "-m",
            "pip",
            "--isolated",
            "install",
            "--no-index",
            "--no-deps",
            "--require-hashes",
            "--only-binary=:all:",
            "--disable-pip-version-check",
            "--find-links",
            HERE / "packages",
            "-r",
            HERE / "requirements.txt",
        ],
        cwd=state,
        log=state / "install.log",
    )
    command(
        [python, "-I", "-m", "pip", "--isolated", "check"],
        cwd=state,
        log=state / "install.log",
    )
    inventory = installed(state)
    require(
        inventory["packages"] == pins["packages"],
        "installed versions differ from the kit",
    )
    command(
        [
            python,
            HERE / "application/adaptive_review.py",
            "prepare",
            "--repo",
            args.repo.resolve(),
            "--base",
            args.base,
            "--head",
            args.head,
            "--run-dir",
            state / "run",
            "--chio",
            HERE / "bin/chio",
            "--model-factory",
            args.model_factory,
            "--max-reviews",
            args.max_reviews,
            "--max-parallel",
            args.max_parallel,
            "--max-rounds",
            args.max_rounds,
            "--max-calls",
            args.max_calls,
        ],
        cwd=state,
        log=state / "application.log",
    )
    persist(
        state / "installation.json",
        {
            "schema": "chio.repository.review-installation.v1",
            "kit": str(HERE),
            "manifest_sha256": digest(HERE / "manifest.json"),
            "runtime": inventory,
        },
    )
    return {"prepared": True, "state": str(state), "run_dir": str(state / "run")}


def validate(state):
    require(
        (state / "installation.json").is_file(),
        "partial preparation; preserve diagnostics and prepare a new state directory",
    )
    require(not state.stat().st_mode & 0o077, "state directory must be private")
    original = json.loads((state / "installation.json").read_text())
    require(
        original["schema"] == "chio.repository.review-installation.v1",
        "unsupported installation record",
    )
    require(
        original["kit"] == str(HERE)
        and original["manifest_sha256"] == digest(HERE / "manifest.json"),
        "kit location or artifacts changed; restore the prepared kit",
    )
    for name, expected in original["runtime"]["files"].items():
        path = state / "venv" / name
        require(
            path.resolve().is_relative_to(state / "venv"),
            "installed path escapes environment",
        )
        require(
            path.is_file() and digest(path) == expected,
            f"installed file changed: {name}",
        )
    current = installed(state)
    # Additional provider packages are allowed, but they cannot replace a
    # prepared dependency or change any of its installed files.
    for name, version in original["runtime"]["packages"].items():
        require(
            current["packages"].get(name) == version,
            f"installed dependency changed: {name}",
        )
    for name, expected in original["runtime"]["files"].items():
        require(
            current["files"].get(name) == expected, f"installed file changed: {name}"
        )


def main():
    os.umask(0o077)

    def stop(_signal, _frame):
        raise KeyboardInterrupt

    signal.signal(signal.SIGTERM, stop)
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    prepare_args = commands.add_parser("prepare")
    prepare_args.add_argument("--state", type=Path, required=True)
    prepare_args.add_argument("--repo", type=Path, required=True)
    prepare_args.add_argument("--base", required=True)
    prepare_args.add_argument("--head", default="HEAD")
    prepare_args.add_argument("--model-factory", default="inventory")
    for name, default, limit in (
        ("reviews", 8, 16),
        ("parallel", 2, 16),
        ("rounds", 8, 32),
        ("calls", 300, 1000),
    ):
        prepare_args.add_argument(
            f"--max-{name}", type=int, choices=range(1, limit + 1), default=default
        )
    run_args = commands.add_parser("run")
    run_args.add_argument("--state", type=Path, required=True)
    args = parser.parse_args()
    pins = manifest()
    if args.command == "prepare":
        result = prepare(args, pins)
    else:
        state = args.state.resolve(strict=True)
        validate(state)
        result = json.loads(
            command(
                [
                    state / "venv/bin/python",
                    HERE / "application/adaptive_review.py",
                    "run",
                    "--run-dir",
                    state / "run",
                ],
                cwd=state,
                log=state / "application.log",
                timeout=3720,
            )
        )
    print(json.dumps(result))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(
            "review interrupted; preserve the state and resume the same run",
            file=sys.stderr,
        )
        raise SystemExit(130) from None
    except (ValueError, OSError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"review: {error}") from None
