/*
 * Chio browser-SDK M04 verify demo.
 *
 * Loads a stable, public-key-only receipt fixture from the M04 corpus
 * (tests/bindings/vectors/receipt/v1.json, case `allow_receipt`) and runs
 * `verify_receipt` from `@chio-protocol/browser` directly in the page.
 *
 * The wasm artifact is generated by `sdks/typescript/scripts/build-wasm.sh`
 * (target=web). When the artifact is missing -- for example, on a fresh
 * checkout where wasm-pack has not yet run -- the demo renders the banner
 * and a clear "wasm not built" notice instead of crashing the page.
 */

import fixture from './fixtures/m04-allow-receipt.json';

interface VerifyReceiptResult {
  ok: boolean;
  signature_valid: boolean;
  parameter_hash_valid: boolean;
  signer_trusted: boolean;
  decision: string;
  receipt_id: string | null;
  signer_key_hex: string | null;
}

interface BrowserSdk {
  verify_receipt: (envelope: Uint8Array, trustedIssuers?: unknown) => unknown;
}

const FIXTURE_LABEL = `${fixture.source}#${fixture.source_case_id}`;

function setText(id: string, value: string, state: 'ok' | 'fail' | 'info' = 'info'): void {
  const el = document.getElementById(id);
  if (!el) return;
  el.textContent = value;
  el.setAttribute('data-state', state);
}

/**
 * Resolve `@chio-protocol/browser`. Imports the wasm-pack-emitted ESM glue
 * directly via the package's `./pkg/*` export, bypassing the package's
 * compiled `dist/index.js` (which only exists once the browser package's
 * own `tsc` step has run). This lets the demo build green on a fresh
 * checkout where only the wasm artifact has been generated.
 *
 * Wrapped in dynamic import so a missing `pkg/` directory does not break
 * the Vite production build; the runtime surfaces the failure in the DOM
 * instead.
 */
async function loadBrowserSdk(): Promise<BrowserSdk | { error: string }> {
  try {
    // Import path: the browser package's exports map declares
    //   "./pkg/*": "./pkg/*"
    // so this resolves to sdks/typescript/packages/browser/pkg/chio_kernel_browser.js
    // (wasm-pack --target web output).
    const mod = (await import(
      '@chio-protocol/browser/pkg/chio_kernel_browser.js'
    )) as { default?: () => Promise<unknown> } & BrowserSdk;

    // wasm-pack --target web requires a one-time `init()` call (the
    // module's default export) to fetch and instantiate the .wasm. Skip
    // when not exported (e.g., a future bundler-target re-export shape).
    if (typeof mod.default === 'function') {
      await mod.default();
    }

    if (typeof mod.verify_receipt !== 'function') {
      return { error: 'wasm export missing: verify_receipt' };
    }
    return mod;
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause);
    return {
      error: `failed to load @chio-protocol/browser: ${message}. ` +
        `Run sdks/typescript/scripts/build-wasm.sh --target web to generate the wasm artifact.`,
    };
  }
}

function encodeReceipt(receipt: unknown): Uint8Array {
  const json = JSON.stringify(receipt);
  return new TextEncoder().encode(json);
}

function renderResult(result: VerifyReceiptResult, elapsedMs: number): void {
  setText('fixture-id', FIXTURE_LABEL, 'info');
  setText('verdict', result.decision ?? '(none)', result.ok ? 'ok' : 'fail');
  setText(
    'signature-valid',
    String(result.signature_valid),
    result.signature_valid ? 'ok' : 'fail',
  );
  setText('signer-key', result.signer_key_hex ?? '(none)', 'info');
  setText('elapsed', `${elapsedMs.toFixed(2)} ms`, 'info');

  const raw = document.getElementById('raw-result');
  if (raw) raw.textContent = JSON.stringify(result, null, 2);
}

function renderError(stage: string, message: string): void {
  setText('fixture-id', FIXTURE_LABEL, 'info');
  setText('verdict', `error during ${stage}`, 'fail');
  setText('signature-valid', '(unavailable)', 'fail');
  setText('signer-key', '(unavailable)', 'info');
  setText('elapsed', '(unavailable)', 'info');

  const raw = document.getElementById('raw-result');
  if (raw) raw.textContent = `[${stage}] ${message}`;
}

async function run(): Promise<void> {
  const loaded = await loadBrowserSdk();
  if ('error' in loaded) {
    renderError('load-sdk', loaded.error);
    return;
  }

  const envelope = encodeReceipt(fixture.receipt);
  // Pin the embedded kernel key so the demo proves issuer-pinning, not just
  // raw signature math. The key lives inside the receipt fixture itself
  // (public key only; no private material ships to the browser).
  const trustedIssuers = [fixture.receipt.kernel_key];

  const start =
    typeof performance !== 'undefined' && typeof performance.now === 'function'
      ? performance.now()
      : Date.now();

  let result: VerifyReceiptResult;
  try {
    const raw = loaded.verify_receipt(envelope, trustedIssuers);
    result = raw as VerifyReceiptResult;
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause);
    renderError('verify', message);
    return;
  }

  const elapsed =
    (typeof performance !== 'undefined' && typeof performance.now === 'function'
      ? performance.now()
      : Date.now()) - start;

  renderResult(result, elapsed);
}

void run();
