include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/trust_control/cluster/admission_consensus_parts/part_01.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/trust_control/cluster/admission_consensus_parts/part_02.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/trust_control/cluster/admission_consensus_parts/part_03.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/trust_control/cluster/admission_consensus_parts/part_04.inc"
));
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/trust_control/cluster/admission_consensus_parts/part_05.inc"
));
