#!/usr/bin/env python3
"""Remove known legacy generated declarations without changing XML values."""
import re
import sys
from html.entities import name2codepoint
from pathlib import Path
import xml.etree.ElementTree as ET

KNOWN_ENTITIES = {**name2codepoint, "nbhy": 0x2011, "zwsp": 0x200B, "wj": 0x2060}
DTD_ENTITIES = {"nbsp": 160, "zwsp": 8203, "nbhy": 8209, "wj": 8288}
PROTECTED = re.compile(r'(<!\[CDATA\[.*?\]\]>|<!--.*?-->|<\?.*?\?>)', re.DOTALL)
INTERNAL_DTD = re.compile(r'<!DOCTYPE\s+rfc\s*\[([^\]]*)\]\s*>', re.DOTALL)
GENERATOR_COMMENT = re.compile(r'(<!-- generated by https://github\.com/cabo/kramdown-rfc version [\d.]+) \(Ruby [^)]+\)( -->)')


def outside_text(data):
    def strip_internal(match):
        subset = match.group(1)
        declarations = re.findall(r'<!ENTITY\s+(\w+)\s+"&#(\d+);"\s*>', subset)
        residue = re.sub(r'<!ENTITY\s+\w+\s+"&#\d+;"\s*>', '', subset)
        if residue.strip() or any(DTD_ENTITIES.get(name) != int(value) for name, value in declarations):
            raise ValueError("unexpected internal DTD")
        return ''
    data = INTERNAL_DTD.sub(strip_internal, data)
    data = re.sub(r'<!DOCTYPE\s+rfc\s+SYSTEM\s+"rfc2629-xhtml\.ent"\s*>', '', data)
    if '<!DOCTYPE' in data or '<!ENTITY' in data:
        raise ValueError("unexpected DTD declaration")
    for name, codepoint in KNOWN_ENTITIES.items():
        data = data.replace(f'&{name};', f'&#{codepoint};')
    return data


def normalize(data):
    parts = PROTECTED.split(data)
    for index, part in enumerate(parts):
        if index % 2 == 0:
            parts[index] = outside_text(part)
        elif re.fullmatch(r'<\?line\s+-?\d+\?>', part):
            parts[index] = ''
        elif GENERATOR_COMMENT.fullmatch(part):
            parts[index] = GENERATOR_COMMENT.sub(r'\1\2', part)
    result = ''.join(parts)
    ET.fromstring(result)
    return result


if __name__ == '__main__':
    try:
        if len(sys.argv) != 3:
            raise ValueError("expected input and output paths")
        Path(sys.argv[2]).write_text(normalize(Path(sys.argv[1]).read_text()))
    except (OSError, ValueError, ET.ParseError) as error:
        print(f'normalize_xml: {error}', file=sys.stderr)
        sys.exit(1)
