#!/usr/bin/env python3
"""Regression checks for silent converter and validator acceptance failures."""
import copy
import unittest
import xml.etree.ElementTree as ET
from idnits_gate import validate
from normalize_xml import normalize

CLEAN = {"result": "pass", "file": {"path": "draft.xml", "size": 100},
         "nitsBySeverity": {"error": 0, "warning": 0, "comment": 0}, "nits": []}


class IdnitsGate(unittest.TestCase):
    def test_completed_clean_report(self):
        self.assertEqual(validate(CLEAN), CLEAN["nitsBySeverity"])

    def test_completed_comments_are_allowed(self):
        report = copy.deepcopy(CLEAN)
        report.update(result="fail", nits=[{"severity": "ValidationComment", "code": "comment", "desc": "Informational"}])
        report["nitsBySeverity"]["comment"] = 1
        self.assertEqual(validate(report)["comment"], 1)

    def test_errors_and_warnings_are_rejected(self):
        for severity, key in [("ValidationError", "error"), ("ValidationWarning", "warning")]:
            report = copy.deepcopy(CLEAN)
            report.update(result="fail", nits=[{"severity": severity, "code": "nit", "desc": "Failure"}])
            report["nitsBySeverity"][key] = 1
            with self.subTest(severity=severity), self.assertRaises(ValueError):
                validate(report)

    def test_incomplete_and_contradictory_reports_are_rejected(self):
        reports = [None, {}, {"nits": [], "nitsBySeverity": None}]
        for change in [{"result": "fail"}, {"file": {"path": "draft.xml", "size": True}},
                       {"nitsBySeverity": {"error": 1, "warning": 0, "comment": 0}},
                       {"nitsBySeverity": {"error": False, "warning": 0, "comment": 0}},
                       {"result": "fail", "nits": [{"severity": "warning", "code": "nit", "desc": "Failure"}]}]:
            report = copy.deepcopy(CLEAN); report.update(change); reports.append(report)
        for report in reports:
            with self.subTest(report=report), self.assertRaises((ValueError, TypeError)):
                validate(report)


class XmlNormalization(unittest.TestCase):
    def test_known_dtd_entities_preserve_typed_text(self):
        source = '<!DOCTYPE rfc [<!ENTITY nbsp "&#160;">]><rfc><t>&nbsp;&nbhy;&amp;</t></rfc>'
        self.assertEqual(ET.fromstring(normalize(source)).findtext('t'), '\u00a0\u2011&')

    def test_cdata_comments_and_non_line_pi_preserve_literal_bytes(self):
        protected = '<sourcecode><![CDATA[{"literal":"&nbsp; <!DOCTYPE rfc> <?line 1?>"}]]></sourcecode><!-- &nbsp; (Ruby 4.0.6) --><\x3fexample &nbsp;\x3f>'
        source = '<rfc>' + protected + '</rfc>'
        self.assertEqual(normalize(source), source)
        self.assertEqual(ET.fromstring(normalize(source)).findtext('sourcecode'), '{"literal":"&nbsp; <!DOCTYPE rfc> <?line 1?>"}')

    def test_only_generator_runtime_and_line_pi_are_removed(self):
        source = '<!-- generated by https://github.com/cabo/kramdown-rfc version 1.7.43 (Ruby 4.0.6) --><rfc><?line -2?><t>ok</t></rfc>'
        result = normalize(source)
        self.assertNotIn('(Ruby', result)
        self.assertNotIn('<?line', result)
        self.assertIn('version 1.7.43', result)

    def test_unknown_or_changed_dtd_is_rejected(self):
        for declaration in ['<!DOCTYPE rfc SYSTEM "https://example.invalid/evil.dtd">',
                            '<!DOCTYPE rfc [<!ENTITY nbsp "&#1;">]>',
                            '<!DOCTYPE rfc [<!ENTITY payload SYSTEM "file:///etc/passwd">]>']:
            with self.subTest(declaration=declaration), self.assertRaises(ValueError):
                normalize(declaration + '<rfc/>')


if __name__ == '__main__':
    unittest.main()
