#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../../.." && pwd)"
tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/chio-docker-workspace.XXXXXX")"
trap 'rm -rf "${tmp_dir}"' EXIT
mode=write
member="crates/products/chio-cli"
destination="${script_dir}"
for argument in "$@"; do
  case "${argument}" in
    write | --write | check | --check) mode="${argument}" ;;
    --proof-room)
      member="crates/products/chio-proof-room"
      destination="${script_dir}/../proof-room-workspace"
      ;;
    *)
      echo "usage: $0 [--check] [--proof-room]" >&2
      exit 2
      ;;
  esac
done

{
  echo "# Generated by deploy/docker/chio-workspace/regenerate.sh."
  echo "# Docker uses this manifest to build ${member##*/} without copying non-product workspace roots."
  echo
  echo "[workspace]"
  echo 'resolver = "2"'
  printf 'members = ["%s"]\n' "${member}"
  echo
  awk 'BEGIN { copy = 0; patch = 0 }
       /^\[workspace\.package\]/ { copy = 1 }
       /^\[patch\.crates-io\]/ { patch = 1; print; next }
       patch && /^\[/ { patch = 0 }
       patch { print; next }
       copy { print }' \
    "${repo_root}/Cargo.toml"
} >"${tmp_dir}/Cargo.toml.generated"

cp "${repo_root}/Cargo.lock" "${tmp_dir}/Cargo.lock"
cp "${tmp_dir}/Cargo.toml.generated" "${tmp_dir}/Cargo.toml"
ln -s "${repo_root}/crates" "${tmp_dir}/crates"
ln -s "${repo_root}/third_party" "${tmp_dir}/third_party"
ln -s "${repo_root}/fixtures" "${tmp_dir}/fixtures"
ln -s "${repo_root}/spec" "${tmp_dir}/spec"
ln -s "${repo_root}/wit" "${tmp_dir}/wit"

(
  cd "${tmp_dir}"
  cargo metadata --format-version 1 >/dev/null
  cargo metadata --format-version 1 --locked >/dev/null
)

if [[ "${mode}" == "check" || "${mode}" == "--check" ]]; then
  diff -u "${destination}/Cargo.toml" "${tmp_dir}/Cargo.toml.generated"
  diff -u "${destination}/Cargo.lock" "${tmp_dir}/Cargo.lock"
else
  cp "${tmp_dir}/Cargo.toml.generated" "${destination}/Cargo.toml"
  cp "${tmp_dir}/Cargo.lock" "${destination}/Cargo.lock"
fi
