#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../../.." && pwd)"
tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/chio-docker-workspace.XXXXXX")"
trap 'rm -rf "${tmp_dir}"' EXIT
mode="${1:-write}"

case "${mode}" in
  write | --write | check | --check) ;;
  *)
    echo "usage: $0 [--check]" >&2
    exit 2
    ;;
esac

{
  echo "# Generated by deploy/docker/chio-workspace/regenerate.sh."
  echo "# Docker uses this manifest to build chio-cli without copying non-product workspace roots."
  echo
  echo "[workspace]"
  echo 'resolver = "2"'
  echo 'members = ["crates/products/chio-cli"]'
  echo
  awk 'BEGIN { copy = 0 } /^\[workspace\.package\]/ { copy = 1 } copy { print }' \
    "${repo_root}/Cargo.toml"
} >"${tmp_dir}/Cargo.toml.generated"

cp "${repo_root}/Cargo.lock" "${tmp_dir}/Cargo.lock"
cp "${tmp_dir}/Cargo.toml.generated" "${tmp_dir}/Cargo.toml"
ln -s "${repo_root}/crates" "${tmp_dir}/crates"
ln -s "${repo_root}/fixtures" "${tmp_dir}/fixtures"
ln -s "${repo_root}/spec" "${tmp_dir}/spec"
ln -s "${repo_root}/third_party" "${tmp_dir}/third_party"
ln -s "${repo_root}/wit" "${tmp_dir}/wit"

(
  cd "${tmp_dir}"
  cargo metadata --format-version 1 >/dev/null
  cargo metadata --format-version 1 --locked >/dev/null
)

if [[ "${mode}" == "check" || "${mode}" == "--check" ]]; then
  diff -u "${script_dir}/Cargo.toml" "${tmp_dir}/Cargo.toml.generated"
  diff -u "${script_dir}/Cargo.lock" "${tmp_dir}/Cargo.lock"
else
  cp "${tmp_dir}/Cargo.toml.generated" "${script_dir}/Cargo.toml"
  cp "${tmp_dir}/Cargo.lock" "${script_dir}/Cargo.lock"
fi
