-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [formal_economy]: function definitions
import Aeneas
import FormalEconomy.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace Chio.AeneasEconomy

/-- [formal_economy::convert_ceil_scalar]:
    Source: 'crates/economy/chio-credit/src/formal_economy.rs', lines 8:0-26:1
    Visibility: public -/
def convert_ceil_scalar
  (units : Std.U64) (numerator : Std.U64) (denominator : Std.U64) :
  Result (Option Std.U64)
  := do
  if numerator = 0#u64
  then ok none
  else
    if denominator = 0#u64
    then ok none
    else
      let i ← lift (UScalar.cast .U128 units)
      let i1 ← lift (UScalar.cast .U128 numerator)
      let product ← i * i1
      let denominator1 ← lift (UScalar.cast .U128 denominator)
      let quotient ← product / denominator1
      let i2 ← product % denominator1
      let rounded ← if i2 = 0#u128
                      then ok quotient
                      else quotient + 1#u128
      let i3 ← lift (UScalar.cast .U128 core.num.U64.MAX)
      if rounded > i3
      then ok none
      else let i4 ← lift (UScalar.cast .U64 rounded)
           ok (some i4)

/-- [formal_economy::convert_floor_scalar]:
    Source: 'crates/economy/chio-credit/src/formal_economy.rs', lines 32:0-44:1
    Visibility: public -/
def convert_floor_scalar
  (units : Std.U64) (numerator : Std.U64) (denominator : Std.U64) :
  Result (Option Std.U64)
  := do
  if numerator = 0#u64
  then ok none
  else
    if denominator = 0#u64
    then ok none
    else
      let i ← lift (UScalar.cast .U128 units)
      let i1 ← lift (UScalar.cast .U128 numerator)
      let product ← i * i1
      let i2 ← lift (UScalar.cast .U128 denominator)
      let quotient ← product / i2
      let i3 ← lift (UScalar.cast .U128 core.num.U64.MAX)
      if quotient > i3
      then ok none
      else let i4 ← lift (UScalar.cast .U64 quotient)
           ok (some i4)

end Chio.AeneasEconomy
