use super::*;

pub(super) fn render_markdown(
    rows: &[CoverageRow],
    lanes: &[String],
    artifact_records: &[ArtifactRecord],
) -> String {
    let qualifiers = artifact_records
        .iter()
        .map(|artifact| (&artifact.id, &artifact.qualifiers))
        .collect::<BTreeMap<_, _>>();
    let mut output = String::from("| Surface");
    for lane in lanes {
        output.push_str(" | ");
        output.push_str(lane);
    }
    output.push_str(" |\n| ---");
    for _ in lanes {
        output.push_str(" | ---:");
    }
    output.push_str(" |\n");
    for row in rows {
        output.push_str("| `");
        output.push_str(&row.surface);
        output.push('`');
        for lane in lanes {
            output.push_str(" | ");
            match row.lanes.get(lane).map(BTreeSet::len).unwrap_or(0) {
                0 => output.push('-'),
                count => output.push_str(&count.to_string()),
            }
        }
        output.push_str(" |\n");
    }
    output.push_str("\n## Evidence Details\n\n");
    for row in rows {
        output.push_str("### `");
        output.push_str(&row.surface);
        output.push_str("`\n\n");
        for lane in lanes {
            let Some(artifacts) = row.lanes.get(lane).filter(|values| !values.is_empty()) else {
                continue;
            };
            output.push_str("**");
            output.push_str(lane);
            output.push_str("**\n\n");
            for artifact in artifacts {
                output.push_str("- `");
                output.push_str(artifact);
                output.push('`');
                if let Some(values) = qualifiers.get(artifact).filter(|values| !values.is_empty()) {
                    output.push_str(" (");
                    output.push_str(&render_qualifiers(values));
                    output.push(')');
                }
                output.push('\n');
            }
            output.push('\n');
        }
    }
    output
}

pub(super) fn render_qualifiers(qualifiers: &BTreeMap<String, String>) -> String {
    qualifiers
        .iter()
        .map(|(key, value)| format!("{key}={value}"))
        .collect::<Vec<_>>()
        .join(", ")
}

pub(super) fn markdown_cells(line: &str) -> Vec<String> {
    line.trim_matches('|')
        .split('|')
        .map(|cell| cell.trim().to_string())
        .collect()
}

pub(super) fn separator_cells(cells: &[String]) -> bool {
    !cells.is_empty()
        && cells.iter().all(|cell| {
            let trimmed = cell.trim_matches(':');
            trimmed.len() >= 3 && trimmed.bytes().all(|byte| byte == b'-')
        })
}

pub(super) fn strip_code_span(value: &str) -> String {
    value
        .strip_prefix('`')
        .and_then(|inner| inner.strip_suffix('`'))
        .unwrap_or(value)
        .to_string()
}

pub(super) fn render_document(build: &CoverageBuild) -> Result<String, String> {
    let mut output = String::from(
        "<!-- Generated by `cargo xtask gen proof-coverage`. Do not edit. -->\n\n# Proof Coverage\n\n",
    );
    output.push_str(
        "This matrix joins declared verification evidence to its primary Rust surface. A populated cell is an artifact count, not a completeness claim. Full artifact identifiers appear below the matrix. Claim wording remains governed by [CLAIM_REGISTRY.md](../reference/CLAIM_REGISTRY.md).\n\n",
    );
    output.push_str(
        "Theorem inventory and differential-test artifacts without a machine-readable Rust link are listed as unattributed. They are not assigned by naming heuristics. Qualifiers preserve theorem status and Kani execution or model scope. Empty cells are deliberate.\n\n## Surface Matrix\n\n",
    );
    output.push_str(&render_markdown(
        &build.rows,
        &build.lanes,
        &build.artifacts,
    ));
    output.push_str("## Related Surfaces\n\n");
    let mut related_count = 0usize;
    for artifact in &build.artifacts {
        if artifact.related_surfaces.is_empty() {
            continue;
        }
        related_count += 1;
        output.push_str("- `");
        output.push_str(&artifact.id);
        output.push_str("`: ");
        output.push_str(
            &artifact
                .related_surfaces
                .iter()
                .map(|surface| format!("`{surface}`"))
                .collect::<Vec<_>>()
                .join(", "),
        );
        output.push('\n');
    }
    if related_count == 0 {
        output.push_str("- None.\n");
    }

    output.push_str("\n## Unattributed Artifacts\n\n");
    if build.unattributed_artifacts.is_empty() {
        output.push_str("- None.\n");
    } else {
        for artifact in &build.unattributed_artifacts {
            output.push_str("- `");
            output.push_str(&artifact.id);
            output.push_str("` (`");
            output.push_str(&artifact.lane);
            output.push_str("`)");
            if !artifact.qualifiers.is_empty() {
                output.push_str(" (");
                output.push_str(&render_qualifiers(&artifact.qualifiers));
                output.push(')');
            }
            output.push_str(": ");
            output.push_str(&artifact.reason);
            if !artifact.related_properties.is_empty() {
                output.push_str(" Properties: ");
                output.push_str(&artifact.related_properties.join(", "));
                output.push('.');
            }
            if !artifact.related_surfaces.is_empty() {
                output.push_str(" Related surfaces: ");
                output.push_str(
                    &artifact
                        .related_surfaces
                        .iter()
                        .map(|surface| format!("`{surface}`"))
                        .collect::<Vec<_>>()
                        .join(", "),
                );
                output.push('.');
            }
            output.push('\n');
        }
    }

    output.push_str("\n## Non-Proof Linkage Metadata\n\n");
    output.push_str(
        "These drift-checked manual mirrors and contract twins are review navigation only. They do not populate evidence cells, prove semantic equivalence, or license formal claims.\n\n",
    );
    if build.review_links.is_empty() {
        output.push_str("- None.\n");
    } else {
        for link in &build.review_links {
            output.push_str("- `");
            output.push_str(&link.id);
            output.push_str("` (`");
            output.push_str(&link.kind);
            output.push_str("`, `");
            output.push_str(&link.relationship);
            output.push_str("`): `");
            output.push_str(&link.source);
            output.push_str("` -> `");
            output.push_str(&link.target);
            output.push('`');
            if !link.qualifiers.is_empty() {
                output.push_str(" (");
                output.push_str(&render_qualifiers(&link.qualifiers));
                output.push(')');
            }
            output.push('\n');
        }
    }

    output.push_str("\n## Assumption Boundary\n\n");
    for assumption in &build.assumptions {
        output.push_str("- `");
        output.push_str(&assumption.id);
        output.push_str("`: ");
        output.push_str(&assumption.status);
        output.push('\n');
    }
    output.push_str("\n## Excluded Surfaces\n\n");
    for excluded in &build.excluded_surfaces {
        output.push_str("- ");
        output.push_str(excluded);
        output.push('\n');
    }
    if !build.lane_postures.is_empty() {
        output.push_str("\n## Lane Postures\n\n");
        for (lane, posture) in &build.lane_postures {
            output.push_str("- `");
            output.push_str(lane);
            output.push_str("`: ");
            output.push_str(posture);
            output.push('\n');
        }
    }
    output.push_str("\n## Generation\n\n");
    output.push_str(&format!("- Generator version: `{GENERATOR_VERSION}`\n"));
    output.push_str("- Regenerate: `cargo xtask gen proof-coverage`\n");
    output.push_str(&format!("- Input digest: `{}`\n", build.input_digest));
    output.push_str(&format!(
        "- Git commit: `{COMMIT_TOKEN}` (resolved in coverage.json and Proof Room packages)\n"
    ));
    output.push_str(
        "- Row identity: file rows use package-relative Rust paths; crate-only artifacts use `package::*`.\n\n### Inputs\n\n",
    );
    for input in &build.inputs {
        output.push_str("- `");
        output.push_str(&input.path);
        output.push_str("`: `");
        output.push_str(&input.sha256);
        output.push_str("`\n");
    }
    if !build.parse_warnings.is_empty() {
        output.push_str("\n### Parse Warnings\n\n");
        for warning in &build.parse_warnings {
            output.push_str("- ");
            output.push_str(warning);
            output.push('\n');
        }
    }

    for line in output.lines().filter(|line| line.starts_with('|')) {
        if line.len() > 120 {
            return Err(format!(
                "coverage matrix row exceeds 120 columns ({}): {line}",
                line.len()
            ));
        }
    }
    Ok(output)
}

pub(super) fn combined_input_digest(inputs: &[InputDigest]) -> String {
    let mut hasher = Sha256::new();
    for input in inputs {
        hasher.update((input.path.len() as u64).to_be_bytes());
        hasher.update(input.path.as_bytes());
        hasher.update((input.sha256.len() as u64).to_be_bytes());
        hasher.update(input.sha256.as_bytes());
    }
    digest_hex(&hasher.finalize())
}

pub(super) fn ordered_string_digest(values: &[String]) -> String {
    let mut hasher = Sha256::new();
    for value in values {
        hasher.update((value.len() as u64).to_be_bytes());
        hasher.update(value.as_bytes());
    }
    digest_hex(&hasher.finalize())
}

pub(super) fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    digest_hex(&digest)
}

pub(super) fn digest_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    output
}

pub(super) fn git_commit(root: &Path) -> Result<String, String> {
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(root)
        .output()
        .map_err(|error| format!("cannot run git rev-parse HEAD: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "git rev-parse HEAD failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let commit = String::from_utf8(output.stdout)
        .map_err(|error| format!("git commit is not UTF-8: {error}"))?
        .trim()
        .to_string();
    if commit.len() != 40 || !commit.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(format!(
            "git rev-parse HEAD returned invalid commit: {commit}"
        ));
    }
    Ok(commit)
}

pub(super) fn write_output(path: &Path, content: &str) -> Result<(), XtaskError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| XtaskError::Io(parent.display().to_string(), error))?;
    }
    fs::write(path, content).map_err(|error| XtaskError::Io(path.display().to_string(), error))
}

pub(super) fn first_difference(existing: &str, generated: &str) -> String {
    let existing_lines = existing.lines().collect::<Vec<_>>();
    let generated_lines = generated.lines().collect::<Vec<_>>();
    let count = existing_lines.len().max(generated_lines.len());
    for index in 0..count {
        if existing_lines.get(index) != generated_lines.get(index) {
            return format!(
                " (first difference at line {}: existing={:?}, generated={:?})",
                index + 1,
                existing_lines.get(index).copied().unwrap_or("<missing>"),
                generated_lines.get(index).copied().unwrap_or("<missing>")
            );
        }
    }
    String::new()
}

pub(super) fn verify_committed_markdown(existing: &str, generated: &str) -> Result<(), String> {
    if existing == generated {
        return Ok(());
    }
    Err(format!(
        "{MARKDOWN_PATH} is stale; run `cargo xtask gen proof-coverage`{}",
        first_difference(existing, generated)
    ))
}
