// Package main documents the tool-gate guard example for ordinary Go package
// checks. The executable guard source is built only after WIT bindings are
// generated by the SDK build script.
package main
