#!/usr/bin/env python3
"""Regenerate derived-macros.tex from the artifacts each value is read from.

Every macro below is a count or a statistic that exists in a committed
artifact or in a retained benchmark result file. Nothing here is typed by
hand: the point is that a number in the paper cannot drift from the file it
came from without this script failing or changing the value.

Usage: python3 tools/derive-macros.py [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

PAPER = Path(__file__).resolve().parent.parent
REPO = PAPER.parent.parent.parent
RESULTS = PAPER.parent / "programmable-sovereignty" / "bench" / "results"
MANIFEST = PAPER.parent / "programmable-sovereignty" / "supplementary" / "artifact-manifest.json"
SUBSTITUTION_TEST = "runtime_treaty_binding_substitution"
OUT = PAPER / "derived-macros.tex"


def read(rel: Path | str) -> str:
    return (REPO / rel).read_text(encoding="utf-8")


def load_json(path: Path | str):
    p = path if isinstance(path, Path) else REPO / path
    return json.loads(p.read_text(encoding="utf-8"))


def load_toml(rel: str):
    return tomllib.loads(read(rel))


def median(values):
    ordered = sorted(values)
    n = len(ordered)
    if n % 2:
        return ordered[n // 2]
    return (ordered[n // 2 - 1] + ordered[n // 2]) / 2


def ms(value: float) -> str:
    return f"{value:.3f}"


def emit(macros: list[tuple[str, str, str]]) -> str:
    lines = [
        "% GENERATED by tools/derive-macros.py. Do not edit by hand.",
        "% Each macro is followed by the artifact it was derived from.",
        "",
    ]
    width = max(len(name) for name, _, _ in macros)
    for name, value, source in macros:
        decl = f"\\newcommand{{\\{name}}}{{{value}}}"
        pad = " " * max(1, width + 24 - len(decl))
        lines.append(f"{decl}{pad}% {source}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    macros: list[tuple[str, str, str]] = []

    def add(name, value, source):
        macros.append((name, str(value), source))

    # --- Wire and runtime code sets -------------------------------------
    federation = read("crates/trust/chio-federation/src/bilateral.rs")
    block = federation.split("rejection_codes! {", 1)[1].split("\n}", 1)[0]
    rejection_codes = re.findall(r'=>\s*"([a-z0-9_.]+)"', block)
    add(
        "PSRejectionCodeCount",
        len(rejection_codes),
        "chio-federation bilateral.rs, rejection_codes! variants",
    )

    error_rs = read("crates/trust/chio-federation/src/bilateral_verifier/error.rs")
    redacted = error_rs.split("pub fn redacted(", 1)[1].split("\n    }", 1)[0]
    verifier_codes = set(re.findall(r"RejectionCode::([A-Za-z]+)", redacted))
    add(
        "PSVerifierCodeCount",
        len(verifier_codes),
        "chio-federation bilateral_verifier/error.rs, VerifierError::redacted arms",
    )

    schema_rs = read("crates/kernel/chio-runtime-core/src/schema.rs")
    start = schema_rs.index("pub const CHIO_RUNTIME_FAILURE_CODES")
    codes_block = schema_rs[start : schema_rs.index("];", start)]
    runtime_codes = re.findall(r'"([a-z0-9_.]+)"', codes_block)
    add(
        "PSRuntimeCodeCount",
        len(runtime_codes),
        "chio-runtime-core schema.rs, CHIO_RUNTIME_FAILURE_CODES",
    )
    add(
        "PSRuntimeTreatyCodeCount",
        sum(1 for code in runtime_codes if code.startswith("chio_treaty_")),
        "chio-runtime-core schema.rs, agreement-scoped runtime codes",
    )

    types_rs = read("crates/trust/chio-federation/src/bilateral_dsse/types.rs")
    binding = types_rs.split("pub struct TreatyBindingRef {", 1)[1].split("\n}", 1)[0]
    add(
        "PSBindingFieldCount",
        len(re.findall(r"pub [a-z0-9_]+:", binding)),
        "chio-federation bilateral_dsse/types.rs, TreatyBindingRef fields",
    )

    spec = read("spec/CHIO_BILATERAL_COSIGN_INVOCATION.md")
    section7 = spec.split("## 7. Verification Algorithm", 1)[1].split("### 7.1", 1)[0]
    add(
        "PSVerifierStepCount",
        len(re.findall(r"^\s*(\d+)\. ", section7, re.M)),
        "spec/CHIO_BILATERAL_COSIGN_INVOCATION.md section 7, numbered steps",
    )

    admission = read("crates/kernel/chio-kernel/src/admission_operation.rs")
    add(
        "PSAdmissionStateCount",
        re.search(r"const ALL: \[Self; (\d+)\]", admission).group(1),
        "chio-kernel admission_operation.rs, AdmissionOperationState::ALL",
    )

    # --- Formal estate ---------------------------------------------------
    add(
        "PSAssumptionCount",
        len(load_toml("formal/assumptions.toml")["assumptions"]),
        "formal/assumptions.toml, assumption entries",
    )
    add(
        "PSTheoremCount",
        len(load_json("formal/theorem-inventory.json")["theorems"]),
        "formal/theorem-inventory.json, theorem entries",
    )
    aeneas = load_toml("formal/aeneas/production.toml")
    add(
        "PSAeneasFunctionCount",
        sum(len(target["functions"]) for target in aeneas["targets"]),
        "formal/aeneas/production.toml, functions across extraction targets",
    )
    add(
        "PSKaniHarnessCount",
        len(load_toml(".kani/harnesses.toml")["harness"]),
        ".kani/harnesses.toml, harness entries (all public-module symbols)",
    )

    evidence = sorted(
        (REPO / "formal/mutation/evidence").glob("proof-mutants-*.json"),
        key=lambda path: load_json(path)["measured_at"],
    )[-1]
    proof = load_json(evidence)
    add("PSProofMutants", proof["enumerated"], f"formal/mutation/evidence/{evidence.name}")
    add("PSProofMutantsKilled", proof["aggregate"]["killed"], "same report, aggregate.killed")
    add("PSProofMutantsUnviable", proof["aggregate"]["unviable"], "same report, aggregate.unviable")
    add("PSProofMutantsSurvived", proof["aggregate"]["survived"], "same report, aggregate.survived")

    lean = read("docs/formal/CURRENT_STATE.md")
    lean_line = re.search(
        r"Lean campaign enumerated (\d+) mutants, killed (\d+), and left (\d+)", lean, re.S
    )
    add("PSLeanMutants", lean_line.group(1), "docs/formal/CURRENT_STATE.md, retained Lean campaign")
    add("PSLeanMutantsKilled", lean_line.group(2), "same line")
    add("PSLeanMutantsSurvived", lean_line.group(3), "same line")

    # --- Corpora ---------------------------------------------------------
    vectors = load_json("tests/bindings/vectors/receipt/v1.json")
    add(
        "PSVectorCaseCount",
        len(vectors["cases"]),
        "tests/bindings/vectors/receipt/v1.json, cases",
    )
    corpus = load_json("examples/chio-3vendor/fixtures/treaty-runtime-negative-corpus.json")
    dispatchable = [
        case
        for case in corpus["cases"]
        if case.get("package") == "chio-runtime-core" and case.get("targetKind") == "integration"
    ]
    add(
        "PSThreatDispatchCaseCount",
        len(dispatchable),
        "treaty-runtime-negative-corpus.json, cases on the dispatch-capable hook",
    )
    add(
        "PSThreatVerifierCaseCount",
        len(corpus["cases"]) - len(dispatchable),
        "treaty-runtime-negative-corpus.json, cases on the verifier alone",
    )

    substitution = read(
        f"crates/kernel/chio-runtime-core/tests/{SUBSTITUTION_TEST}.rs"
    )
    add(
        "PSSubstitutionCaseCount",
        len(re.findall(r"^#\[test\]$", substitution, re.M)),
        f"tests/{SUBSTITUTION_TEST}.rs, test cases",
    )
    behavioral = [
        entry
        for entry in load_json(MANIFEST)["behavioralTests"]
        if entry["command"].endswith(SUBSTITUTION_TEST)
    ]
    if len(behavioral) != 1:
        raise SystemExit(f"binding-substitution evidence id is not unique: {behavioral}")
    add(
        "PSSubstitutionEvidenceId",
        behavioral[0]["id"],
        "artifact-manifest.json, the behavioral test that runs the substitution corpus",
    )

    # --- Retained cross-process run --------------------------------------
    fed = load_json(RESULTS / "federated-pair.json")
    add("PSRunCommit", fed["commit"][:10], "federated-pair.json, commit")
    add("PSEpochTickMs", fed["topology"]["epochTickMs"], "federated-pair.json, topology.epochTickMs")
    freshness = {
        int(match)
        for message in fed["revocation"]["cutFailureCodes"]
        for match in re.findall(r"exceeds (\d+) ms", message)
    }
    if len(freshness) != 1:
        raise SystemExit(f"freshness window is not single-valued: {freshness}")
    add(
        "PSFreshnessMs",
        freshness.pop(),
        "federated-pair.json, freshness window named in every cut denial",
    )

    revoke = fed["revocation"]["revokeToDeny"]
    cut = fed["revocation"]["cutToDeny"]
    add("PSFedRevokeMinMs", ms(revoke["min_ms"]), "federated-pair.json, revocation.revokeToDeny")
    add("PSFedRevokeMaxMs", ms(revoke["max_ms"]), "same distribution")
    add("PSFedCutMinMs", ms(cut["min_ms"]), "federated-pair.json, revocation.cutToDeny")
    add("PSFedCutMaxMs", ms(cut["max_ms"]), "same distribution")

    calls = fed["revocation"]["callsUntilDeny"]
    cut_calls = fed["revocation"]["cutCallsUntilDeny"]
    add("PSFedRevokeCallsMedian", int(median(calls)), "federated-pair.json, revocation.callsUntilDeny")
    add("PSFedRevokeCallsMax", max(calls), "same array")
    add(
        "PSFedCutCallsMedian",
        int(median(cut_calls)),
        "federated-pair.json, revocation.cutCallsUntilDeny",
    )
    add("PSFedCutCallsMax", max(cut_calls), "same array")

    ambiguous = "pre-dispatch cleanup could not be confirmed"
    revoke_records = fed["revocation"]["failureCodes"]
    cut_records = fed["revocation"]["cutFailureCodes"]
    add(
        "PSFedRevokeDenialRecords",
        len(revoke_records),
        "federated-pair.json, revocation.failureCodes",
    )
    add(
        "PSFedRevokeAmbiguousReleases",
        sum(1 for record in revoke_records if ambiguous in record),
        "same array, records reporting an unconfirmed pre-dispatch release",
    )
    add(
        "PSFedCutDenialRecords",
        len(cut_records),
        "federated-pair.json, revocation.cutFailureCodes",
    )
    add(
        "PSFedCutAmbiguousReleases",
        sum(1 for record in cut_records if ambiguous in record),
        "same array, records reporting an unconfirmed pre-dispatch release",
    )
    add(
        "PSFedRevokeAbsorbedCount",
        fed["revocation"]["freshnessDenialsAbsorbed"],
        "federated-pair.json, revocation.freshnessDenialsAbsorbed",
    )
    # The denial experiment's share is what the reported total leaves once the
    # other two buckets are taken out, so the three cannot stop summing to it.
    absorbed = fed["freshnessDenialsAbsorbed"]
    residual = absorbed["total"] - absorbed["admitted"] - absorbed["revocation"]
    if residual != absorbed["denied"]:
        raise SystemExit(
            f"absorbed freshness denials do not reconcile: {absorbed}"
        )
    add(
        "PSFedDenyAbsorbedCount",
        residual,
        "federated-pair.json, freshnessDenialsAbsorbed.total less its admitted and revocation buckets",
    )
    add(
        "PSFedAllowAttemptCount",
        fed["admitted"]["calls"] + fed["admitted"]["freshnessDenialsAbsorbed"],
        "federated-pair.json, admitted.calls plus admitted.freshnessDenialsAbsorbed",
    )
    add(
        "PSFedReceiverEvalPFiftyMs",
        ms(fed["admitted"]["receiverEvaluate"]["p50_ms"]),
        "federated-pair.json, admitted.receiverEvaluate",
    )
    add(
        "PSFedEvidencePrepPFiftyMs",
        ms(fed["admitted"]["evidencePreparation"]["p50_ms"]),
        "federated-pair.json, admitted.evidencePreparation",
    )
    add(
        "PSFedWorktreeState",
        "modified" if fed["environment"]["worktreeDirty"] else "clean",
        "federated-pair.json, environment.worktreeDirty",
    )

    rendered = emit(macros)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != rendered:
            print("derived-macros.tex is stale; run make macros", file=sys.stderr)
            return 1
        print("check-macros: clean")
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(PAPER)} with {len(macros)} macros")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
