"""Generated BOARD.md: human attention first, then items by wave, then agents."""

from __future__ import annotations

from . import agents, claims, clock, frontmatter, items
from .store import Store

STATUS_ORDER = (
    "blocked", "disputed", "in-progress", "claimed", "review", "ready", "open",
    "integrated", "done", "deferred", "wontfix",
)


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _age(started: str) -> str:
    if not started:
        return "-"
    hours = int((clock.now() - clock.parse(started)).total_seconds() // 3600)
    return f"{hours}h"


def render(store: Store) -> str:
    now = clock.now()
    out = ["# Swarm board", "", "Generated by `swarm board --write`. Do not edit by hand.", ""]

    out += ["## Needs Connor", ""]
    human = sorted(store.path("msgs", "human").glob("*.md"))
    for path in human:
        meta, _ = frontmatter.parse(path.read_text())
        out.append(f"- {meta['sent']} {meta['from']} [{meta['item'] or '-'}] {_cell(meta['subject'])}")
    if not human:
        out.append("- nothing")
    out.append("")

    everything, broken = items.all_items(store)
    leases = {c["item"]: c for c in claims.all_claims(store)}
    for wave in sorted({i.meta["wave"] for i in everything}):
        out += [f"## Wave {wave}", "", "| ID | Sev | Status | Owner | Age | Blockers | Title |", "| --- | --- | --- | --- | --- | --- | --- |"]
        rows = sorted(
            (i for i in everything if i.meta["wave"] == wave),
            key=lambda i: (STATUS_ORDER.index(i.status), i.meta["severity"], i.id),
        )
        for item in rows:
            blockers = items.deps_unmet(store, item)
            lease = leases.get(item.id)
            if lease and claims.is_expired(lease, now) and item.status not in items.CLOSED:
                blockers.append("claim expired")
            out.append(
                f"| {item.id} | {item.meta['severity']} | {item.status} | {item.meta['owner'] or '-'} | "
                f"{_age(item.meta['attempts']['started'])} | {_cell(', '.join(blockers) or '-')} | {_cell(item.meta['title'])} |"
            )
        out.append("")
    if broken:
        out += ["## Unparseable items", ""] + [f"- items/{name}" for name in broken] + [""]

    out += ["## Agents", "", "| Agent | Role | Vendor | Model | Status | Heartbeat |", "| --- | --- | --- | --- | --- | --- |"]
    for meta in agents.all_agents(store):
        beat = meta.get("last_heartbeat", "")
        flag = " STALE" if agents.is_stale(meta) else ""
        out.append(
            f"| {meta['id']} | {meta['role']} | {meta['vendor']} | {meta['model']} | {meta['status']} | {beat}{flag} |"
        )
    out.append("")
    return "\n".join(out)


def write(store: Store) -> bool:
    def mutate() -> bool:
        text = render(store)
        path = store.path("BOARD.md")
        if path.exists() and path.read_text() == text:
            return False
        path.write_text(text)
        return True

    return store.transact("board", mutate)
