# DO NOT EDIT - regenerate via 'cargo xtask codegen --lang python'.
#
# Source: spec/schemas/chio-wire/v1/**/*.schema.json
# Tool:   datamodel-code-generator==0.34.0 (see xtask/codegen-tools.lock.toml)
# Schema sha256: 35f8e30cf30553986a159b074ee485804a85db29547a8102522cd7bfa3080d2e
#
# Manual edits will be overwritten by the next regeneration; the
# spec-drift CI lane enforces this header on every file
# under sdks/python/chio-sdk-python/src/chio_sdk/_generated/.

from __future__ import annotations

from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsCapabilityLeaseRef as CapabilityLeaseRef
from .bilateral_signature_slice_envelope_schema import ChioBilateralDSSESignatureSliceEnvelope as ChioBilateralDsseSignatureSliceEnvelope
from .bilateral_signature_slice_schema import ChioBilateralDSSESignatureSliceStatement as ChioBilateralDsseSignatureSliceStatement
from .bilateral_signature_slice_schema import FederationBilateralSignatureSlicePredicateCoSign as CoSign
from .bilateral_signature_slice_schema import FederationBilateralSignatureSlicePredicateCrossOrgVisibility as CrossOrgVisibility
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceSubjectItemsDigest as Digest
from .bilateral_signature_slice_schema import ChioBilateralDSSESignatureSliceStatement as FederationBilateralSignatureSliceChioBilateralDSSESignatureSliceStatement
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsCapabilityLeaseRef
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsGovernanceReceiptRef
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsHashRecord
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsKernelIdentity
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyEvaluationSummary
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyEvaluationSummaryJointDisposition
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyVerdict
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyVerdictVerdict
from .bilateral_signature_slice_envelope_schema import ChioBilateralDSSESignatureSliceEnvelope as FederationBilateralSignatureSliceEnvelopeChioBilateralDSSESignatureSliceEnvelope
from .bilateral_signature_slice_envelope_schema import FederationBilateralSignatureSliceEnvelopeSignaturesItems
from .bilateral_signature_slice_schema import FederationBilateralSignatureSlicePredicate
from .bilateral_signature_slice_schema import FederationBilateralSignatureSlicePredicateCoSign
from .bilateral_signature_slice_schema import FederationBilateralSignatureSlicePredicateCrossOrgVisibility
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceSubjectItems
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceSubjectItemsDigest
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsGovernanceReceiptRef as GovernanceReceiptRef
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsHashRecord as HashRecord
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyEvaluationSummaryJointDisposition as JointDisposition
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsKernelIdentity as KernelIdentity
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyEvaluationSummary as PolicyEvaluationSummary
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyVerdict as PolicyVerdict
from .bilateral_signature_slice_schema import FederationBilateralSignatureSlicePredicate as Predicate
from .bilateral_signature_slice_envelope_schema import FederationBilateralSignatureSliceEnvelopeSignaturesItems as Signature
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceSubjectItems as SubjectItem
from .bilateral_signature_slice_schema import FederationBilateralSignatureSliceDefinitionsPolicyVerdictVerdict as Verdict

__all__ = [
    "CapabilityLeaseRef",
    "ChioBilateralDsseSignatureSliceEnvelope",
    "ChioBilateralDsseSignatureSliceStatement",
    "CoSign",
    "CrossOrgVisibility",
    "Digest",
    "FederationBilateralSignatureSliceChioBilateralDSSESignatureSliceStatement",
    "FederationBilateralSignatureSliceDefinitionsCapabilityLeaseRef",
    "FederationBilateralSignatureSliceDefinitionsGovernanceReceiptRef",
    "FederationBilateralSignatureSliceDefinitionsHashRecord",
    "FederationBilateralSignatureSliceDefinitionsKernelIdentity",
    "FederationBilateralSignatureSliceDefinitionsPolicyEvaluationSummary",
    "FederationBilateralSignatureSliceDefinitionsPolicyEvaluationSummaryJointDisposition",
    "FederationBilateralSignatureSliceDefinitionsPolicyVerdict",
    "FederationBilateralSignatureSliceDefinitionsPolicyVerdictVerdict",
    "FederationBilateralSignatureSliceEnvelopeChioBilateralDSSESignatureSliceEnvelope",
    "FederationBilateralSignatureSliceEnvelopeSignaturesItems",
    "FederationBilateralSignatureSlicePredicate",
    "FederationBilateralSignatureSlicePredicateCoSign",
    "FederationBilateralSignatureSlicePredicateCrossOrgVisibility",
    "FederationBilateralSignatureSliceSubjectItems",
    "FederationBilateralSignatureSliceSubjectItemsDigest",
    "GovernanceReceiptRef",
    "HashRecord",
    "JointDisposition",
    "KernelIdentity",
    "PolicyEvaluationSummary",
    "PolicyVerdict",
    "Predicate",
    "Signature",
    "SubjectItem",
    "Verdict",
]
