#!/usr/bin/env bash
# install-orchestrator-tools.sh - Pin and install the toolchain the
# autonomous orchestrator depends on.
#
# Pinned tools:
#   - mikefarah/yq v4.x  (YAML query; manifest roll-ups in EXECUTION-BOARD.md)
#   - jq                 (JSON query; EXECUTION-LOG.ndjson event parsing)
#
# This script is idempotent. It writes pinned versions into
# .planning/trajectory/tool-versions.lock and exits non-zero if the
# installed versions disagree with the lock.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCK="${ROOT}/.planning/trajectory/tool-versions.lock"

YQ_VERSION="v4.44.3"
JQ_VERSION="1.7.1"

uname_s="$(uname -s)"
uname_m="$(uname -m)"

case "${uname_s}-${uname_m}" in
    Linux-x86_64)   yq_asset="yq_linux_amd64" ;;
    Linux-aarch64)  yq_asset="yq_linux_arm64" ;;
    Darwin-x86_64)  yq_asset="yq_darwin_amd64" ;;
    Darwin-arm64)   yq_asset="yq_darwin_arm64" ;;
    *) echo "unsupported platform: ${uname_s}-${uname_m}" >&2; exit 2 ;;
esac

target_dir="${HOME}/.local/bin"
mkdir -p "${target_dir}"
case ":${PATH}:" in
    *":${target_dir}:"*) ;;
    *) echo "warning: ${target_dir} is not on PATH; add it before invoking yq/jq" >&2 ;;
esac

install_yq() {
    local installed
    installed="$(yq --version 2>/dev/null | awk '{print $NF}' || echo "missing")"
    if [[ "${installed}" == "${YQ_VERSION}" ]]; then
        echo "yq ${YQ_VERSION} already installed"
        return 0
    fi
    echo "installing yq ${YQ_VERSION} (${yq_asset})"
    local url="https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${yq_asset}"
    curl -fsSL --retry 3 "${url}" -o "${target_dir}/yq"
    chmod +x "${target_dir}/yq"
}

install_jq() {
    local installed
    installed="$(jq --version 2>/dev/null | sed 's/^jq-//' || echo "missing")"
    if [[ "${installed}" == "${JQ_VERSION}" ]]; then
        echo "jq ${JQ_VERSION} already installed"
        return 0
    fi
    echo "installing jq ${JQ_VERSION}"
    case "${uname_s}-${uname_m}" in
        Linux-x86_64)   asset="jq-linux-amd64" ;;
        Linux-aarch64)  asset="jq-linux-arm64" ;;
        Darwin-x86_64)  asset="jq-macos-amd64" ;;
        Darwin-arm64)   asset="jq-macos-arm64" ;;
    esac
    local url="https://github.com/jqlang/jq/releases/download/jq-${JQ_VERSION}/${asset}"
    curl -fsSL --retry 3 "${url}" -o "${target_dir}/jq"
    chmod +x "${target_dir}/jq"
}

install_yq
install_jq

mkdir -p "$(dirname "${LOCK}")"
cat > "${LOCK}" <<EOF
# Generated by scripts/install-orchestrator-tools.sh; do not hand-edit.
yq=${YQ_VERSION}
jq=${JQ_VERSION}
EOF

echo "tool versions pinned in ${LOCK}"
