#!/usr/bin/env bash
set -uo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "${ROOT_DIR}" ]; then
  echo "error: not a git checkout (or git missing); cannot resolve workspace root" >&2
  exit 2
fi
cd "${ROOT_DIR}"

# Each line: id|public_symbol_claim|file_path|test_file|expected_triage
ROWS=(
  "agent_velocity_abuse|chio_guards::agent_velocity::AgentVelocityGuard|crates/chio-guards/src/agent_velocity.rs|crates/chio-conformance/tests/threats/agent_velocity_abuse.rs|IMPL-EXISTS-AND-PUBLIC"
  "audience_confusion|chio_kernel_core::capability_verify::verify_capability_full|crates/chio-kernel-core/src/capability_verify.rs|crates/chio-conformance/tests/threats/audience_confusion.rs|IMPL-EXISTS-AND-PUBLIC"
  "behavioral_sequence_attack|chio_guards::behavioral_sequence::BehavioralSequenceGuard|crates/chio-guards/src/behavioral_sequence.rs|crates/chio-conformance/tests/threats/behavioral_sequence_attack.rs|IMPL-EXISTS-AND-PUBLIC"
  "capability_token_theft|chio_kernel::execution_nonce::verify_execution_nonce|crates/chio-kernel/src/execution_nonce.rs|crates/chio-conformance/tests/threats/capability_token_theft.rs|IMPL-EXISTS-AND-PUBLIC"
  "cumulative_data_exfiltration|chio_guards::data_flow::DataFlowGuard|crates/chio-guards/src/data_flow.rs|crates/chio-conformance/tests/threats/cumulative_data_exfiltration.rs|IMPL-EXISTS-AND-PUBLIC"
  "delegation_chain_abuse|chio_kernel_core::capability_verify::verify_capability_with_trusted_and_floor|crates/chio-kernel-core/src/capability_verify.rs|crates/chio-conformance/tests/threats/delegation_chain_abuse.rs|IMPL-EXISTS-AND-PUBLIC"
  "device_key_extraction|chio_custody_hw::attestation::app_attest::verify_app_attest|crates/chio-custody-hw/src/attestation/app_attest.rs|crates/chio-conformance/tests/threats/device_key_extraction.rs|IMPL-EXISTS-AND-PUBLIC"
  "kernel_impersonation|chio_kernel_core::receipts::sign_receipt|crates/chio-kernel-core/src/receipts.rs|crates/chio-conformance/tests/threats/kernel_impersonation.rs|IMPL-EXISTS-AND-PUBLIC"
  "mobile_attestation_replay|chio_custody_hw::attestation::app_attest::verify_app_attest|crates/chio-custody-hw/src/attestation/app_attest.rs|crates/chio-conformance/tests/threats/mobile_attestation_replay.rs|IMPL-EXISTS-AND-PUBLIC"
  "native_channel_replay|chio_kernel::execution_nonce::verify_execution_nonce|crates/chio-kernel/src/execution_nonce.rs|crates/chio-conformance/tests/threats/native_channel_replay.rs|IMPL-EXISTS-AND-PUBLIC"
  "passkey_credential_theft|chio_credentials::verify_signed_passport_verifier_policy|crates/chio-credentials/src/registry.rs|crates/chio-conformance/tests/threats/passkey_credential_theft.rs|IMPL-EXISTS-AND-PUBLIC"
  "pii_phi_exposure|chio_guards::response_sanitization::ResponseSanitizationGuard|crates/chio-guards/src/response_sanitization.rs|crates/chio-conformance/tests/threats/pii_phi_exposure.rs|IMPL-EXISTS-AND-PUBLIC"
  "play_integrity_token_replay|chio_custody_hw::attestation::play_integrity::verify_play_integrity|crates/chio-custody-hw/src/attestation/play_integrity.rs|crates/chio-conformance/tests/threats/play_integrity_token_replay.rs|IMPL-EXISTS-AND-PUBLIC"
  "pq_signature_downgrade|chio_kernel_core::capability_verify::verify_capability_full|crates/chio-kernel-core/src/capability_verify.rs|crates/chio-conformance/tests/threats/pq_signature_downgrade.rs|IMPL-EXISTS-AND-PUBLIC"
  "resource_exhaustion_dos|chio_kernel::dispatch|crates/chio-kernel/src/kernel/mod.rs|crates/chio-conformance/tests/threats/resource_exhaustion_dos.rs|IMPL-PARTIAL"
  "ssrf_via_http_substrate|chio_egress_contract::HttpEgressContract|crates/chio-egress-contract/src/lib.rs|crates/chio-conformance/tests/threats/ssrf_via_http_substrate.rs|IMPL-EXISTS-AND-PUBLIC"
  "tee_quote_forgery|chio_tee_frame::schema::validate_signed|crates/chio-tee-frame/src/schema.rs|crates/chio-conformance/tests/threats/tee_quote_forgery.rs|IMPL-EXISTS-AND-PUBLIC"
  "tool_server_escape|chio_kernel::dispatch|crates/chio-kernel/src/kernel/mod.rs|crates/chio-conformance/tests/threats/tool_server_escape.rs|IMPL-PARTIAL"
  "wasm_guard_resource_exhaustion|(deferred)|crates/chio-wasm-guards/src/lib.rs|crates/chio-conformance/tests/threats/wasm_guard_resource_exhaustion.rs|BLOCKED-BY-ARCHITECTURE"
  "weights_hash_spoof|chio_weights::card::weights_hash_of|crates/chio-weights/src/card.rs|crates/chio-conformance/tests/threats/weights_hash_spoof.rs|IMPL-EXISTS-AND-PUBLIC"
)

count_implpub=0
count_implpub_unknown=0
count_implpartial=0
count_blocked=0

i=0
cat <<'EOF'
# Per-row threat triage

Date: 2026-05-08.

Generated by `scripts/triage-threat-rows.sh` from the current workspace.
Rows with public symbols but unknown test assertions are manual-review
items, not covered threat rows. A close-bar claim requires an actual deny
assertion, an accepted meta-only rewrite, or an explicit partial/blocker
classification.

## Per-row triage table

EOF
printf '| Row | ID | Symbol | File:Line(grep) | Symbol-found | Test-file | Test-asserts-deny? | Plan-triage | Final-triage |\n'
printf '|---|---|---|---|---|---|---|---|---|\n'

for row in "${ROWS[@]}"; do
  i=$((i + 1))
  IFS='|' read -r id sym file test plan_triage <<< "$row"
  # Extract last `::` segment for grep
  short="${sym##*::}"
  # Strip trailing parens / comment text in the symbol
  short="${short%% *}"
  short="${short%%(*}"
  if [ "${plan_triage}" = "BLOCKED-BY-ARCHITECTURE" ]; then
    line="(deferred)"
    found="(deferred)"
  elif [ -f "${file}" ]; then
    line=$(grep -nE "^pub (fn|struct|enum|trait|mod) ${short}" "${file}" | head -1 | cut -d: -f1)
    if [ -n "${line}" ]; then
      found="yes"
    else
      # Try without `^pub` prefix (might be `impl ... { pub fn X ... }`)
      line=$(grep -nE "(pub fn|pub struct) ${short}\b" "${file}" | head -1 | cut -d: -f1)
      if [ -n "${line}" ]; then
        found="yes"
      else
        found="no"
        line="-"
      fi
    fi
  else
    found="missing-file"
    line="-"
  fi

  # Check the test body
  if [ -f "${test}" ]; then
    if grep -E "Verdict::Deny|VerdictDeny|.deny\(|assert.*Err\(|assert.*Reject" "${test}" > /dev/null 2>&1; then
      asserts_deny="yes"
    elif grep -E "assert_file_contains|assert_threat_covered_by_corpus" "${test}" > /dev/null 2>&1; then
      asserts_deny="meta-only"
    else
      asserts_deny="?"
    fi
  else
    asserts_deny="missing-file"
  fi

  # Final triage
  if [ "${plan_triage}" = "BLOCKED-BY-ARCHITECTURE" ]; then
    final="BLOCKED-BY-ARCHITECTURE"
    count_blocked=$((count_blocked + 1))
  elif [ "${found}" = "yes" ] && [ "${asserts_deny}" = "yes" ]; then
    final="IMPL-EXISTS-AND-PUBLIC"
    count_implpub=$((count_implpub + 1))
  elif [ "${found}" = "yes" ] && [ "${asserts_deny}" = "meta-only" ]; then
    final="IMPL-EXISTS-AND-PUBLIC (test rewrite needed)"
    count_implpub=$((count_implpub + 1))
  elif [ "${found}" = "yes" ]; then
    final="IMPL-EXISTS-AND-PUBLIC (test assertion unknown - manual review needed)"
    count_implpub_unknown=$((count_implpub_unknown + 1))
  elif [ "${plan_triage}" = "IMPL-PARTIAL" ]; then
    final="IMPL-PARTIAL"
    count_implpartial=$((count_implpartial + 1))
  else
    final="IMPL-PARTIAL (unverified)"
    count_implpartial=$((count_implpartial + 1))
  fi

  printf '| %d | `%s` | `%s` | `%s:%s` | %s | `%s` | %s | %s | **%s** |\n' \
    "$i" "$id" "$sym" "$file" "$line" "$found" "$test" "$asserts_deny" "$plan_triage" "$final"
done

printf '\n## Tally\n\n'
printf -- '- IMPL-EXISTS-AND-PUBLIC with deny/assertion evidence: %d\n' "$count_implpub"
printf -- '- IMPL-EXISTS-AND-PUBLIC requiring manual test review: %d\n' "$count_implpub_unknown"
printf -- '- IMPL-EXISTS-PRIVATE: 0 (none in this triage)\n'
printf -- '- IMPL-PARTIAL: %d\n' "$count_implpartial"
printf -- '- BLOCKED-BY-ARCHITECTURE: %d\n' "$count_blocked"
total=$((count_implpub + count_implpub_unknown + count_implpartial + count_blocked))
printf -- '\n**Total**: %d (expected 20)\n' "$total"

if [ "$((count_implpub_unknown + count_implpartial + count_blocked))" -gt 2 ]; then
  printf '\n**Threat surface coverage gap** (`manual-review + IMPL-PARTIAL + BLOCKED-BY-ARCHITECTURE` count = %d > 2; review the unknown/partial/blocked rows before declaring coverage complete).\n' "$((count_implpub_unknown + count_implpartial + count_blocked))"
fi

cat <<'EOF'

## Reproducibility

Run `bash scripts/triage-threat-rows.sh` from the workspace root.
Any drift in this output means a row's symbol or test body changed.
EOF
