//! `cargo xtask snippets regen [--check]`
//!
//! Reads the tool-neutral snippet sources under `editors/snippets/` and
//! regenerates the editor-native snippet files for `vscode-chio` and
//! `zed-chio`. With `--check` the regen renders to memory and returns
//! a `Drift` error if the on-disk files do not match.
//!
//! The snippet schema (`editors/snippets/snippet.schema.json`) is
//! authoritative for the YAML shape. Any new field added to the YAML
//! must be reflected here.

use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use crate::XtaskError;

const VSCODE_OUTPUT: &str = "editors/vscode-chio/snippets/chio.code-snippets";
const ZED_OUTPUT: &str = "editors/zed-chio/snippets/chio.json";
const SNIPPET_SCHEMA: &str = "editors/snippets/snippet.schema.json";
const HEADER: &str =
    "// generated by `cargo xtask snippets regen` - edit editors/snippets/*.snippet.yaml instead";

#[derive(Debug, Deserialize)]
struct Snippet {
    id: String,
    scope: Vec<String>,
    prefix: String,
    description: String,
    body: Vec<String>,
}

/// Entry point invoked from `xtask::main`.
pub fn run(args: Vec<String>, workspace_root: &Path) -> Result<(), XtaskError> {
    let mut iter = args.into_iter();
    let sub = iter
        .next()
        .ok_or_else(|| XtaskError::Usage("snippets <subcommand>".into()))?;
    match sub.as_str() {
        "regen" => regen(iter.collect(), workspace_root),
        other => Err(XtaskError::Usage(format!(
            "unknown snippets subcommand: {other}"
        ))),
    }
}

fn regen(args: Vec<String>, workspace_root: &Path) -> Result<(), XtaskError> {
    let mut check_only = false;
    for arg in args {
        match arg.as_str() {
            "--check" => check_only = true,
            other => {
                return Err(XtaskError::Usage(format!(
                    "snippets regen: unknown flag: {other}"
                )));
            }
        }
    }

    let source_dir = workspace_root.join("editors/snippets");
    let schema_path = workspace_root.join(SNIPPET_SCHEMA);
    let snippets = load_snippets(&source_dir, &schema_path)?;

    let vscode_path = workspace_root.join(VSCODE_OUTPUT);
    let zed_path = workspace_root.join(ZED_OUTPUT);

    let vscode_body = render_vscode(&snippets)?;
    let zed_body = render_zed(&snippets)?;

    write_or_check(&vscode_path, &vscode_body, check_only)?;
    write_or_check(&zed_path, &zed_body, check_only)?;

    if check_only {
        println!("snippets in sync ({} snippet sources)", snippets.len());
    } else {
        println!(
            "regenerated {} and {} from {} snippet sources",
            VSCODE_OUTPUT,
            ZED_OUTPUT,
            snippets.len()
        );
    }
    Ok(())
}

fn load_snippets(source_dir: &Path, schema_path: &Path) -> Result<Vec<Snippet>, XtaskError> {
    let entries = fs::read_dir(source_dir)
        .map_err(|err| XtaskError::Io(source_dir.display().to_string(), err))?;
    let mut paths: Vec<PathBuf> = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|err| XtaskError::Io(source_dir.display().to_string(), err))?;
        let path = entry.path();
        let Some(name) = path.file_name().and_then(OsStr::to_str) else {
            continue;
        };
        if name.ends_with(".snippet.yaml") {
            paths.push(path);
        }
    }
    paths.sort();

    // Load and compile the snippet schema once. The schema is the
    // authoritative shape contract advertised in `editors/snippets/`,
    // so any new field must round-trip through this validator before
    // it reaches an editor manifest. Without this gate, additional or
    // misspelled keys (for example unknown scope IDs) silently pass
    // through `serde_yml::from_str` and ship into editor outputs.
    let schema_raw = fs::read_to_string(schema_path)
        .map_err(|err| XtaskError::Io(schema_path.display().to_string(), err))?;
    let schema_value: serde_json::Value = serde_json::from_str(&schema_raw)
        .map_err(|err| XtaskError::Json(schema_path.display().to_string(), err))?;
    let validator = jsonschema::options().build(&schema_value).map_err(|err| {
        XtaskError::Validation(format!(
            "snippet schema {}: compile failed: {err}",
            schema_path.display()
        ))
    })?;

    let mut out: Vec<Snippet> = Vec::with_capacity(paths.len());
    for path in &paths {
        let raw = fs::read_to_string(path)
            .map_err(|err| XtaskError::Io(path.display().to_string(), err))?;
        // First validate the YAML document against the snippet schema
        // (after a YAML -> JSON round trip), then deserialize into the
        // strongly-typed `Snippet` struct used by the renderers.
        let yaml_value: serde_yml::Value = serde_yml::from_str(&raw)
            .map_err(|err| XtaskError::Yaml(path.display().to_string(), err))?;
        let json_value = yaml_to_json(yaml_value).map_err(|err| {
            XtaskError::Validation(format!(
                "snippet {} cannot be expressed as JSON: {err}",
                path.display()
            ))
        })?;
        if let Err(errors) = collect_schema_errors(&validator, &json_value) {
            return Err(XtaskError::Validation(format!(
                "snippet {} violates schema {}:\n  - {}",
                path.display(),
                schema_path.display(),
                errors.join("\n  - ")
            )));
        }
        let parsed: Snippet = serde_json::from_value(json_value)
            .map_err(|err| XtaskError::Json(path.display().to_string(), err))?;
        out.push(parsed);
    }
    out.sort_by(|a, b| a.id.cmp(&b.id));
    Ok(out)
}

/// Convert a `serde_yml::Value` to `serde_json::Value` so the
/// JSON-schema validator can be applied. YAML supports a strict
/// superset of JSON, but the snippet schema only references JSON
/// types, so any YAML feature that cannot be re-serialized as JSON
/// (for example non-string mapping keys) is rejected here.
fn yaml_to_json(value: serde_yml::Value) -> Result<serde_json::Value, String> {
    let raw = serde_json::to_string(&value).map_err(|err| err.to_string())?;
    serde_json::from_str(&raw).map_err(|err| err.to_string())
}

fn collect_schema_errors(
    validator: &jsonschema::Validator,
    instance: &serde_json::Value,
) -> Result<(), Vec<String>> {
    if validator.is_valid(instance) {
        return Ok(());
    }
    let errors: Vec<String> = validator
        .iter_errors(instance)
        .map(|err| format!("{}: {err}", err.instance_path()))
        .collect();
    Err(errors)
}

fn render_vscode(snippets: &[Snippet]) -> Result<String, XtaskError> {
    // VSCode uses `*.code-snippets` JSON keyed by snippet name. The
    // file is JSON-with-comments so the generated header can ride on
    // the leading `//`.
    let mut body = String::new();
    body.push_str(HEADER);
    body.push('\n');
    body.push_str("{\n");
    for (idx, snippet) in snippets.iter().enumerate() {
        let entry = serde_json::json!({
            "scope": snippet.scope.join(","),
            "prefix": snippet.prefix,
            "body": snippet.body,
            "description": snippet.description,
        });
        let entry_str = serde_json::to_string_pretty(&entry)
            .map_err(|err| XtaskError::Json("vscode snippet".to_string(), err))?;
        let key = serde_json::to_string(&snippet.id)
            .map_err(|err| XtaskError::Json("vscode snippet key".to_string(), err))?;
        body.push_str("  ");
        body.push_str(&key);
        body.push_str(": ");
        body.push_str(&indent_after_first_line(&entry_str, "  "));
        if idx + 1 < snippets.len() {
            body.push(',');
        }
        body.push('\n');
    }
    body.push_str("}\n");
    Ok(body)
}

fn render_zed(snippets: &[Snippet]) -> Result<String, XtaskError> {
    // Zed reads snippet JSON keyed by snippet name. Snippet activation
    // is scoped by the filename under snippets/, so xtask writes the
    // Chio pack to chio.json rather than the global snippets.json.
    let mut entries: serde_json::Map<String, serde_json::Value> = serde_json::Map::new();
    for snippet in snippets {
        let entry = serde_json::json!({
            "prefix": snippet.prefix,
            "body": snippet.body,
            "description": snippet.description,
            "scope": snippet.scope,
        });
        entries.insert(snippet.id.clone(), entry);
    }
    let payload = serde_json::Value::Object(entries);
    let json = serde_json::to_string_pretty(&payload)
        .map_err(|err| XtaskError::Json("zed snippets".to_string(), err))?;
    Ok(format!("{HEADER}\n{json}\n"))
}

fn indent_after_first_line(s: &str, indent: &str) -> String {
    let mut lines = s.lines();
    let mut out = String::new();
    if let Some(first) = lines.next() {
        out.push_str(first);
    }
    for line in lines {
        out.push('\n');
        out.push_str(indent);
        out.push_str(line);
    }
    out
}

fn write_or_check(path: &Path, body: &str, check_only: bool) -> Result<(), XtaskError> {
    if let Some(parent) = path.parent() {
        if !check_only {
            fs::create_dir_all(parent)
                .map_err(|err| XtaskError::Io(parent.display().to_string(), err))?;
        }
    }
    if check_only {
        let existing = fs::read_to_string(path)
            .map_err(|err| XtaskError::Io(path.display().to_string(), err))?;
        if existing != body {
            return Err(XtaskError::Drift(format!(
                "{} is stale; rerun `cargo xtask snippets regen`",
                path.display()
            )));
        }
        Ok(())
    } else {
        fs::write(path, body).map_err(|err| XtaskError::Io(path.display().to_string(), err))?;
        Ok(())
    }
}
