// @chio-protocol/browser entry: re-exports the verify_receipt wasm-bindgen
// surface from the wasm-pack output under ../pkg/.

// The pkg/ directory is generated by build-wasm.sh before TypeScript
// compilation.

import { verify_receipt } from '../pkg/chio_kernel_browser.js';

export { verify_receipt };
export type VerifyReceiptResultJson = ReturnType<typeof verify_receipt>;

// Convenience helper: parses an envelope from a hex string.
export function verifyReceiptHex(envelopeHex: string, trustedIssuers?: string | string[]): unknown {
  const normalized = envelopeHex.startsWith("0x") || envelopeHex.startsWith("0X")
    ? envelopeHex.slice(2)
    : envelopeHex;
  if (normalized.length === 0 || normalized.length % 2 !== 0 || !/^[0-9a-fA-F]+$/.test(normalized)) {
    throw new Error("receipt envelope hex must be a non-empty even-length hex string");
  }
  const bytes = Uint8Array.from(normalized.match(/.{2}/g)!.map(b => parseInt(b, 16)));
  return verify_receipt(bytes, trustedIssuers);
}
