// @chio-protocol/browser entry: re-exports the verify_receipt wasm-bindgen
// surface from the wasm-pack output under ../pkg/.

// The pkg/ directory is generated by build-wasm.sh before TypeScript
// compilation.

import { verify_receipt } from '../pkg/chio_kernel_browser.js';

export { verify_receipt };
export type VerifyReceiptResultJson = ReturnType<typeof verify_receipt>;

// Convenience helper: parses an envelope from a hex string.
export function verifyReceiptHex(envelopeHex: string, trustedIssuers?: string | string[]): unknown {
  const normalized = envelopeHex.startsWith('0x') ? envelopeHex.slice(2) : envelopeHex;
  if (normalized.length % 2 !== 0) {
    throw new Error('receipt hex must have an even number of characters');
  }
  if (!/^[0-9a-fA-F]*$/.test(normalized)) {
    throw new Error('receipt hex must contain only hexadecimal characters');
  }

  const bytes = Uint8Array.from((normalized.match(/.{2}/g) ?? []).map(b => Number.parseInt(b, 16)));
  return verify_receipt(bytes, trustedIssuers);
}
