// @chio-protocol/browser entry: re-exports the verify_receipt wasm-bindgen
// surface from the wasm-pack output under ./pkg/.

// The pkg/ directory is generated by build-wasm.sh; until that runs, the
// import path may not resolve. The runtime fix is `npm run build:wasm`.

export { verify_receipt } from './pkg/chio_kernel_browser';
export type { VerifyReceiptResultJson } from './pkg/chio_kernel_browser';

// Convenience helper: parses an envelope from a hex string.
export function verifyReceiptHex(envelopeHex: string, trustedIssuers?: string | string[]): unknown {
  const bytes = Uint8Array.from(envelopeHex.match(/.{1,2}/g)!.map(b => parseInt(b, 16)));
  return verify_receipt(bytes, trustedIssuers);
}
