[package]
name = "chio-core"
description = "Core types for the Chio protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
publish = false

[package.metadata.chio]
public_entrypoint = true

[lib]
name = "chio_core"

[[bench]]
name = "core_primitives"
harness = false

[dependencies]
chio-appraisal = { workspace = true }
chio-autonomy = { workspace = true }
chio-core-types = { workspace = true }
chio-credit = { workspace = true }
chio-federation = { workspace = true }
chio-governance = { workspace = true }
chio-listing = { workspace = true }
chio-market = { workspace = true }
chio-open-market = { workspace = true }
chio-underwriting = { workspace = true }
chio-web3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
url = "2"

[features]
default = []
pq = ["chio-core-types/pq"]

[dev-dependencies]
serde_json = { workspace = true }
proptest = { workspace = true }
criterion = { workspace = true }

[lints]
workspace = true
