use super::*;

pub(super) fn challenge_route_state(
    deployment: &Deployment,
    executor: Arc<dyn FindingChallengeSubmissionExecutor>,
) -> TrustServiceState {
    let config = TrustServiceConfig {
        transport: Default::default(),
        listen: std::net::SocketAddr::from(([127, 0, 0, 1], 0)),
        service_token: "challenge-service-secret".to_string(),
        tenant_read_tokens: BTreeMap::new(),
        authority_workload_token: None,
        receipt_db_path: None,
        receipt_query_snapshot_quota_bytes: 2_147_483_648,
        revocation_db_path: None,
        authority_seed_path: None,
        authority_db_path: None,
        authority_keyring_config_path: None,
        authority_keyring_receipt_anchor_root: None,
        budget_db_path: None,
        joint_authority_db_path: None,
        fiscal_runtime: None,
        enterprise_providers_file: None,
        federation_policies_file: None,
        scim_lifecycle_file: None,
        verifier_policies_file: None,
        verifier_challenge_db_path: None,
        passport_statuses_file: None,
        passport_issuance_offers_file: None,
        certification_registry_file: None,
        certification_discovery_file: None,
        issuance_policy: None,
        runtime_assurance_policy: None,
        advertise_url: None,
        allow_local_peer_urls: true,
        certification_public_metadata_ttl_seconds: 300,
        peer_urls: Vec::new(),
        cluster_sync_interval: std::time::Duration::from_millis(25),
        roster_policy: None,
        memory_budget: chio_kernel::MemoryBudgetConfig::defaults(),
        finding_market: Some(market_config()),
    };
    TrustServiceState {
        finding_challenge_clock: Arc::new(chio_security_types::clock::SystemClock),
        config,
        authority_keyring: None,
        authority_keyring_seed_path: None,
        joint_authority_store: Some(Arc::clone(&deployment._authority)),
        fiscal_runtime: None,
        budget_store: None,
        revocation_store: None,
        receipt_store: None,
        enterprise_provider_registry: None,
        verifier_policy_registry: None,
        federation_admission_rate_limiter: Arc::new(Mutex::new(
            FederationAdmissionRateLimiter::default(),
        )),
        cluster: None,
        cluster_progress: None,
        finding_rail: Some(deployment.rail.clone()),
        finding_purchase_executor: None,
        finding_purchase_execution_lane: Arc::new(tokio::sync::Semaphore::new(1)),
        finding_proof_egress_lane: Arc::new(tokio::sync::Semaphore::new(1)),
        finding_seller_submission_executor: None,
        finding_seller_submission_lane: Arc::new(tokio::sync::Semaphore::new(1)),
        finding_challenge_submission_lane: Arc::new(tokio::sync::Semaphore::new(1)),
        finding_authority_status_resolver: Some(Arc::new(TestAuthorityStatusResolver::live())),
        finding_challenge_executor: Some(executor),
    }
}
