#![no_main]

use arbitrary::{Arbitrary, Unstructured};
use chio_core::capability::MonetaryAmount;
use chio_core::crypto::{Keypair, PublicKey};
use chio_manifest::{
    sign_manifest, validate_manifest, verify_manifest, LatencyHint, ManifestError, PricingModel,
    SignedManifest, ToolDefinition, ToolManifest, ToolPricing, TOOL_MANIFEST_SCHEMA,
};
use libfuzzer_sys::fuzz_target;

const MAX_RAW_BYTES: usize = 16 * 1024;
const MAX_TEXT_CHARS: usize = 128;
const MAX_TOOLS: usize = 8;
const MANIFEST_VECTOR_SEEDS: &[&[u8]] = &[
    include_bytes!("../corpus/fuzz_manifest_roundtrip/binding-valid_signed_manifest.json"),
    include_bytes!("../corpus/fuzz_manifest_roundtrip/binding-tampered_manifest_signature.json"),
    include_bytes!("../corpus/fuzz_manifest_roundtrip/binding-mismatched_embedded_public_key.json"),
    include_bytes!("../corpus/fuzz_manifest_roundtrip/binding-duplicate_tool_name_manifest.json"),
    include_bytes!("../corpus/fuzz_manifest_roundtrip/binding-invalid_embedded_public_key.json"),
    include_bytes!(
        "../corpus/fuzz_manifest_roundtrip/malformed-signed-manifest-unknown-fields.json"
    ),
];

#[derive(Arbitrary, Debug)]
struct ManifestInput {
    raw_json: Vec<u8>,
    key_seed: [u8; 32],
    server_selector: u8,
    tool_count: u8,
    duplicate_names: bool,
    include_pricing: bool,
    include_output_schema: bool,
    description: String,
}

fn trim(input: &str) -> String {
    input.chars().take(MAX_TEXT_CHARS).collect()
}

fn generated_manifest(input: &ManifestInput, keypair: &Keypair) -> ToolManifest {
    let count = usize::from(input.tool_count % MAX_TOOLS as u8) + 1;
    let description = trim(&input.description);
    let mut tools = Vec::with_capacity(count);

    for idx in 0..count {
        let name = if input.duplicate_names && idx > 0 {
            "tool_0".to_string()
        } else {
            format!("tool_{idx}")
        };
        tools.push(ToolDefinition {
            name,
            description: if description.is_empty() {
                format!("Generated fuzz tool {idx}")
            } else {
                description.clone()
            },
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "path": { "type": "string" },
                    "limit": { "type": "integer", "minimum": 0 }
                }
            }),
            output_schema: input.include_output_schema.then(|| {
                serde_json::json!({
                    "type": "object",
                    "properties": {
                        "ok": { "type": "boolean" }
                    }
                })
            }),
            pricing: input.include_pricing.then(|| ToolPricing {
                pricing_model: PricingModel::PerInvocation,
                base_price: Some(MonetaryAmount {
                    units: 1,
                    currency: "USD".to_string(),
                }),
                unit_price: None,
                billing_unit: Some("invocation".to_string()),
            }),
            has_side_effects: idx % 2 == 0,
            latency_hint: Some(match idx % 4 {
                0 => LatencyHint::Instant,
                1 => LatencyHint::Fast,
                2 => LatencyHint::Moderate,
                _ => LatencyHint::Slow,
            }),
        });
    }

    ToolManifest {
        schema: TOOL_MANIFEST_SCHEMA.to_string(),
        server_id: format!("srv-fuzz-{}", input.server_selector),
        name: "Fuzz Tool Server".to_string(),
        description: Some("Generated by fuzz target".to_string()),
        version: "0.1.0".to_string(),
        tools,
        required_permissions: None,
        public_key: keypair.public_key().to_hex(),
    }
}

fn has_duplicate_tool_names(manifest: &ToolManifest) -> bool {
    let mut names = std::collections::HashSet::new();
    manifest
        .tools
        .iter()
        .any(|tool| !names.insert(tool.name.as_str()))
}

fn is_exact_seed(data: &[u8], seeds: &[&[u8]]) -> bool {
    seeds.contains(&data)
}

fn exercise_signed_manifest(signed: &SignedManifest) {
    let structure_valid = validate_manifest(&signed.manifest).is_ok();
    let signature_valid = signed
        .signer_key
        .verify_canonical(&signed.manifest, &signed.signature)
        .unwrap_or(false);
    let embedded_key = PublicKey::from_hex(&signed.manifest.public_key);

    if structure_valid && signature_valid {
        if let Err(error) = verify_manifest(signed, &signed.signer_key) {
            panic!("structurally valid signed manifest should verify: {error}");
        }
    } else {
        assert!(verify_manifest(signed, &signed.signer_key).is_err());
    }

    if let Ok(embedded_key) = embedded_key {
        let embedded_matches_signer = embedded_key == signed.signer_key;
        let manifest_verify = verify_manifest(signed, &embedded_key);
        if structure_valid && signature_valid && embedded_matches_signer {
            assert!(manifest_verify.is_ok());
        } else {
            assert!(manifest_verify.is_err());
        }
    }
}

fn bool_expected(value: &serde_json::Value, key: &str) -> Option<bool> {
    value
        .get("expected")
        .and_then(|expected| expected.get(key))
        .and_then(|value| value.as_bool())
}

fn exercise_manifest_case(case: &serde_json::Value, enforce_expected: bool) {
    let Some(signed_value) = case.get("signed_manifest") else {
        return;
    };
    let Ok(signed) = serde_json::from_value::<SignedManifest>(signed_value.clone()) else {
        return;
    };

    if enforce_expected {
        if let Some(expected_structure) = bool_expected(case, "structure_valid") {
            assert_eq!(
                validate_manifest(&signed.manifest).is_ok(),
                expected_structure
            );
        }
        if let Some(expected_signature) = bool_expected(case, "signature_valid") {
            let actual = signed
                .signer_key
                .verify_canonical(&signed.manifest, &signed.signature)
                .unwrap_or(false);
            assert_eq!(actual, expected_signature);
        }
        if let Some(expected_embedded_key) = bool_expected(case, "embedded_public_key_valid") {
            assert_eq!(
                PublicKey::from_hex(&signed.manifest.public_key).is_ok(),
                expected_embedded_key
            );
        }
        if let Some(expected_embedded_match) =
            bool_expected(case, "embedded_public_key_matches_signer")
        {
            let actual = PublicKey::from_hex(&signed.manifest.public_key)
                .map(|key| key == signed.signer_key)
                .unwrap_or(false);
            assert_eq!(actual, expected_embedded_match);
        }
        if let Some(expected_body) = case
            .get("manifest_body_canonical_json")
            .and_then(|value| value.as_str())
        {
            let actual = match chio_core::canonical_json_string(&signed.manifest) {
                Ok(actual) => actual,
                Err(error) => panic!("manifest body should canonicalize: {error}"),
            };
            assert_eq!(actual, expected_body);
        }
    }

    exercise_signed_manifest(&signed);
}

fn exercise_manifest_vector(value: &serde_json::Value, enforce_expected: bool) {
    if let Some(cases) = value.get("cases").and_then(|cases| cases.as_array()) {
        for case in cases {
            exercise_manifest_case(case, enforce_expected);
        }
    } else {
        exercise_manifest_case(value, enforce_expected);
    }
}

fn exercise_manifest(manifest: &ToolManifest, keypair: &Keypair, should_be_valid: bool) {
    let validation = validate_manifest(manifest);
    if has_duplicate_tool_names(manifest) {
        assert!(matches!(
            validation,
            Err(ManifestError::DuplicateToolName(_))
        ));
        return;
    }

    if should_be_valid {
        if let Err(error) = &validation {
            panic!("generated manifest should validate: {error}");
        }
    }

    if validation.is_ok() {
        let signed = match sign_manifest(manifest, keypair) {
            Ok(signed) => signed,
            Err(error) => panic!("valid manifest should sign: {error}"),
        };
        if let Err(error) = verify_manifest(&signed, &keypair.public_key()) {
            panic!("signed manifest should verify: {error}");
        }

        let encoded = match serde_json::to_vec(&signed) {
            Ok(encoded) => encoded,
            Err(error) => panic!("signed manifest should serialize: {error}"),
        };
        let restored: chio_manifest::SignedManifest = match serde_json::from_slice(&encoded) {
            Ok(restored) => restored,
            Err(error) => panic!("signed manifest should deserialize: {error}"),
        };
        if let Err(error) = verify_manifest(&restored, &keypair.public_key()) {
            panic!("restored signed manifest should verify: {error}");
        }

        let mut tampered = restored.clone();
        tampered.manifest.version.push_str(".tampered");
        assert!(verify_manifest(&tampered, &keypair.public_key()).is_err());
    }
}

fn exercise_raw(data: &[u8], keypair: &Keypair) {
    if data.len() > MAX_RAW_BYTES {
        return;
    }

    let Ok(value) = serde_json::from_slice::<serde_json::Value>(data) else {
        return;
    };

    exercise_manifest_vector(&value, is_exact_seed(data, MANIFEST_VECTOR_SEEDS));

    if let Ok(signed) = serde_json::from_value::<SignedManifest>(value.clone()) {
        exercise_signed_manifest(&signed);
    }
    if let Ok(manifest) = serde_json::from_value::<ToolManifest>(value) {
        exercise_manifest(&manifest, keypair, false);
    }
}

fn exercise_generated(input: ManifestInput) {
    let keypair = Keypair::from_seed(&input.key_seed);

    exercise_raw(&input.raw_json, &keypair);

    let generated = generated_manifest(&input, &keypair);
    exercise_manifest(&generated, &keypair, !has_duplicate_tool_names(&generated));
}

fuzz_target!(|data: &[u8]| {
    let keypair = Keypair::from_seed(&[0x42; 32]);
    exercise_raw(data, &keypair);

    let mut unstructured = Unstructured::new(data);
    if let Ok(input) = ManifestInput::arbitrary(&mut unstructured) {
        exercise_generated(input);
    }
});
