use super::*;

pub(crate) fn dispatch_chio_pheromone_command(
    command: ChioPheromoneCommands,
) -> Result<(), CliError> {
    match command {
        ChioPheromoneCommands::Receive {
            batch,
            transit_policy,
            proof_package,
            trust_bundle,
            context,
            store,
            now_unix_ms,
            report,
        } => cmd_chio_pheromone_receive(
            &batch,
            &transit_policy,
            &proof_package,
            &trust_bundle,
            &context,
            &store,
            now_unix_ms,
            &report,
        ),
        ChioPheromoneCommands::Query {
            store,
            subject_class,
            namespace,
            reputation_epoch,
            peer_weights,
            now_unix_ms,
            report,
        } => cmd_chio_pheromone_query(
            &store,
            &subject_class,
            &namespace,
            reputation_epoch,
            &peer_weights,
            now_unix_ms,
            &report,
        ),
        ChioPheromoneCommands::Relay { command } => match command {
            ChioPheromoneRelayCommands::Lint {
                peer_directory,
                peer_directory_state,
                profile,
                trusted_issuers,
                report,
            } => cmd_chio_pheromone_relay_lint(
                peer_directory.as_deref(),
                peer_directory_state.as_deref(),
                profile.into(),
                trusted_issuers.as_deref(),
                &report,
            ),
            ChioPheromoneRelayCommands::Serve {
                listen,
                store,
                peer_directory,
                peer_directory_state,
                profile,
                trusted_issuers,
                transit_policy,
                proof_package,
                trust_bundle,
                context,
                report_dir,
                operator_token_env,
                iroh_enable,
                iroh_transport_directory,
                iroh_transport_directory_state,
                iroh_transport_key,
                iroh_bind_addr,
                iroh_relay_url,
                iroh_lanes,
            } => cmd_chio_pheromone_relay_serve(
                &listen,
                &store,
                peer_directory.as_deref(),
                peer_directory_state.as_deref(),
                profile.into(),
                trusted_issuers.as_deref(),
                &transit_policy,
                &proof_package,
                &trust_bundle,
                &context,
                &report_dir,
                operator_token_env.as_deref(),
                iroh_enable,
                iroh_transport_directory.as_deref(),
                iroh_transport_directory_state.as_deref(),
                iroh_transport_key.as_deref(),
                &iroh_bind_addr,
                &iroh_relay_url,
                &iroh_lanes,
            ),
            ChioPheromoneRelayCommands::Enqueue {
                store,
                batch,
                transit_policy,
                trust_bundle,
                peer_directory,
                peer_directory_state,
                profile,
                trusted_issuers,
                now_unix_ms,
                report,
            } => cmd_chio_pheromone_relay_enqueue(
                &store,
                &batch,
                &transit_policy,
                &trust_bundle,
                peer_directory.as_deref(),
                peer_directory_state.as_deref(),
                profile.into(),
                trusted_issuers.as_deref(),
                now_unix_ms,
                &report,
            ),
            ChioPheromoneRelayCommands::Tick {
                store,
                peer_directory,
                peer_directory_state,
                profile,
                trusted_issuers,
                now_unix_ms,
                max_batches,
                signing_key,
                report,
                report_dir,
                iroh_enable,
                iroh_transport_directory,
                iroh_transport_directory_state,
                iroh_transport_key,
                iroh_bind_addr,
                iroh_relay_url,
                iroh_peer_addr,
                iroh_lanes,
            } => cmd_chio_pheromone_relay_tick(
                &store,
                peer_directory.as_deref(),
                peer_directory_state.as_deref(),
                profile.into(),
                trusted_issuers.as_deref(),
                now_unix_ms,
                max_batches,
                &signing_key,
                &report,
                report_dir.as_deref(),
                iroh_enable,
                iroh_transport_directory.as_deref(),
                iroh_transport_directory_state.as_deref(),
                iroh_transport_key.as_deref(),
                &iroh_bind_addr,
                &iroh_relay_url,
                &iroh_peer_addr,
                &iroh_lanes,
            ),
            ChioPheromoneRelayCommands::Catchup {
                store,
                peer,
                peer_directory_state,
                profile,
                trusted_issuers,
                now_unix_ms,
                treaty,
                after_cursor,
                limit,
                report,
            } => cmd_chio_pheromone_relay_catchup(
                &store,
                &peer,
                peer_directory_state.as_deref(),
                profile.into(),
                trusted_issuers.as_deref(),
                now_unix_ms,
                &treaty,
                &after_cursor,
                limit,
                &report,
            ),
            ChioPheromoneRelayCommands::Status { store, report } => {
                cmd_chio_pheromone_relay_status(&store, &report)
            }
            ChioPheromoneRelayCommands::Observe {
                store,
                peer_directory_state,
                profile,
                trusted_issuers,
                report_dir,
                limit,
                report,
            } => cmd_chio_pheromone_relay_observe(
                &store,
                &peer_directory_state,
                profile.into(),
                &trusted_issuers,
                &report_dir,
                limit,
                &report,
            ),
            ChioPheromoneRelayCommands::Metrics {
                store,
                format,
                output,
            } => cmd_chio_pheromone_relay_metrics(&store, format.into(), &output),
            ChioPheromoneRelayCommands::Alert { command } => match command {
                ChioPheromoneRelayAlertCommands::Evaluate {
                    observability_report,
                    event_dir,
                    routing_profile,
                    suppression_state,
                    now_unix_ms,
                    report,
                } => cmd_chio_pheromone_relay_alert_evaluate(
                    &observability_report,
                    &event_dir,
                    &routing_profile,
                    &suppression_state,
                    now_unix_ms,
                    &report,
                ),
                ChioPheromoneRelayAlertCommands::Handoff {
                    alert_report,
                    trend_report,
                    routing_profile,
                    handoff_profile,
                    now_unix_ms,
                    report,
                } => cmd_chio_pheromone_relay_alert_handoff(
                    &alert_report,
                    &trend_report,
                    &routing_profile,
                    &handoff_profile,
                    now_unix_ms,
                    &report,
                ),
                ChioPheromoneRelayAlertCommands::Normalize {
                    profile,
                    input_dir,
                    now_unix_ms,
                    out_dir,
                    report,
                } => cmd_chio_pheromone_relay_alert_normalize(
                    &profile,
                    &input_dir,
                    now_unix_ms,
                    &out_dir,
                    &report,
                ),
                ChioPheromoneRelayAlertCommands::Delivery { command } => match command {
                    ChioPheromoneRelayAlertDeliveryCommands::Import {
                        handoff_report,
                        delivery_profile,
                        evidence_dir,
                        now_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_delivery_import(
                        &handoff_report,
                        &delivery_profile,
                        &evidence_dir,
                        now_unix_ms,
                        &report,
                    ),
                    ChioPheromoneRelayAlertDeliveryCommands::Acknowledge {
                        handoff_report,
                        delivery_report,
                        delivery_profile,
                        now_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_delivery_acknowledge(
                        &handoff_report,
                        &delivery_report,
                        &delivery_profile,
                        now_unix_ms,
                        &report,
                    ),
                    ChioPheromoneRelayAlertDeliveryCommands::Drift {
                        handoff_reports_dir,
                        delivery_reports_dir,
                        delivery_profile,
                        since_unix_ms,
                        until_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_delivery_drift(
                        &handoff_reports_dir,
                        &delivery_reports_dir,
                        &delivery_profile,
                        since_unix_ms,
                        until_unix_ms,
                        &report,
                    ),
                    ChioPheromoneRelayAlertDeliveryCommands::DriftWindow {
                        handoff_reports_dir,
                        delivery_reports_dir,
                        delivery_profile,
                        since_unix_ms,
                        until_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_delivery_drift_window(
                        &handoff_reports_dir,
                        &delivery_reports_dir,
                        &delivery_profile,
                        since_unix_ms,
                        until_unix_ms,
                        &report,
                    ),
                },
                ChioPheromoneRelayAlertCommands::Review {
                    handoff_report,
                    delivery_report,
                    acknowledgement_report,
                    drift_report,
                    route_owner_profile,
                    now_unix_ms,
                    report,
                } => cmd_chio_pheromone_relay_alert_review(
                    &handoff_report,
                    &delivery_report,
                    &acknowledgement_report,
                    &drift_report,
                    &route_owner_profile,
                    now_unix_ms,
                    &report,
                ),
                ChioPheromoneRelayAlertCommands::Assurance { command } => match command {
                    ChioPheromoneRelayAlertAssuranceCommands::Package {
                        alert_report,
                        trend_report,
                        handoff_report,
                        normalization_report,
                        delivery_report,
                        acknowledgement_report,
                        drift_report,
                        review_packet,
                        now_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_assurance_package(
                        &alert_report,
                        &trend_report,
                        &handoff_report,
                        &normalization_report,
                        &delivery_report,
                        &acknowledgement_report,
                        &drift_report,
                        &review_packet,
                        now_unix_ms,
                        &report,
                    ),
                    ChioPheromoneRelayAlertAssuranceCommands::Export {
                        package,
                        alert_report,
                        trend_report,
                        handoff_report,
                        normalization_report,
                        delivery_report,
                        acknowledgement_report,
                        drift_report,
                        review_packet,
                        retention_profile,
                        signing_key,
                        now_unix_ms,
                        out_dir,
                        report,
                    } => cmd_chio_pheromone_relay_alert_assurance_export(
                        &package,
                        &alert_report,
                        &trend_report,
                        &handoff_report,
                        &normalization_report,
                        &delivery_report,
                        &acknowledgement_report,
                        &drift_report,
                        &review_packet,
                        &retention_profile,
                        &signing_key,
                        now_unix_ms,
                        &out_dir,
                        &report,
                    ),
                    ChioPheromoneRelayAlertAssuranceCommands::Verify {
                        bundle_dir,
                        trusted_exporters,
                        now_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_assurance_verify(
                        &bundle_dir,
                        &trusted_exporters,
                        now_unix_ms,
                        &report,
                    ),
                    ChioPheromoneRelayAlertAssuranceCommands::Replay {
                        bundle_dir,
                        trusted_exporters,
                        now_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_assurance_replay(
                        &bundle_dir,
                        &trusted_exporters,
                        now_unix_ms,
                        &report,
                    ),
                    ChioPheromoneRelayAlertAssuranceCommands::Retention { command } => {
                        match command {
                            ChioPheromoneRelayAlertAssuranceRetentionCommands::Plan {
                                bundle_root,
                                retention_profile,
                                now_unix_ms,
                                report,
                            } => cmd_chio_pheromone_relay_alert_assurance_retention_plan(
                                &bundle_root,
                                &retention_profile,
                                now_unix_ms,
                                &report,
                            ),
                            ChioPheromoneRelayAlertAssuranceRetentionCommands::Handoff {
                                command,
                            } => match command {
                                ChioPheromoneRelayAlertAssuranceRetentionHandoffCommands::Review {
                                    evidence,
                                    profile,
                                    package_report,
                                    now_unix_ms,
                                    report,
                                } => cmd_chio_pheromone_relay_alert_assurance_retention_handoff_review(
                                    &evidence,
                                    &profile,
                                    &package_report,
                                    now_unix_ms,
                                    &report,
                                ),
                            },
                            ChioPheromoneRelayAlertAssuranceRetentionCommands::ExternalReview {
                                package_dir,
                                source_report_dir,
                                trusted_packagers,
                                trusted_exporters,
                                profile,
                                since_unix_ms,
                                until_unix_ms,
                                now_unix_ms,
                                report,
                            } => cmd_chio_pheromone_relay_alert_assurance_retention_external_review(
                                &package_dir,
                                &source_report_dir,
                                &trusted_packagers,
                                &trusted_exporters,
                                &profile,
                                since_unix_ms,
                                until_unix_ms,
                                now_unix_ms,
                                &report,
                            ),
                        }
                    }
                    ChioPheromoneRelayAlertAssuranceCommands::RecoveryDrill {
                        bundle_dir,
                        trusted_exporters,
                        case,
                        now_unix_ms,
                        report,
                    } => cmd_chio_pheromone_relay_alert_assurance_recovery_drill(
                        &bundle_dir,
                        &trusted_exporters,
                        &case,
                        now_unix_ms,
                        &report,
                    ),
                    ChioPheromoneRelayAlertAssuranceCommands::Archive { command } => {
                        match command {
                            ChioPheromoneRelayAlertAssuranceArchiveCommands::Plan {
                                bundle_root,
                                trusted_exporters,
                                archive_profile,
                                retention_profile,
                                now_unix_ms,
                                report,
                            } => cmd_chio_pheromone_relay_alert_assurance_archive_plan(
                                &bundle_root,
                                &trusted_exporters,
                                &archive_profile,
                                &retention_profile,
                                now_unix_ms,
                                &report,
                            ),
                            ChioPheromoneRelayAlertAssuranceArchiveCommands::Package { command } => {
                                match command {
                                    ChioPheromoneRelayAlertAssuranceArchivePackageCommands::Create {
                                        bundle_root,
                                        trusted_exporters,
                                        archive_report,
                                        closeout_report,
                                        signing_key,
                                        package_id,
                                        packager_key_id,
                                        package_generation,
                                        previous_package_report,
                                        now_unix_ms,
                                        out,
                                        report,
                                    } => cmd_chio_pheromone_relay_alert_assurance_archive_package_create(
                                        &bundle_root,
                                        &trusted_exporters,
                                        &archive_report,
                                        &closeout_report,
                                        &signing_key,
                                        &package_id,
                                        &packager_key_id,
                                        package_generation,
                                        previous_package_report.as_deref(),
                                        now_unix_ms,
                                        &out,
                                        &report,
                                    ),
                                    ChioPheromoneRelayAlertAssuranceArchivePackageCommands::Verify {
                                        package,
                                        trusted_packagers,
                                        trusted_exporters,
                                        archive_report,
                                        closeout_report,
                                        now_unix_ms,
                                        report,
                                    } => cmd_chio_pheromone_relay_alert_assurance_archive_package_verify(
                                        &package,
                                        &trusted_packagers,
                                        &trusted_exporters,
                                        &archive_report,
                                        &closeout_report,
                                        now_unix_ms,
                                        &report,
                                    ),
                                    ChioPheromoneRelayAlertAssuranceArchivePackageCommands::Extract {
                                        package,
                                        trusted_packagers,
                                        trusted_exporters,
                                        archive_report,
                                        closeout_report,
                                        out_dir,
                                        now_unix_ms,
                                        report,
                                    } => cmd_chio_pheromone_relay_alert_assurance_archive_package_extract(
                                        &package,
                                        &trusted_packagers,
                                        &trusted_exporters,
                                        &archive_report,
                                        &closeout_report,
                                        &out_dir,
                                        now_unix_ms,
                                        &report,
                                    ),
                                }
                            }
                            ChioPheromoneRelayAlertAssuranceArchiveCommands::PhysicalDrill {
                                command,
                            } => match command {
                                ChioPheromoneRelayAlertAssurancePhysicalDrillCommands::Review {
                                    evidence,
                                    package_report,
                                    now_unix_ms,
                                    report,
                                } => cmd_chio_pheromone_relay_alert_assurance_physical_drill_review(
                                    &evidence,
                                    &package_report,
                                    now_unix_ms,
                                    &report,
                                ),
                            },
                            ChioPheromoneRelayAlertAssuranceArchiveCommands::RestoreDrill {
                                command,
                            } => match command {
                                ChioPheromoneRelayAlertAssuranceArchiveRestoreDrillCommands::Review {
                                    package_dir,
                                    source_report_dir,
                                    trusted_packagers,
                                    trusted_exporters,
                                    restore_profile,
                                    now_unix_ms,
                                    report,
                                } => cmd_chio_pheromone_relay_alert_assurance_archive_restore_drill_review(
                                    &package_dir,
                                    &source_report_dir,
                                    &trusted_packagers,
                                    &trusted_exporters,
                                    &restore_profile,
                                    now_unix_ms,
                                    &report,
                                ),
                            },
                        }
                    }
                    ChioPheromoneRelayAlertAssuranceCommands::Closeout { command } => {
                        match command {
                            ChioPheromoneRelayAlertAssuranceCloseoutCommands::Review {
                                bundle_root,
                                trusted_exporters,
                                closeout_profile,
                                retention_profile,
                                now_unix_ms,
                                report,
                            } => cmd_chio_pheromone_relay_alert_assurance_closeout_review(
                                &bundle_root,
                                &trusted_exporters,
                                &closeout_profile,
                                &retention_profile,
                                now_unix_ms,
                                &report,
                            ),
                        }
                    }
                },
            },
            ChioPheromoneRelayCommands::Trend {
                reports_dir,
                event_dir,
                routing_profile,
                since_unix_ms,
                until_unix_ms,
                report,
            } => cmd_chio_pheromone_relay_trend(
                &reports_dir,
                &event_dir,
                &routing_profile,
                since_unix_ms,
                until_unix_ms,
                &report,
            ),
            ChioPheromoneRelayCommands::Directory { command } => match command {
                ChioPheromoneRelayDirectoryCommands::Inspect { state, report } => {
                    cmd_chio_pheromone_relay_directory_inspect(&state, &report)
                }
                ChioPheromoneRelayDirectoryCommands::Promote {
                    state,
                    candidate,
                    trusted_issuers,
                    profile,
                    now_unix_ms,
                    report,
                } => cmd_chio_pheromone_relay_directory_promote(
                    &state,
                    &candidate,
                    &trusted_issuers,
                    profile.into(),
                    now_unix_ms,
                    &report,
                ),
                ChioPheromoneRelayDirectoryCommands::Reject {
                    state,
                    candidate,
                    reason,
                    now_unix_ms,
                    report,
                } => cmd_chio_pheromone_relay_directory_reject(
                    &state,
                    &candidate,
                    &reason,
                    now_unix_ms,
                    &report,
                ),
            },
            ChioPheromoneRelayCommands::Supervisor { command } => match command {
                ChioPheromoneRelaySupervisorCommands::Lint { profile, report } => {
                    cmd_chio_pheromone_relay_supervisor_lint(&profile, &report)
                }
            },
        },
    }
}
