use super::*;

pub(crate) fn dispatch_chio_runtime_command(command: ChioRuntimeCommands) -> Result<(), CliError> {
    match command {
        ChioRuntimeCommands::Admit {
            request,
            admission_profile,
            admission_bundle,
            runtime_trust_input,
            trusted_verifiers,
            pheromone_query_report,
            runtime_pheromone_policy,
            runtime_peer_weights,
            action_class_id,
            trust_floor_state,
            store,
            now_unix_ms,
            report,
        } => cmd_chio_runtime_admit(
            &request,
            &admission_profile,
            &admission_bundle,
            runtime_trust_input.as_deref(),
            trusted_verifiers.as_deref(),
            pheromone_query_report.as_deref(),
            runtime_pheromone_policy.as_deref(),
            runtime_peer_weights.as_deref(),
            action_class_id.as_deref(),
            trust_floor_state.as_deref(),
            &store,
            now_unix_ms,
            &report,
        ),
        ChioRuntimeCommands::SignTrustInput {
            body,
            signing_seed_file,
            out,
        } => cmd_chio_runtime_sign_trust_input(&body, &signing_seed_file, &out),
        ChioRuntimeCommands::Policy { command } => match command {
            ChioRuntimePolicyCommands::Sign {
                body,
                signing_seed_file,
                out,
            } => cmd_chio_runtime_sign_policy(&body, &signing_seed_file, &out),
        },
        ChioRuntimeCommands::PeerWeights { command } => match command {
            ChioRuntimePeerWeightsCommands::Hash { body, out } => {
                cmd_chio_runtime_peer_weights_hash(&body, &out)
            }
            ChioRuntimePeerWeightsCommands::Sign {
                body,
                signing_seed_file,
                out,
            } => cmd_chio_runtime_sign_peer_weights(&body, &signing_seed_file, &out),
        },
        ChioRuntimeCommands::Pheromone { command } => match command {
            ChioRuntimePheromoneCommands::SignQueryReport {
                body,
                signing_seed_file,
                out,
            } => cmd_chio_runtime_sign_pheromone_query_report(&body, &signing_seed_file, &out),
            ChioRuntimePheromoneCommands::Evaluate {
                admission_bundle,
                runtime_trust_input,
                trusted_verifiers,
                pheromone_query_report,
                runtime_pheromone_policy,
                runtime_peer_weights,
                action_class_id,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_pheromone_evaluate(
                &admission_bundle,
                &runtime_trust_input,
                &trusted_verifiers,
                &pheromone_query_report,
                &runtime_pheromone_policy,
                &runtime_peer_weights,
                action_class_id.as_deref(),
                now_unix_ms,
                &report,
            ),
        },
        ChioRuntimeCommands::Orchestrate { command } => match command {
            ChioRuntimeOrchestrateCommands::Lint { profile, report } => {
                cmd_chio_runtime_orchestrate_lint(&profile, &report)
            }
            ChioRuntimeOrchestrateCommands::Plan {
                profile,
                run_contract,
                store,
                evidence_dir,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_orchestrate_plan(
                &profile,
                &run_contract,
                &store,
                &evidence_dir,
                now_unix_ms,
                &report,
            ),
            ChioRuntimeOrchestrateCommands::Run {
                profile,
                run_contract,
                store,
                evidence_dir,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_orchestrate_run(
                &profile,
                &run_contract,
                &store,
                &evidence_dir,
                now_unix_ms,
                &report,
            ),
            ChioRuntimeOrchestrateCommands::Resume {
                profile,
                resume_plan,
                store,
                evidence_dir,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_orchestrate_resume(
                &profile,
                &resume_plan,
                &store,
                &evidence_dir,
                now_unix_ms,
                &report,
            ),
            ChioRuntimeOrchestrateCommands::Status {
                profile,
                store,
                evidence_dir,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_orchestrate_status(
                &profile,
                &store,
                &evidence_dir,
                now_unix_ms.unwrap_or_else(unix_now_ms),
                &report,
            ),
            ChioRuntimeOrchestrateCommands::Drift {
                profile,
                runs_dir,
                since_unix_ms,
                until_unix_ms,
                report,
            } => cmd_chio_runtime_orchestrate_drift(
                &profile,
                &runs_dir,
                since_unix_ms,
                until_unix_ms,
                &report,
            ),
        },
        ChioRuntimeCommands::Ops { command } => match command {
            ChioRuntimeOpsCommands::Supervise {
                supervisor_profile,
                store,
                evidence_root,
                provider_bindings,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_ops_status(
                &supervisor_profile,
                &store,
                &evidence_root,
                provider_bindings.as_deref(),
                Some(now_unix_ms),
                &report,
            ),
            ChioRuntimeOpsCommands::Tick {
                supervisor_profile,
                store,
                evidence_root,
                owner_id,
                now_unix_ms,
                max_runs,
                report,
            } => cmd_chio_runtime_ops_tick(
                &supervisor_profile,
                &store,
                &evidence_root,
                &owner_id,
                now_unix_ms,
                max_runs,
                &report,
            ),
            ChioRuntimeOpsCommands::Status {
                supervisor_profile,
                store,
                evidence_root,
                provider_bindings,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_ops_status(
                &supervisor_profile,
                &store,
                &evidence_root,
                provider_bindings.as_deref(),
                now_unix_ms,
                &report,
            ),
            ChioRuntimeOpsCommands::RecoveryDrill {
                supervisor_profile,
                run_id,
                store,
                evidence_root,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_ops_recovery_drill(
                &supervisor_profile,
                &run_id,
                &store,
                &evidence_root,
                now_unix_ms,
                &report,
            ),
            ChioRuntimeOpsCommands::EvidenceHealth {
                supervisor_profile,
                run_id,
                store,
                evidence_root,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_ops_evidence_health(
                &supervisor_profile,
                &run_id,
                &store,
                &evidence_root,
                now_unix_ms.unwrap_or_else(unix_now_ms),
                &report,
            ),
            ChioRuntimeOpsCommands::ProviderHealth {
                supervisor_profile,
                provider_bindings,
                now_unix_ms,
                report,
            } => cmd_chio_runtime_ops_provider_health(
                &supervisor_profile,
                &provider_bindings,
                now_unix_ms.unwrap_or_else(unix_now_ms),
                &report,
            ),
            ChioRuntimeOpsCommands::Retention { command } => match command {
                ChioRuntimeOpsRetentionCommands::Plan {
                    retention_profile,
                    store,
                    evidence_root,
                    now_unix_ms,
                    report,
                } => cmd_chio_runtime_ops_retention_plan(
                    &retention_profile,
                    &store,
                    &evidence_root,
                    now_unix_ms,
                    &report,
                ),
            },
        },
        ChioRuntimeCommands::RunLoopback {
            scenario,
            static_package,
            static_report,
            store_dir,
            now_unix_ms,
            out_dir,
        } => cmd_chio_runtime_run_loopback(
            &scenario,
            static_package.as_deref(),
            static_report.as_deref(),
            &store_dir,
            now_unix_ms,
            &out_dir,
        ),
    }
}
